-- Més exercicis A2 per als continguts de 4.1 Fonètica i ortografia
-- (20260930110000 en tenia 8-10 per contingut): s'afigen darrere dels que ja hi
-- ha, a partir de la posició `offset`, fins a uns 35 per contingut. Tornar a
-- aplicar el fitxer no els duplica: primer s'esborren les posicions > offset.

CREATE TEMP TABLE practice_more AS
SELECT * FROM jsonb_to_recordset($data$[
  {
    "id": "5340aadb-100f-428d-a1ad-6d866a54a2e6", "offset": 8,
    "exercises": [
      {"q": "Quina és la síl·laba tònica de «rellotge»?", "o": ["-llot-", "re-", "-ge"], "e": "Re-LLOT-ge és plana: la tònica és la penúltima síl·laba."},
      {"q": "Quina és la síl·laba tònica de «ordinador»?", "o": ["-dor", "or-", "-di-"], "e": "Or-di-na-DOR és aguda: la tònica és l'última síl·laba."},
      {"q": "Quina és la síl·laba tònica de «llibre»?", "o": ["lli-", "-bre"], "e": "LLI-bre és plana."},
      {"q": "Quina és la síl·laba tònica de «tomaca»?", "o": ["-ma-", "to-", "-ca"], "e": "To-MA-ca és plana acabada en vocal: per això no porta accent."},
      {"q": "Quina és la síl·laba tònica de «plàtan»?", "o": ["plà-", "-tan"], "e": "PLÀ-tan és plana; l'accent gràfic ens ho indica."},
      {"q": "Quina és la síl·laba tònica de «telèfon»?", "o": ["-lè-", "te-", "-fon"], "e": "Te-LÈ-fon és plana acabada en -n (no en -en): porta accent."},
      {"q": "Quina és la síl·laba tònica de «paella»?", "o": ["-e-", "pa-", "-lla"], "e": "Pa-E-lla és plana: la tònica és la penúltima síl·laba."},
      {"q": "Quina és la síl·laba tònica de «dinar»?", "o": ["-nar", "di-"], "e": "Di-NAR és aguda acabada en -r: no porta accent."},
      {"q": "Quina és la síl·laba tònica de «pantalons»?", "o": ["-lons", "pan-", "-ta-"], "e": "Pan-ta-LONS és aguda."},
      {"q": "Quina és la síl·laba tònica de «ciutat»?", "o": ["-tat", "ciu-"], "e": "Ciu-TAT és aguda acabada en -t: no porta accent."},
      {"q": "Quina és la síl·laba tònica de «música»?", "o": ["mú-", "-si-", "-ca"], "e": "MÚ-si-ca és esdrúixola."},
      {"q": "Quina és la síl·laba tònica de «bicicleta»?", "o": ["-cle-", "bi-", "-ci-", "-ta"], "e": "Bi-ci-CLE-ta és plana."},
      {"q": "Quina és la síl·laba tònica de «dimecres»?", "o": ["-me-", "di-", "-cres"], "e": "Di-ME-cres és plana acabada en -s: no porta accent."},
      {"q": "Quina és la síl·laba tònica de «setmana»?", "o": ["-ma-", "set-", "-na"], "e": "Set-MA-na és plana."},
      {"q": "Quina és la síl·laba tònica de «valencià»?", "o": ["-cià", "va-", "-len-"], "e": "Va-len-CIÀ és aguda acabada en vocal: porta accent."},
      {"q": "Quina és la síl·laba tònica de «Castelló»?", "o": ["-lló", "cas-", "-te-"], "e": "Cas-te-LLÓ és aguda acabada en vocal: porta accent."},
      {"q": "Quina és la síl·laba tònica de «Alacant»?", "o": ["-cant", "a-", "-la-"], "e": "A-la-CANT és aguda acabada en -nt: no porta accent."},
      {"q": "Quina d'estes paraules és aguda?", "o": ["cafè", "cadira", "número"], "e": "Ca-FÈ és aguda. Cadira és plana i número, esdrúixola."},
      {"q": "Quina d'estes paraules és aguda?", "o": ["menjar", "menja", "menjava"], "e": "Men-JAR és aguda. MEN-ja i men-JA-va són planes."},
      {"q": "Quina d'estes paraules és aguda?", "o": ["cançó", "taula", "àlbum"], "e": "Can-ÇÓ és aguda. Taula i àlbum són planes."},
      {"q": "Quina d'estes paraules és plana?", "o": ["germana", "camió", "llàgrima"], "e": "Ger-MA-na és plana. Camió és aguda i llàgrima, esdrúixola."},
      {"q": "Quina d'estes paraules és plana?", "o": ["fàcil", "sofà", "màquina"], "e": "FÀ-cil és plana. Sofà és aguda i màquina, esdrúixola."},
      {"q": "Quina d'estes paraules és esdrúixola?", "o": ["màquina", "ordinador", "plàtan"], "e": "MÀ-qui-na és esdrúixola. Ordinador és aguda i plàtan, plana."},
      {"q": "Quina d'estes paraules és esdrúixola?", "o": ["número", "cadira", "cançó"], "e": "NÚ-me-ro és esdrúixola."},
      {"q": "Quantes síl·labes té «finestra»?", "o": ["3", "2", "4"], "e": "Fi-nes-tra: tres síl·labes."},
      {"q": "Quantes síl·labes té «ordinador»?", "o": ["4", "3", "5"], "e": "Or-di-na-dor: quatre síl·labes."},
      {"q": "Quantes síl·labes té «pa»?", "o": ["1", "2", "3"], "e": "Pa és monosíl·laba: té una sola síl·laba."}
    ]
  },
  {
    "id": "3d8fbee8-b30f-491c-9906-c442729c5e3d", "offset": 8,
    "exercises": [
      {"q": "Quina d'estes paraules va primer en el diccionari?", "o": ["casa", "cotxe", "cuina"], "e": "Les tres comencen per c: es mira la segona lletra (a, o, u)."},
      {"q": "Quina d'estes paraules va l'última en el diccionari?", "o": ["zero", "xiquet", "vaca"], "e": "L'ordre és v, x, z: zero va l'última."},
      {"q": "Quina llista està en ordre alfabètic?", "o": ["gat, gos, gust", "gos, gat, gust", "gust, gat, gos"], "e": "Es mira la segona lletra: a, o, u."},
      {"q": "Quina d'estes paraules va primer en el diccionari?", "o": ["mar", "mare", "marit"], "e": "Mar és més curta i les tres lletres coincidixen: va primer. Després mare (e) i marit (i)."},
      {"q": "Quina lletra ve després de la «p» en l'alfabet?", "o": ["q", "r", "o"], "e": "L'ordre és ... o, p, q, r ..."},
      {"q": "Quina lletra ve abans de la «t» en l'alfabet?", "o": ["s", "u", "r"], "e": "L'ordre és ... r, s, t, u ..."},
      {"q": "Quina d'estes paraules té un dígraf?", "o": ["guerra", "gran", "gat"], "e": "En «guerra» hi ha dos dígrafs: gu (davant de e) i rr."},
      {"q": "Quantes lletres i quants sons té «llet»?", "o": ["4 lletres i 3 sons", "4 lletres i 4 sons", "3 lletres i 3 sons"], "e": "El dígraf ll fa un sol so: ll-e-t."},
      {"q": "Quantes lletres i quants sons té «any»?", "o": ["3 lletres i 2 sons", "3 lletres i 3 sons", "2 lletres i 2 sons"], "e": "El dígraf ny fa un sol so: a-ny."},
      {"q": "Quantes lletres i quants sons té «carro»?", "o": ["5 lletres i 4 sons", "5 lletres i 5 sons", "4 lletres i 4 sons"], "e": "El dígraf rr fa un sol so: c-a-rr-o."},
      {"q": "Quantes lletres i quants sons té «guitarra»?", "o": ["8 lletres i 6 sons", "8 lletres i 7 sons", "8 lletres i 8 sons"], "e": "Hi ha dos dígrafs: gu (davant de i) i rr."},
      {"q": "Quina d'estes paraules té el dígraf «ny»?", "o": ["muntanya", "música", "nit"], "e": "Mun-ta-nya: ny fa un sol so."},
      {"q": "En quina paraula «qu» és un dígraf (la u no sona)?", "o": ["quinze", "quatre", "quan"], "e": "Davant de e i i, «qu» fa un sol so /k/. En quatre i quan la u sí que sona."},
      {"q": "En quina paraula «gu» és un dígraf (la u no sona)?", "o": ["guerra", "aigua", "guant"], "e": "Davant de e i i, «gu» fa un sol so. En aigua i guant la u sí que sona."},
      {"q": "Com se separa en síl·labes «carrer»?", "o": ["car-rer", "ca-rrer", "carr-er"], "e": "El dígraf rr es separa: car-rer."},
      {"q": "Com se separa en síl·labes «passeig»?", "o": ["pas-seig", "pa-sseig", "pass-eig"], "e": "El dígraf ss es separa: pas-seig."},
      {"q": "Com se separa en síl·labes «senyor»?", "o": ["se-nyor", "sen-yor", "seny-or"], "e": "El dígraf ny no se separa: se-nyor."},
      {"q": "Com se separa en síl·labes «metge»?", "o": ["met-ge", "me-tge", "metg-e"], "e": "El dígraf tg es separa: met-ge."},
      {"q": "Com se separa en síl·labes «platja»?", "o": ["plat-ja", "pla-tja", "platj-a"], "e": "El dígraf tj es separa: plat-ja."},
      {"q": "Com se separa en síl·labes «caixa»?", "o": ["cai-xa", "ca-ixa", "caix-a"], "e": "El dígraf ix es separa: cai-xa."},
      {"q": "Com se separa en síl·labes «guitarra»?", "o": ["gui-tar-ra", "gu-i-tar-ra", "gui-ta-rra"], "e": "Gu no se separa i rr sí: gui-tar-ra."},
      {"q": "Com se separa en síl·labes «escola»?", "o": ["es-co-la", "e-sco-la", "esc-o-la"], "e": "Es-co-la: la s va amb la síl·laba anterior."},
      {"q": "Com se separa en síl·labes «aigua»?", "o": ["ai-gua", "a-i-gua", "aig-ua"], "e": "Ai-gua: ai i ua són diftongs i no se separen."},
      {"q": "Quantes síl·labes té «estudiant»?", "o": ["4", "3", "5"], "e": "Es-tu-di-ant: la i i la a són en síl·labes diferents."},
      {"q": "Quina frase té les paraules ben separades?", "o": ["Vaig a comprar pa.", "Vaiga comprar pa.", "Vaig acomprar pa."], "e": "Vaig / a / comprar / pa: cada paraula s'escriu separada."},
      {"q": "Quina frase té les paraules ben separades?", "o": ["Tinc una germana.", "Tincuna germana.", "Tinc unager mana."], "e": "Tinc / una / germana."},
      {"q": "Quina frase té les paraules ben separades?", "o": ["El meu amic és de Sueca.", "Elmeu amic és de Sueca.", "El meuamic ésde Sueca."], "e": "El / meu / amic / és / de / Sueca."}
    ]
  },
  {
    "id": "975ade8f-5197-4edc-bd4a-20dd8816d65f", "offset": 9,
    "exercises": [
      {"q": "Quina forma és correcta?", "o": ["cafè", "café", "cafe"], "e": "Ca-FÈ és aguda acabada en vocal; la e és oberta: cafè."},
      {"q": "Quina forma és correcta?", "o": ["també", "tambè", "tambe"], "e": "Tam-BÉ és aguda acabada en vocal; la e és tancada: també."},
      {"q": "Quina forma és correcta?", "o": ["dijous", "dijóus", "díjous"], "e": "Di-JOUS és aguda acabada en diftong + s: no porta accent."},
      {"q": "Quina forma és correcta?", "o": ["cançó", "canço", "cánço"], "e": "Can-ÇÓ és aguda acabada en vocal: porta accent."},
      {"q": "Quina forma és correcta?", "o": ["número", "numero", "numéro"], "e": "NÚ-me-ro és esdrúixola: sempre porta accent."},
      {"q": "Quina forma és correcta?", "o": ["fàcil", "facil", "fácil"], "e": "FÀ-cil és plana acabada en -l: porta accent. La a sempre porta accent obert (à)."},
      {"q": "Quina forma és correcta?", "o": ["arròs", "arros", "arrós"], "e": "Ar-RÒS és aguda acabada en vocal + s: porta accent, i la o és oberta."},
      {"q": "Quina forma és correcta?", "o": ["matí", "mati", "màti"], "e": "Ma-TÍ és aguda acabada en vocal: porta accent."},
      {"q": "Quina forma és correcta?", "o": ["divendres", "divèndres", "divendrés"], "e": "Di-VEN-dres és plana acabada en -s: no porta accent."},
      {"q": "Quina forma és correcta?", "o": ["dilluns", "dillúns", "dílluns"], "e": "Di-LLUNS és aguda acabada en -ns: no porta accent."},
      {"q": "Quina forma és correcta?", "o": ["pastís", "pastis", "pàstis"], "e": "Pas-TÍS és aguda acabada en vocal + s: porta accent."},
      {"q": "Quina forma és correcta?", "o": ["jardí", "jardi", "jàrdi"], "e": "Jar-DÍ és aguda acabada en vocal: porta accent."},
      {"q": "Quina forma és correcta?", "o": ["estiu", "estíu", "éstiu"], "e": "Es-TIU és aguda acabada en diftong: no porta accent."},
      {"q": "Quina forma és correcta?", "o": ["després", "despres", "desprès"], "e": "Des-PRÉS és aguda acabada en vocal + s: porta accent; la e és tancada."},
      {"q": "Quina forma és correcta?", "o": ["València", "Valéncia", "Valencia"], "e": "Va-LÈN-ci-a porta accent obert en la e."},
      {"q": "Quina forma és correcta?", "o": ["dinar", "dinàr", "dínar"], "e": "Di-NAR és aguda acabada en -r: no porta accent."},
      {"q": "Quina forma és correcta?", "o": ["àlbum", "album", "albúm"], "e": "ÀL-bum és plana acabada en -m: porta accent."},
      {"q": "Quina forma és correcta?", "o": ["meló", "melo", "mèlo"], "e": "Me-LÓ és aguda acabada en vocal: porta accent."},
      {"q": "Quina d'estes paraules està ben escrita sense accent?", "o": ["germans", "cafe", "musica"], "e": "Ger-MANS és aguda acabada en -ns: no porta accent. Cafè i música sí que en porten."},
      {"q": "Per què no porta accent «taula»?", "o": ["Perquè és plana acabada en vocal", "Perquè és aguda", "Perquè és esdrúixola"], "e": "TAU-la és plana acabada en vocal: les planes acabades en vocal no s'accentuen."},
      {"q": "Per què porta accent «pastís»?", "o": ["Perquè és aguda acabada en vocal + s", "Perquè és plana acabada en -s", "Perquè és esdrúixola"], "e": "Les agudes acabades en vocal, vocal + s, -en o -in porten accent."},
      {"q": "Escriu la paraula amb l'accent correcte: sofa (seient per a dues o tres persones).", "a": ["sofà"], "e": "So-FÀ és aguda acabada en vocal."},
      {"q": "Escriu la paraula amb l'accent correcte: rapid (que va molt de pressa).", "a": ["ràpid"], "e": "RÀ-pid és plana acabada en -d: porta accent."},
      {"q": "Escriu la paraula amb l'accent correcte: autobus.", "a": ["autobús"], "e": "Au-to-BÚS és aguda acabada en vocal + s."},
      {"q": "Escriu la paraula amb l'accent correcte: maquina (de cosir, de rentar...).", "a": ["màquina"], "e": "MÀ-qui-na és esdrúixola: sempre porta accent."},
      {"q": "Escriu la paraula amb l'accent correcte: tambe.", "a": ["també"], "e": "Tam-BÉ és aguda acabada en vocal, amb e tancada."}
    ]
  },
  {
    "id": "b832d33a-d974-4137-8d8c-d23523f6d44a", "offset": 10,
    "exercises": [
      {"q": "Completa: ___ aigua està molt freda.", "o": ["L'", "La", "El"], "e": "L'article s'apostrofa davant de vocal: l'aigua."},
      {"q": "Completa: ___ home del bar és molt simpàtic.", "o": ["L'", "El", "Lo"], "e": "Davant de h muda també s'apostrofa: l'home."},
      {"q": "Completa: Ja és ___ hora de dinar.", "o": ["l'", "la", "el"], "e": "L'hora: la h és muda i la o és tònica."},
      {"q": "Completa: ___ illa és molt menuda.", "o": ["L'", "La", "El"], "e": "L'illa: la i és tònica, per això «la» s'apostrofa."},
      {"q": "Completa: ___ ordinador no funciona.", "o": ["L'", "El", "La"], "e": "El + ordinador → l'ordinador."},
      {"q": "Quina forma és correcta?", "o": ["la infermera", "l'infermera", "l' infermera"], "e": "«La» no s'apostrofa davant de i o u àtones: la infermera."},
      {"q": "Quina forma és correcta?", "o": ["la història", "l'història", "l' història"], "e": "His-TÒ-ri-a: la i és àtona, per això no s'apostrofa."},
      {"q": "Quina forma és correcta?", "o": ["l'avió", "el avió", "la avió"], "e": "Davant de vocal: l'avió."},
      {"q": "Quina forma és correcta?", "o": ["l'ull", "el ull", "lo ull"], "e": "Davant de vocal: l'ull."},
      {"q": "Quina forma és correcta?", "o": ["el pare", "l'pare", "lo pare"], "e": "Davant de consonant no s'apostrofa: el pare."},
      {"q": "Quina forma és correcta?", "o": ["l'escola i l'institut", "la escola i el institut", "l'escola i el institut"], "e": "Tots dos comencen per vocal: s'apostrofen."},
      {"q": "Completa: Són ___ una del migdia.", "o": ["la", "l'", "lo"], "e": "Per a les hores es diu «la una», sense apòstrof."},
      {"q": "Completa: Vinc ___ ajuntament.", "o": ["de l'", "del", "d'el"], "e": "Davant de vocal, l'article s'apostrofa i ja no hi ha contracció: de l'ajuntament."},
      {"q": "Completa: Anem ___ hospital.", "o": ["a l'", "al", "a el"], "e": "L'hospital: amb l'article apostrofat no es fa contracció."},
      {"q": "Completa: Vaig ___ metge.", "o": ["al", "a el", "a l'"], "e": "A + el → al."},
      {"q": "Completa: Tinc una casa ___ camp.", "o": ["al", "a el", "a l'"], "e": "A + el → al."},
      {"q": "Completa: Parlem ___ professors.", "o": ["dels", "de els", "d'els"], "e": "De + els → dels."},
      {"q": "Completa: Done el regal ___ xiquets.", "o": ["als", "a els", "a los"], "e": "A + els → als."},
      {"q": "Completa: Caminem ___ parc.", "o": ["pel", "per el", "per l'"], "e": "Per + el → pel."},
      {"q": "Completa: És el cotxe ___ Anna.", "o": ["d'", "de", "del"], "e": "La preposició «de» s'apostrofa davant de vocal: d'Anna."},
      {"q": "Completa: Vull una tassa ___ aigua.", "o": ["d'", "de", "del"], "e": "D'aigua: «de» davant de vocal."},
      {"q": "Completa: Vull una tassa ___ llet.", "o": ["de", "d'", "del"], "e": "Davant de consonant, «de» no s'apostrofa."},
      {"q": "Completa: Soc ___ Alacant.", "o": ["d'", "de", "del"], "e": "D'Alacant: «de» davant de vocal."},
      {"q": "Escriu la contracció: per + el", "a": ["pel"], "e": "Per + el → pel (passegem pel parc)."},
      {"q": "Escriu la contracció: a + el", "a": ["al"], "e": "A + el → al (anem al cine)."}
    ]
  },
  {
    "id": "b3f10344-a6e4-43f5-9a59-3dd9dd7ad9a5", "offset": 9,
    "exercises": [
      {"q": "Completa: cami__a (peça de roba)", "o": ["s", "ss", "ç"], "e": "Camisa: s sonora entre vocals → s."},
      {"q": "Completa: cla__e (aula de l'escola)", "o": ["ss", "s", "ç"], "e": "Classe: s sorda entre vocals → ss."},
      {"q": "Completa: ta__a (per a beure el café)", "o": ["ss", "s", "ç"], "e": "Tassa: s sorda entre vocals → ss."},
      {"q": "Completa: pre__a (Tinc molta ___, arribe tard!)", "o": ["ss", "s", "ç"], "e": "Pressa: s sorda entre vocals → ss."},
      {"q": "Completa: pi__ina (per a nadar)", "o": ["sc", "ss", "c"], "e": "Piscina s'escriu amb sc."},
      {"q": "Completa: __ol (brilla al cel)", "o": ["s", "c", "z"], "e": "Sol: a principi de paraula, davant de o, el so sord és s."},
      {"q": "Completa: __abates (les portem als peus)", "o": ["s", "c", "z"], "e": "Sabates: s a principi de paraula."},
      {"q": "Completa: __ucre (endolcix el café)", "o": ["s", "c", "z"], "e": "Sucre: s a principi de paraula."},
      {"q": "Completa: __inc (el número 5)", "o": ["c", "s", "z"], "e": "Cinc: c davant de i."},
      {"q": "Completa: __entre (el mig de la ciutat)", "o": ["c", "s", "z"], "e": "Centre: c davant de e."},
      {"q": "Completa: __ervesa (beguda)", "o": ["c", "s", "z"], "e": "Cervesa: c davant de e i s sonora entre vocals."},
      {"q": "Completa: po__ar (col·locar una cosa en un lloc)", "o": ["s", "ss", "ç"], "e": "Posar: s sonora entre vocals → s."},
      {"q": "Completa: bra__ (part del cos)", "o": ["ç", "s", "ss"], "e": "Braç: a final de paraula el so sord pot ser ç."},
      {"q": "Completa: for__a (energia per a fer una cosa)", "o": ["ç", "c", "ss"], "e": "Força: ç davant de a."},
      {"q": "Completa: No tinc for__es.", "o": ["c", "ç", "ss"], "e": "Forces: davant de e s'escriu c, no ç."},
      {"q": "El plural de «braç» és...", "o": ["braços", "bracos", "brasos"], "e": "Braços: davant de o es manté la ç."},
      {"q": "El plural de «gos» és...", "o": ["gossos", "gosos", "goços"], "e": "Gossos: la s sorda entre vocals s'escriu ss."},
      {"q": "El plural de «mes» és...", "o": ["mesos", "messos", "meços"], "e": "Mesos: s sonora entre vocals → s."},
      {"q": "El femení de «francés» és...", "o": ["francesa", "francessa", "franceça"], "e": "Francesa: s sonora entre vocals → s."},
      {"q": "El femení de «gros» és...", "o": ["grossa", "grosa", "groça"], "e": "Grossa: s sorda entre vocals → ss."},
      {"q": "Quina paraula vol dir «buscar animals per a atrapar-los»?", "o": ["caçar", "casar", "cassar"], "e": "Caçar (amb ç). Casar vol dir unir en matrimoni."},
      {"q": "Completa: tre__e (el número 13)", "o": ["tz", "ts", "z"], "e": "Tretze: s sonora després de t → tz."},
      {"q": "Completa: qui__e (el número 15)", "o": ["nz", "ns", "nc"], "e": "Quinze: s sonora després de n → z."},
      {"q": "Completa: do__ (el número 2)", "o": ["s", "ss", "ç"], "e": "Dos: s a final de paraula."},
      {"q": "Escriu en lletres el número 11.", "a": ["onze"], "e": "Onze: s sonora després de n → z."},
      {"q": "Escriu en lletres el número 16.", "a": ["setze"], "e": "Setze: s sonora després de t → tz."}
    ]
  },
  {
    "id": "5e910bc3-c0d6-486e-9edc-852f7f7684b2", "offset": 10,
    "exercises": [
      {"q": "Completa: __ardí (lloc amb plantes i flors)", "o": ["j", "g", "x"], "e": "Jardí: j davant de a."},
      {"q": "Completa: __ent (moltes persones)", "o": ["g", "j", "x"], "e": "Gent: g davant de e."},
      {"q": "Completa: __ener (el primer mes de l'any)", "o": ["g", "j", "x"], "e": "Gener: g davant de e."},
      {"q": "Completa: __uliol (el setè mes de l'any)", "o": ["j", "g", "x"], "e": "Juliol: j davant de u."},
      {"q": "Completa: __ugar (divertir-se amb un joc)", "o": ["j", "g", "x"], "e": "Jugar: j davant de u."},
      {"q": "Completa: men__ar (prendre aliments)", "o": ["j", "g", "tj"], "e": "Menjar: j davant de a."},
      {"q": "Completa: Jo men__e pa amb tomaca.", "o": ["g", "j", "tg"], "e": "Menge: davant de e s'escriu g."},
      {"q": "Completa: pu__ar (anar cap amunt)", "o": ["j", "g", "x"], "e": "Pujar: j davant de a."},
      {"q": "Completa: Nosaltres pu__em a la muntanya.", "o": ["g", "j", "x"], "e": "Pugem: davant de e canvia a g."},
      {"q": "Completa: plu__a (aigua que cau del cel)", "o": ["j", "g", "tj"], "e": "Pluja: j davant de a."},
      {"q": "Completa: pà__ina (d'un llibre)", "o": ["g", "j", "tg"], "e": "Pàgina: g davant de i."},
      {"q": "Completa: via__ar (anar d'un lloc a un altre)", "o": ["tj", "tg", "j"], "e": "Viatjar: tj davant de a."},
      {"q": "Completa: un via__e a París", "o": ["tg", "tj", "g"], "e": "Viatge: tg davant de e."},
      {"q": "Completa: rello__e (marca l'hora)", "o": ["tg", "tj", "g"], "e": "Rellotge: tg davant de e."},
      {"q": "Completa: ro__ (el color de la sang)", "o": ["ig", "tx", "ix"], "e": "Roig: a final de paraula, darrere de vocal, ig."},
      {"q": "Completa: __ocolata (llepolia de cacau)", "o": ["x", "tx", "ix"], "e": "Xocolata: a principi de paraula, x."},
      {"q": "Completa: __iquet (persona de poca edat)", "o": ["x", "tx", "ix"], "e": "Xiquet: a principi de paraula, x."},
      {"q": "Completa: cai__a (recipient per a guardar coses)", "o": ["ix", "x", "tx"], "e": "Caixa: darrere de vocal, ix."},
      {"q": "Completa: dibu__ar (fer un dibuix)", "o": ["ix", "x", "tx"], "e": "Dibuixar: darrere de vocal, ix."},
      {"q": "Completa: madu__a (fruita roja i xicoteta)", "o": ["ix", "x", "tx"], "e": "Maduixa: darrere de vocal, ix."},
      {"q": "Completa: fi__a (targeta amb informació)", "o": ["tx", "ix", "x"], "e": "Fitxa: so africat, tx."},
      {"q": "Completa: despa__ (lloc on treballa el director)", "o": ["tx", "ix", "x"], "e": "Despatx: so africat, tx."},
      {"q": "Completa: pe__os (plural de peix)", "o": ["ix", "x", "tx"], "e": "Peixos: es manté ix."},
      {"q": "Escriu el plural de «platja».", "a": ["platges"], "e": "Platja → platges: davant de e, tj canvia a tg."},
      {"q": "Escriu el verb que correspon a «viatge».", "a": ["viatjar"], "e": "Viatge → viatjar: davant de a, tg canvia a tj."}
    ]
  },
  {
    "id": "77e69eed-4550-4420-a66e-1f226c99a989", "offset": 9,
    "exercises": [
      {"q": "Completa: __et (beguda blanca)", "o": ["ll", "l"], "e": "Llet: dígraf ll a principi de paraula."},
      {"q": "Completa: __imona (fruita groga i àcida)", "o": ["ll", "l"], "e": "Llimona: dígraf ll."},
      {"q": "Completa: __apis (per a escriure i dibuixar)", "o": ["ll", "l"], "e": "Llapis: dígraf ll."},
      {"q": "Completa: __ençol (roba del llit)", "o": ["ll", "l"], "e": "Llençol: dígraf ll."},
      {"q": "Completa: __adre (persona que roba)", "o": ["ll", "l"], "e": "Lladre: dígraf ll."},
      {"q": "Completa: __ínia (ratlla en un paper)", "o": ["l", "ll"], "e": "Línia: l simple."},
      {"q": "Completa: __ent (que va a poc a poc)", "o": ["l", "ll"], "e": "Lent: l simple."},
      {"q": "Completa: cava__ (animal que es pot muntar)", "o": ["ll", "l"], "e": "Cavall: ll a final de paraula."},
      {"q": "Completa: ga__ (canta de matí)", "o": ["ll", "l"], "e": "Gall: ll a final de paraula."},
      {"q": "Completa: cabe__ (el tenim al cap)", "o": ["ll", "l"], "e": "Cabell: ll a final de paraula."},
      {"q": "Completa: sa__ (condiment blanc)", "o": ["l", "ll"], "e": "Sal: l simple."},
      {"q": "Completa: ce__ (el veiem blau de dia)", "o": ["l", "ll"], "e": "Cel: l simple."},
      {"q": "Completa: me__ (la fan les abelles)", "o": ["l", "ll"], "e": "Mel: l simple."},
      {"q": "Completa: abe__a (insecte que fa mel)", "o": ["ll", "l"], "e": "Abella: ll entre vocals."},
      {"q": "Completa: fu__a (d'un arbre)", "o": ["ll", "l"], "e": "Fulla: ll entre vocals."},
      {"q": "Completa: ce__a (pèl damunt de l'ull)", "o": ["ll", "l"], "e": "Cella: ll entre vocals."},
      {"q": "Completa: ampo__a (d'aigua o de vi)", "o": ["ll", "l"], "e": "Ampolla: ll entre vocals."},
      {"q": "Completa: sa__a (habitació gran de la casa)", "o": ["l", "ll"], "e": "Sala: l simple entre vocals."},
      {"q": "Completa: vo__ar (fer com els ocells)", "o": ["l", "ll"], "e": "Volar: l simple."},
      {"q": "Completa: ca__ar (no parlar)", "o": ["ll", "l"], "e": "Callar: ll entre vocals."},
      {"q": "Completa: a__í (en aquell lloc)", "o": ["ll", "l"], "e": "Allí: ll entre vocals."},
      {"q": "Completa: mo__t (una gran quantitat)", "o": ["l", "ll"], "e": "Molt: l simple."},
      {"q": "Quina forma és correcta?", "o": ["lluny", "luny", "llunny"], "e": "Lluny: ll a principi i ny al final."},
      {"q": "Quina forma és correcta?", "o": ["llibreria", "libreria", "llibrería"], "e": "Llibreria, com llibre."},
      {"q": "Escriu el contrari de «curt».", "a": ["llarg"], "e": "Llarg, amb ll inicial."},
      {"q": "Escriu el contrari de «jove».", "a": ["vell"], "e": "Vell, amb ll final."}
    ]
  },
  {
    "id": "4a7ebcc7-0141-4e17-bae8-6386275e31dd", "offset": 8,
    "exercises": [
      {"q": "Completa: ca__o (vehicle tirat per un cavall)", "o": ["rr", "r"], "e": "Carro: r forta entre vocals → rr."},
      {"q": "Completa: gue__a (conflicte entre països)", "o": ["rr", "r"], "e": "Guerra: r forta entre vocals → rr."},
      {"q": "Completa: a__òs (el posem a la paella)", "o": ["rr", "r"], "e": "Arròs: r forta entre vocals → rr."},
      {"q": "Completa: guita__a (instrument de música)", "o": ["rr", "r"], "e": "Guitarra: r forta entre vocals → rr."},
      {"q": "Completa: ba__a (de pa)", "o": ["rr", "r"], "e": "Barra: r forta entre vocals → rr."},
      {"q": "Completa: có__er (anar molt de pressa a peu)", "o": ["rr", "r"], "e": "Córrer: r forta entre vocals → rr."},
      {"q": "Completa: fe__o (metall dur)", "o": ["rr", "r"], "e": "Ferro: r forta entre vocals → rr."},
      {"q": "Completa: e__or (equivocació)", "o": ["rr", "r"], "e": "Error: r forta entre vocals → rr."},
      {"q": "Completa: ba__et (el portem al cap)", "o": ["rr", "r"], "e": "Barret: r forta entre vocals → rr."},
      {"q": "Completa: pe__uquer (talla els cabells)", "o": ["rr", "r"], "e": "Perruquer: r forta entre vocals → rr."},
      {"q": "Completa: pe__a (fruita)", "o": ["r", "rr"], "e": "Pera: r suau entre vocals."},
      {"q": "Completa: ta__onja (fruita típica valenciana)", "o": ["r", "rr"], "e": "Taronja: r suau entre vocals."},
      {"q": "Completa: ma__e (la dona que t'ha tingut)", "o": ["r", "rr"], "e": "Mare: r suau entre vocals."},
      {"q": "Completa: pa__e (l'home que t'ha tingut)", "o": ["r", "rr"], "e": "Pare: r suau entre vocals."},
      {"q": "Completa: __iu (aigua que corre fins a la mar)", "o": ["r", "rr"], "e": "Riu: a principi de paraula, r forta però amb una sola r."},
      {"q": "Completa: __oda (d'un cotxe o d'una bici)", "o": ["r", "rr"], "e": "Roda: a principi de paraula, sempre una sola r."},
      {"q": "Completa: __ellotge (marca l'hora)", "o": ["r", "rr"], "e": "Rellotge: a principi de paraula, una sola r."},
      {"q": "Completa: En__ic (nom de persona)", "o": ["r", "rr"], "e": "Enric: darrere de n, la r sona forta però s'escriu amb una sola r."},
      {"q": "Completa: Is__ael (nom de persona)", "o": ["r", "rr"], "e": "Israel: darrere de s, la r sona forta però s'escriu amb una sola r."},
      {"q": "Completa: ve__d (el color de l'herba)", "o": ["r", "rr"], "e": "Verd: davant de consonant, sempre una sola r."},
      {"q": "Completa: po__ta (per a entrar a casa)", "o": ["r", "rr"], "e": "Porta: davant de consonant, sempre una sola r."},
      {"q": "Completa: ma__ó (color de la xocolata)", "o": ["rr", "r"], "e": "Marró: r forta entre vocals → rr."},
      {"q": "En quina d'estes paraules la r és suau?", "o": ["cara", "carro", "riu"], "e": "Cara: r suau entre vocals. En carro i riu és forta."},
      {"q": "En quina d'estes paraules sona la r forta?", "o": ["Enric", "Maria", "pera"], "e": "Darrere de n la r sona forta."},
      {"q": "Escriu en lletres el número 4.", "a": ["quatre"], "e": "Quatre: r suau darrere de t."},
      {"q": "Escriu en lletres el número 3.", "a": ["tres"], "e": "Tres, amb una sola r."},
      {"q": "Escriu el contrari de «dolç».", "a": ["amarg"], "e": "Amarg: r davant de consonant, una sola r."}
    ]
  },
  {
    "id": "c84eadef-dfd6-44d0-9864-61e37ef55e97", "offset": 9,
    "exercises": [
      {"q": "Quina forma és correcta?", "o": ["història", "istòria", "històrya"], "e": "Història porta h inicial."},
      {"q": "Quina forma és correcta?", "o": ["hotel", "otel", "hotél"], "e": "Hotel: h inicial muda."},
      {"q": "Quina forma és correcta?", "o": ["herba", "erba", "hèrba"], "e": "Herba: h inicial muda."},
      {"q": "Quina forma és correcta?", "o": ["hui", "ui", "húi"], "e": "Hui (el dia d'avui) porta h."},
      {"q": "Quina forma és correcta?", "o": ["hort", "ort", "hòrt"], "e": "Hort: h inicial muda."},
      {"q": "Quina forma és correcta?", "o": ["hortalissa", "ortalissa", "hortalisa"], "e": "Hortalissa: amb h, com hort, i amb ss."},
      {"q": "Quina forma és correcta?", "o": ["habitació", "abitació", "habitaciò"], "e": "Habitació: h inicial i accent tancat en la o."},
      {"q": "Quina forma és correcta?", "o": ["humit", "umit", "húmit"], "e": "Humit: h inicial."},
      {"q": "Quina forma és correcta?", "o": ["humor", "umor", "humòr"], "e": "Humor: h inicial."},
      {"q": "Quina forma és correcta?", "o": ["helicòpter", "elicòpter", "helicópter"], "e": "Helicòpter: h inicial i o oberta."},
      {"q": "Quina forma és correcta?", "o": ["prohibit", "proibit", "prohíbit"], "e": "Prohibit porta h entre vocals."},
      {"q": "Quina forma és correcta?", "o": ["vehicle", "veicle", "vehícle"], "e": "Vehicle porta h entre vocals."},
      {"q": "Quina forma és correcta? (el ponen les gallines)", "o": ["ou", "hou", "óu"], "e": "Ou s'escriu sense h (no com el castellà «huevo»)."},
      {"q": "Quina forma és correcta? (part del cos per a sentir)", "o": ["orella", "horella", "horeya"], "e": "Orella s'escriu sense h."},
      {"q": "Quina forma és correcta? (part dura de l'esquelet)", "o": ["os", "hos", "òs"], "e": "Os s'escriu sense h (plural: ossos)."},
      {"q": "Completa: Tu ___ vist la pel·lícula?", "o": ["has", "as", "hàs"], "e": "Has és el verb haver (has vist)."},
      {"q": "Completa: Ell ___ dinat a casa.", "o": ["ha", "a", "hà"], "e": "Ha és el verb haver (ha dinat)."},
      {"q": "Completa: Demà vaig ___ Castelló.", "o": ["a", "ha", "hà"], "e": "Ací és la preposició «a», sense h."},
      {"q": "Completa: Vosaltres ___ estudiat molt.", "o": ["heu", "eu", "héu"], "e": "Heu és el verb haver (heu estudiat)."},
      {"q": "Completa: A casa ___ tres habitacions.", "o": ["hi ha", "i ha", "hi a"], "e": "Hi ha: verb haver-hi."},
      {"q": "Completa: No ___ ha pa.", "o": ["hi", "i", "y"], "e": "No hi ha: el pronom hi porta h."},
      {"q": "Completa: Pere ___ Maria són germans.", "o": ["i", "hi", "y"], "e": "La conjunció i s'escriu sense h."},
      {"q": "Completa: ___ dic Joan.", "o": ["Em", "Hem", "Hen"], "e": "Em (pronom) va sense h. «Hem» és el verb haver."},
      {"q": "Completa: Nosaltres ___ arribat prompte.", "o": ["hem", "em", "hen"], "e": "Hem és el verb haver (hem arribat)."},
      {"q": "Escriu la paraula: el dia abans de hui.", "a": ["ahir"], "e": "Ahir porta h entre vocals."},
      {"q": "Escriu la paraula: l'estació de l'any més freda.", "a": ["hivern"], "e": "Hivern: amb h i amb v."}
    ]
  },
  {
    "id": "e5d6e371-5128-48a1-a4be-01a98a83bedb", "offset": 8,
    "exercises": [
      {"q": "Quina frase està ben escrita?", "o": ["Maria és de València.", "maria és de València.", "Maria és de valència."], "e": "Majúscula a l'inici de frase i en els noms de persona i de lloc."},
      {"q": "Quina frase està ben escrita?", "o": ["El meu gos es diu Tobi.", "El meu Gos es diu Tobi.", "el meu gos es diu tobi."], "e": "El nom de l'animal (Tobi) va en majúscula; «gos», en minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Vaig a París a l'agost.", "Vaig a parís a l'Agost.", "Vaig a París a l'Agost."], "e": "Noms de ciutat en majúscula; mesos en minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Tinc un amic francés.", "Tinc un amic Francés.", "tinc un amic francés."], "e": "Els gentilicis (francés, valencià...) van en minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Per Nadal anem al poble.", "Per nadal anem al poble.", "per Nadal anem al Poble."], "e": "Les festes (Nadal, Pasqua) van en majúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Els valencians celebren les Falles al març.", "Els Valencians celebren les falles al Març.", "Els valencians celebren les falles al Març."], "e": "Falles (la festa) en majúscula; gentilicis i mesos en minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["El riu Túria passa per València.", "El Riu túria passa per València.", "El riu túria passa per València."], "e": "«Riu» en minúscula; el nom propi (Túria), en majúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Visc a l'avinguda del Port.", "Visc a l'Avinguda del port.", "Visc a l'avinguda del port."], "e": "«Avinguda» en minúscula; el nom propi (Port), en majúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["El dilluns tinc classe d'anglés.", "El Dilluns tinc classe d'Anglés.", "El dilluns tinc classe d'Anglés."], "e": "Dies de la setmana i llengües en minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["M'agrada molt la primavera.", "M'agrada molt la Primavera.", "m'agrada molt la primavera."], "e": "Les estacions de l'any van en minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Em dic Laura Martí Soler.", "Em dic laura martí soler.", "Em dic Laura martí soler."], "e": "El nom i els cognoms van en majúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["El meu germà viu a Nova York.", "El meu germà viu a nova york.", "El meu Germà viu a Nova York."], "e": "Noms de ciutat en majúscula (totes les paraules); «germà», en minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Ahir vaig anar al cine. Després vam sopar.", "Ahir vaig anar al cine. després vam sopar.", "ahir vaig anar al cine. Després vam sopar."], "e": "Després d'un punt es comença amb majúscula."},
      {"q": "Quina frase està completa i ben puntuada?", "o": ["Em dic Pau i visc a Elx.", "Em dic Pau i visc a Elx", "em dic Pau i visc a Elx."], "e": "Majúscula a l'inici i punt al final."},
      {"q": "Quina frase està ben escrita?", "o": ["Vols un café?", "¿Vols un café?", "Vols un café¿"], "e": "En valencià normalment només es posa l'interrogant final."},
      {"q": "Quina frase està ben escrita?", "o": ["Que bonic!", "¡Que bonic!", "Que bonic¡"], "e": "En valencià normalment només es posa el signe d'admiració final."},
      {"q": "Quin signe falta? «On vius__»", "o": ["?", "!", "."], "e": "És una pregunta: interrogant al final."},
      {"q": "Quin signe falta? «Quants anys tens__»", "o": ["?", "!", ":"], "e": "És una pregunta: interrogant al final."},
      {"q": "Quin signe falta? «Quina calor fa__»", "o": ["!", "?", ","], "e": "Expressa una emoció o sorpresa: admiració."},
      {"q": "Quin signe falta? «Hui és dimarts__»", "o": [".", "?", ":"], "e": "És una afirmació: punt final."},
      {"q": "Quin signe falta? «Compra pa, ous__ llet i sucre.»", "o": [",", ":", "?"], "e": "La coma separa els elements d'una enumeració."},
      {"q": "Quina frase té la coma ben posada?", "o": ["Joan, vine ací!", "Joan vine, ací!", "Joan vine ací,!"], "e": "El nom de la persona a qui parlem se separa amb una coma."},
      {"q": "Quina frase té la coma ben posada?", "o": ["Hola, Marta, com estàs?", "Hola Marta com, estàs?", "Hola, Marta com, estàs?"], "e": "El nom de la persona a qui parlem va entre comes."},
      {"q": "Quina frase té les comes ben posades?", "o": ["A casa tinc un gat, un gos i dos peixos.", "A casa tinc, un gat un gos i dos peixos.", "A casa tinc un gat un gos, i dos peixos."], "e": "Coma entre els elements de la llista; davant de la «i» final, no."},
      {"q": "Quina frase usa bé els dos punts?", "o": ["Tinc dues germanes: Laura i Carla.", "Tinc dues: germanes Laura i Carla.", "Tinc dues germanes Laura: i Carla."], "e": "Els dos punts introduïxen els elements que s'anuncien."},
      {"q": "Quin signe es posa al final d'una frase que afirma una cosa?", "o": ["El punt (.)", "L'interrogant (?)", "Els dos punts (:)"], "e": "Les frases afirmatives acaben en punt."},
      {"q": "Quin signe usem per a fer una pregunta?", "o": ["L'interrogant (?)", "La coma (,)", "L'admiració (!)"], "e": "L'interrogant marca les preguntes."}
    ]
  }
]$data$::jsonb) AS t(id uuid, "offset" smallint, exercises jsonb);

DELETE FROM public.practice_exercises e
USING practice_more m
WHERE e.resource_id = m.id AND e.level = 'A2' AND e.position > m."offset";

INSERT INTO public.practice_exercises (resource_id, level, position, kind, prompt, options, answers, explanation)
SELECT m.id, 'A2', m."offset" + x.ord,
       CASE WHEN x.e ? 'a' THEN 'fill' ELSE 'choice' END,
       x.e->>'q',
       CASE WHEN x.e ? 'o' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'o')) END,
       CASE WHEN x.e ? 'a' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'a')) ELSE ARRAY[x.e->'o'->>0] END,
       x.e->>'e'
FROM practice_more m
CROSS JOIN LATERAL jsonb_array_elements(m.exercises) WITH ORDINALITY AS x(e, ord);

DROP TABLE practice_more;
