-- Morfosintaxi del B1 (Quadern B1 de la JQCV, 3.2.2). Setze continguts de la
-- categoria morfosintaxi: gènere i nombre del substantiu; l'adjectiu; articles,
-- demostratius i possessius; pronoms forts i febles; pronoms febles CD/CI i
-- combinacions; interrogatius; numerals; quantitatius i indefinits;
-- preposicions; adverbis; connectors; verbs regulars; verbs irregulars; verbs
-- de règim preposicional; modes verbals; i ser/estar, semblar i perífrasis.
-- Són recursos de nivell intermedi amb exercicis B1. Tornar a aplicar el
-- fitxer no duplica res.

CREATE TEMP TABLE practice_catalog AS
SELECT * FROM jsonb_to_recordset($data$[
  {
    "id": "d4e6b0ae-2e1f-4d5b-ad27-be9d86b4e19e", "type": "b1_mor_substantius", "sort_order": 1,
    "title": "Gènere i nombre del substantiu", "name": "Flexió regular, irregular i invariable del substantiu",
    "content": "El gènere del substantiu (regular amb alteració d'accent, irregular i invariable) i el nombre (amb modificació consonàntica, amb canvi d'accent i altres alteracions) (3.2.2).", "icon": "🔤", "color": "#C5E1A5",
    "exercises": [
      {"q": "Quin és el femení de «secretari»?", "o": ["secretària", "secretaria", "secretàrie"], "e": "Secretari → secretària: en femení la paraula es fa esdrúixola i porta accent. La secretaria (sense accent) és l'oficina."},
      {"q": "Quin és el femení de «funcionari»?", "o": ["funcionària", "funcionaria", "funcionàrie"], "e": "Funcionari → funcionària."},
      {"q": "Quin és el femení de «veterinari»?", "o": ["veterinària", "veterinaria", "veterinàrie"], "e": "Veterinari → veterinària."},
      {"q": "Quin és el femení de «cosí»?", "o": ["cosina", "cosína", "cosíssa"], "e": "Cosí → cosina: en femení perd l'accent, perquè passa a ser plana acabada en vocal."},
      {"q": "Quin és el femení de «veí»?", "o": ["veïna", "veína", "veina"], "e": "Veí → veïna: el femení necessita dièresi."},
      {"q": "Quin és el femení de «campió»?", "o": ["campiona", "campióna", "campioa"], "e": "Campió → campiona."},
      {"q": "Quin és el femení de «cavall»?", "o": ["egua", "cavalla", "cavalleta"], "e": "Femení irregular: cavall / egua (o euga)."},
      {"q": "Quin és el femení de «bou»?", "o": ["vaca", "bova", "boua"], "e": "Bou / vaca: paraules diferents."},
      {"q": "Quin és el femení de «gall»?", "o": ["gallina", "galla", "gallessa"], "e": "Gall / gallina."},
      {"q": "Quin és el femení de «actor»?", "o": ["actriu", "actora", "actriz"], "e": "Actor / actriu (com emperador / emperadriu)."},
      {"q": "Quin és el femení de «metge»?", "o": ["metgessa", "metja", "metgesa"], "e": "Metge / metgessa."},
      {"q": "Quin és el femení de «poeta»?", "o": ["poetessa", "poeta", "poetisa"], "e": "Poeta / poetessa."},
      {"q": "Quin és el femení de «gendre»?", "o": ["nora", "gendra", "gendressa"], "e": "Gendre / nora."},
      {"q": "Quin és el femení de «cantaire»?", "o": ["cantaire (és invariable)", "cantairessa", "cantaira"], "e": "Les paraules en -aire són invariables: el cantaire, la cantaire."},
      {"q": "Quin és el femení de «homicida»?", "o": ["homicida (és invariable)", "homicidessa", "homicidera"], "e": "Homicida, suïcida, artista, periodista: invariables en gènere."},
      {"q": "Quin és el femení de «testimoni» (persona que declara)?", "o": ["testimoni (invariable)", "testimònia", "testimona"], "e": "El testimoni, la testimoni."},
      {"q": "Quin és el femení de «jutge»?", "o": ["jutgessa", "jutja", "jutgesa"], "e": "Jutge / jutgessa."},
      {"q": "Quin és el plural de «llengua»?", "o": ["llengües", "llengues", "llenguas"], "e": "Gu + a → gü + e: llengües. La u continua sonant."},
      {"q": "Quin és el plural de «aigua»?", "o": ["aigües", "aigues", "aiguas"], "e": "Aigua → aigües."},
      {"q": "Quin és el plural de «Pasqua»?", "o": ["Pasqües", "Pasques", "Pasquas"], "e": "Qu + a → qü + e: Pasqües."},
      {"q": "Quin és el plural de «amiga»?", "o": ["amigues", "amiges", "amigas"], "e": "G + a → gu + e: amigues."},
      {"q": "Quin és el plural de «platja»?", "o": ["platges", "platjes", "platjas"], "e": "Tj + a → tg + e: platges."},
      {"q": "Quin és el plural de «plaça»?", "o": ["places", "plaçes", "plasses"], "e": "Ç + a → c + e: places."},
      {"q": "Quin és el plural de «camió»?", "o": ["camions", "camións", "camiós"], "e": "Camió → camions: l'aguda acabada en -ons no porta accent."},
      {"q": "Quin és el plural de «examen»?", "o": ["exàmens", "examens", "exámens"], "e": "Examen → exàmens: el plural plana acabada en -ens porta accent."},
      {"q": "Quin és el plural de «país»?", "o": ["països", "paísos", "paisos"], "e": "País → països: dièresi en lloc d'accent."},
      {"q": "Quin és el plural de «mà»?", "o": ["mans", "màs", "manes"], "e": "Mà → mans: recupera la n (també pa → pans, germà → germans)."},
      {"q": "Quin és el plural de «pa»?", "o": ["pans", "pas", "pàs"], "e": "Pa → pans."},
      {"q": "Quin és el plural de «pis»?", "o": ["pisos", "pises", "pissos"], "e": "Pis → pisos (s sonora: s)."},
      {"q": "Quin és el plural de «peix»?", "o": ["peixos", "peixs", "peixes"], "e": "Paraules acabades en -x: plural en -os (peixos, calaixos)."},
      {"q": "Quin és el plural de «despatx»?", "o": ["despatxos", "despatxs", "despatxes"], "e": "Despatx → despatxos."},
      {"q": "Quin és el plural de «text»?", "o": ["textos", "textes", "textus"], "e": "Paraules en -st, -sc, -xt: textos (també boscos, gustos)."},
      {"q": "Quin és el plural de «bosc» més habitual en valencià?", "o": ["boscos", "bosques", "bosquis"], "e": "Boscos (també boscs)."},
      {"q": "Quin és el plural de «dilluns»?", "o": ["dilluns (invariable)", "dillunsos", "dillunes"], "e": "Les paraules planes acabades en -s són invariables: el dilluns, els dilluns; el llapis, els llapis."},
      {"q": "Quin és el plural de «llapis»?", "o": ["llapis", "llapissos", "llapises"], "e": "Invariable: els llapis."},
      {"q": "Quin és el plural de «braç»?", "o": ["braços", "braçs", "braces"], "e": "Braç → braços."},
      {"q": "Escriu el femení de «propietari».", "a": ["propietària"], "e": "Propietària."},
      {"q": "Escriu el plural de «llengua».", "a": ["llengües"], "e": "Llengües."},
      {"q": "Escriu el plural de «germà».", "a": ["germans"], "e": "Germans."},
      {"q": "Escriu el femení de «rei».", "a": ["reina"], "e": "Reina."}
    ]
  },
  {
    "id": "23d2f0c0-a9b0-4df0-85a4-a501b4525e1c", "type": "b1_mor_adjectius", "sort_order": 2,
    "title": "L'adjectiu", "name": "Flexió, adjectius qualificatius, concordança i graus",
    "content": "La flexió dels adjectius d'una i de dos terminacions, els adjectius qualificatius (físic, caràcter, estats d'ànim; gruixut i gros), la concordança i els graus de l'adjectiu (3.2.2).", "icon": "🎨", "color": "#FFE082",
    "exercises": [
      {"q": "Quin és el femení de «bo»?", "o": ["bona", "boa", "bonna"], "e": "Bo / bona / bons / bones."},
      {"q": "Quin és el femení de «nou»?", "o": ["nova", "noua", "nouva"], "e": "Nou / nova / nous / noves."},
      {"q": "Quin és el femení de «blanc»?", "o": ["blanca", "blanqua", "blanga"], "e": "Blanc / blanca / blancs / blanques."},
      {"q": "Quin és el femení plural de «blanc»?", "o": ["blanques", "blances", "blancas"], "e": "C + e → qu: blanques."},
      {"q": "Quin és el femení de «roig»?", "o": ["roja", "rotja", "roija"], "e": "Roig / roja / rojos (o roigs) / roges."},
      {"q": "Quin és el femení de «gros»?", "o": ["grossa", "grosa", "grosça"], "e": "Gros / grossa / grossos / grosses."},
      {"q": "Quin és el femení de «cru»?", "o": ["crua", "cruda", "cruïa"], "e": "Cru / crua / crus / crues."},
      {"q": "En valencià, quin és el femení de «ample»?", "o": ["ampla", "ample (invariable)", "amplia"], "e": "Ample / ampla. També pobre / pobra en valencià."},
      {"q": "Quin d'estos adjectius té una sola terminació (igual en masculí i femení)?", "o": ["jove", "bo", "nou"], "e": "Jove, alegre, gran, fàcil, agradable, breu: una terminació (el xic jove, la xica jove)."},
      {"q": "Quin és el femení de «fàcil»?", "o": ["fàcil", "fàcila", "facila"], "e": "Fàcil: una sola terminació. Plural: fàcils."},
      {"q": "Quin és el plural de «comú»?", "o": ["comuns", "comús", "comúns"], "e": "Comú → comuns (recupera la n)."},
      {"q": "«Este llibre és molt ___: té mil pàgines.»", "o": ["gruixut", "gros", "ample"], "e": "Gruixut: de molt de gruix (un llibre, una paret, una tela). Gros: de gran volum o mida."},
      {"q": "«Han plantat un arbre molt ___ al parc: fa cinc metres.»", "o": ["gros", "gruixut", "prim"], "e": "Gros: gran. Un tronc pot ser gruixut, però l'arbre és gros."},
      {"q": "«La paret és ___: no se sent res del pis del costat.»", "o": ["gruixuda", "grossa", "gruixa"], "e": "Gruixut / gruixuda: amb molt de gruix."},
      {"q": "Quina frase té la concordança correcta?", "o": ["Les cadires i els sofàs nous", "Les cadires i els sofàs noves", "La cadires i el sofàs nous"], "e": "Amb noms de gènere diferent, l'adjectiu va en masculí plural."},
      {"q": "Quina frase té la concordança correcta?", "o": ["una camisa i una falda blanques", "una camisa i una falda blancs", "una camisa i una falda blanca"], "e": "Dos noms femenins: adjectiu en femení plural."},
      {"q": "Quina frase té la concordança correcta?", "o": ["Els xiquets estaven cansats i la mare, preocupada.", "Els xiquets estaven cansat i la mare, preocupats.", "Els xiquets estaven cansada i la mare, preocupat."], "e": "Cada adjectiu concorda amb el seu nom."},
      {"q": "Quin és el superlatiu de «bo»?", "o": ["boníssim", "bonissim", "bonísim"], "e": "Bo → boníssim: sufix -íssim (sempre amb accent)."},
      {"q": "Quin és el superlatiu de «fàcil»?", "o": ["facilíssim", "fàcilíssim", "facilissim"], "e": "Fàcil → facilíssim: l'accent passa al sufix."},
      {"q": "Quin és el superlatiu de «ric»?", "o": ["riquíssim", "ricíssim", "riquisim"], "e": "Ric → riquíssim: c + i → qu."},
      {"q": "Quin és el superlatiu de «llarg»?", "o": ["llarguíssim", "llargíssim", "llargissim"], "e": "Llarg → llarguíssim: g + i → gu."},
      {"q": "Quin és el superlatiu de «amable»?", "o": ["amabilíssim", "amablíssim", "amableíssim"], "e": "Amable → amabilíssim."},
      {"q": "Quina forma intensiva (diminutiva) és correcta per a «calent»?", "o": ["calentet", "calentit", "calentó"], "e": "Sufix -et: calentet, xicotet, bonet... dona un matís afectuós o intensiu."},
      {"q": "Quin és el comparatiu de superioritat de «bo»?", "o": ["millor", "més bo", "mejor"], "e": "Bo → millor (també es diu «més bo» en el sentit de bondat)."},
      {"q": "Quin és el comparatiu de superioritat de «dolent» (o «roín»)?", "o": ["pitjor", "més roín", "peor"], "e": "Dolent / roín → pitjor."},
      {"q": "«És ___ restaurant de la ciutat.» (superlatiu relatiu de bo)", "o": ["el millor", "el més millor", "molt millor"], "e": "El millor, el pitjor: superlatiu relatiu. «Més millor» és incorrecte."},
      {"q": "«Esta pel·lícula és ___ que l'altra.»", "o": ["pitjor", "més pitjor", "pitjora"], "e": "Pitjor ja és comparatiu: mai «més pitjor»."},
      {"q": "Quin adjectiu és un avaluatiu negatiu?", "o": ["roín", "bo", "excel·lent"], "e": "Avaluatius: bo, regular, roín (o dolent), excel·lent..."},
      {"q": "«Com ha anat l'examen?» «___: ni bé ni mal.»", "o": ["Regular", "Boníssim", "Pitjor"], "e": "Regular: mitjà, normal."},
      {"q": "Quin adjectiu descriu un estat d'ànim?", "o": ["preocupat", "alt", "rodó"], "e": "Preocupat, content, trist, nerviós: estats d'ànim (sovint amb estar)."},
      {"q": "Quin adjectiu descriu el caràcter?", "o": ["generós", "calb", "quadrat"], "e": "Generós, simpàtic, tossut: caràcter (sovint amb ser)."},
      {"q": "Quina és correcta?", "o": ["És una xica molt alegre.", "És una xica molt alegra.", "És una xica molt alegres."], "e": "Alegre: una terminació."},
      {"q": "Escriu el femení de «gros».", "a": ["grossa"], "e": "Grossa."},
      {"q": "Escriu el superlatiu en -íssim de «car».", "a": ["caríssim"], "e": "Caríssim."},
      {"q": "Escriu el comparatiu de superioritat de «bo».", "a": ["millor"], "e": "Millor."},
      {"q": "Escriu el femení plural de «blanc».", "a": ["blanques"], "e": "Blanques."}
    ]
  },
  {
    "id": "465bca6e-cc83-4911-bf60-805f4fe6fe12", "type": "b1_mor_determinants", "sort_order": 3,
    "title": "Articles, demostratius i possessius", "name": "Article, contracció, demostratius simples i reforçats i possessius",
    "content": "Les formes de l'article definit i indefinit, la contracció i l'apostrofació, els demostratius simples i reforçats, i els possessius tònics i àtons (3.2.2).", "icon": "👉", "color": "#B3E5FC",
    "exercises": [
      {"q": "Quin és l'article correcte? «___ home»", "o": ["l'", "el", "lo"], "e": "Davant de vocal o h: l'home."},
      {"q": "Quin és l'article correcte? «___ amiga»", "o": ["l'", "la", "un'"], "e": "L'amiga: la s'apostrofa davant de a."},
      {"q": "Quin és l'article correcte? «___ infermera»", "o": ["la", "l'", "le"], "e": "La infermera: no s'apostrofa davant de i àtona. Però l'infermer (masculí sí)."},
      {"q": "Quin és l'article correcte? «___ infermer»", "o": ["l'", "el", "la"], "e": "El s'apostrofa davant de qualsevol vocal: l'infermer."},
      {"q": "Quin és l'article correcte? «___ era» (lloc per a batre el blat)", "o": ["l'", "la", "el"], "e": "L'era."},
      {"q": "«Anem ___ mercat.»", "o": ["al", "a el", "a'l"], "e": "A + el = al."},
      {"q": "«Venim ___ mercat.»", "o": ["del", "de el", "d'el"], "e": "De + el = del."},
      {"q": "«Hem quedat ___ estadi.»", "o": ["a l'", "al", "a el"], "e": "A + l'estadi: amb article apostrofat no hi ha contracció."},
      {"q": "Quin és el plural de l'article indefinit «una»?", "o": ["unes", "unas", "uns"], "e": "Un, una, uns, unes."},
      {"q": "Quina frase evita el castellanisme de l'article neutre «lo»?", "o": ["El més important és la salut.", "Lo més important és la salut.", "Lo important és la salut."], "e": "En valencià no s'usa «lo» neutre: el més important, allò important."},
      {"q": "Quina és la forma simple del demostratiu de proximitat (prop de qui parla)?", "o": ["este", "eixe", "aquell"], "e": "Este/esta/estos/estes (reforçat: aquest/aquesta/aquests/aquestes)."},
      {"q": "Quina és la forma reforçada equivalent a «este producte»?", "o": ["aquest producte", "aqueix producte", "aquell producte"], "e": "Este = aquest. Eixe = aqueix."},
      {"q": "Quina és la forma reforçada equivalent a «eixe gos»?", "o": ["aqueix gos", "aquest gos", "aquell gos"], "e": "Eixe/eixa/eixos/eixes = aqueix/aqueixa/aqueixos/aqueixes."},
      {"q": "Quin demostratiu indica una cosa prop de la persona que escolta?", "o": ["eixe", "este", "aquell"], "e": "Este: prop de qui parla. Eixe: prop de qui escolta. Aquell: lluny dels dos."},
      {"q": "«___ muntanyes que es veuen al fons són molt altes.»", "o": ["Aquelles", "Estes", "Eixes"], "e": "Aquell/aquella/aquells/aquelles: lluny."},
      {"q": "Quin és el plural de «esta»?", "o": ["estes", "estas", "estos"], "e": "Esta → estes."},
      {"q": "Quin és el plural de «eixe»?", "o": ["eixos", "eixes", "eixs"], "e": "Eixe → eixos; eixa → eixes."},
      {"q": "Quin demostratiu neutre s'usa per a una cosa propera a qui parla?", "o": ["açò", "això", "allò"], "e": "Açò (prop), això (mitjana distància), allò (lluny)."},
      {"q": "«És ___ cotxe?» (possessiu, primera persona)", "o": ["el meu", "el mi", "meu el"], "e": "Possessius tònics: el meu, la meua, els meus, les meues."},
      {"q": "«Estes claus són ___.» (possessiu, primera persona)", "o": ["meues", "mies", "meus"], "e": "Les claus → meues (femení plural)."},
      {"q": "«He vist ___ germana al mercat.» (possessiu de tu)", "o": ["la teua", "la tua", "la tenia"], "e": "El teu, la teua, els teus, les teues."},
      {"q": "Quin és el possessiu de «nosaltres» en femení plural?", "o": ["les nostres", "les nostes", "les nostrues"], "e": "El nostre, la nostra, els nostres, les nostres."},
      {"q": "Quin és el possessiu de «ells» per a «casa»?", "o": ["la seua casa", "la sua casa", "la llur casa"], "e": "El seu, la seua, els seus, les seues (de vosté, d'ell, d'ells...)."},
      {"q": "Quina forma àtona del possessiu s'usa habitualment amb noms de família?", "o": ["ma mare", "la ma mare", "mi mare"], "e": "Àtons amb parentiu: ma mare, mon pare, ta germana, son iaio. També «la meua mare»."},
      {"q": "Quina és l'expressió amb possessiu àton correcta?", "o": ["son iaio", "sa iaio", "son iaia"], "e": "Son (masculí): son iaio, son pare. Sa (femení): sa mare, sa iaia."},
      {"q": "Quina és l'expressió amb possessiu àton correcta?", "o": ["ta germana", "ton germana", "tu germana"], "e": "Ta (femení de ton): ta germana, ta tia."},
      {"q": "Quina expressió fixa usa el possessiu àton?", "o": ["en ma vida", "en mia vida", "en mi vida"], "e": "Algunes expressions fixes: en ma vida, a sa casa."},
      {"q": "Quin és el plural de «mon cosí»?", "o": ["mos cosins", "mons cosins", "mes cosins"], "e": "Mon/ma → mos/mes: mos cosins, mes cosines."},
      {"q": "Escriu la contracció de «de + els».", "a": ["dels"], "e": "Dels."},
      {"q": "Escriu la forma reforçada de «esta».", "a": ["aquesta"], "e": "Aquesta."},
      {"q": "Escriu el possessiu tònic femení plural de primera persona: les ___.", "a": ["meues"], "e": "Les meues."},
      {"q": "Escriu el possessiu àton femení de tercera persona davant de «mare»: ___ mare.", "a": ["sa"], "e": "Sa mare."}
    ]
  },
  {
    "id": "5916a0f9-90af-4c02-bab8-768bc0bc7004", "type": "b1_mor_pronoms_personals", "sort_order": 4,
    "title": "Pronoms forts i febles", "name": "Pronoms personals forts i morfologia i col·locació dels febles",
    "content": "Concepte de pronom fort i feble, morfologia dels pronoms forts i de la col·locació dels febles (davant i darrere del verb, amb apòstrof i guionet) (3.2.2).", "icon": "🙋", "color": "#F8BBD0",
    "exercises": [
      {"q": "Quin d'estos és un pronom fort?", "o": ["nosaltres", "ens", "els"], "e": "Forts: jo, tu, ell, ella, vosté, nosaltres, vosaltres, vostés, ells, elles. Febles: em, et, el, ens, us..."},
      {"q": "Quin d'estos és un pronom feble?", "o": ["li", "ella", "vosté"], "e": "Li és feble: va unit al verb."},
      {"q": "Quin pronom fort s'usa darrere d'una preposició per a la primera persona?", "o": ["mi: «per a mi»", "jo: «per a jo»", "me: «per a me»"], "e": "Darrere de preposició, mi: per a mi, amb mi, a mi."},
      {"q": "Quina és correcta?", "o": ["Vine amb mi.", "Vine amb jo.", "Vine amb me."], "e": "Amb mi."},
      {"q": "Quina és correcta?", "o": ["Entre tu i jo ho farem.", "Entre tu i mi ho farem.", "Entre te i jo ho farem."], "e": "Entre tu i jo (o entre tu i mi)."},
      {"q": "Quin és el pronom fort de respecte per a parlar a una persona gran que no coneixes?", "o": ["vosté", "tu", "vós sempre"], "e": "Vosté (plural vostés), amb el verb en tercera persona."},
      {"q": "Quin és el femení de «ells»?", "o": ["elles", "elas", "ellas"], "e": "Ell, ella, ells, elles."},
      {"q": "«___ compre el pa cada dia.» (el pa = CD, davant del verb)", "o": ["El", "Lo", "L'"], "e": "Davant de verb que comença per consonant: el. Davant de vocal: l' (l'agafe)."},
      {"q": "«___ agafe cada matí.» (el tren)", "o": ["L'", "El", "Lo"], "e": "El → l' davant de vocal."},
      {"q": "«Vull comprar___.» (el pa, darrere de l'infinitiu)", "o": ["-lo", "'l", "-el"], "e": "Darrere de verb acabat en consonant: comprar-lo."},
      {"q": "«Vaig a vendre___.» (el cotxe)", "o": ["'l", "-lo", "-el"], "e": "Darrere de verb acabat en vocal: vendre'l."},
      {"q": "«Compra___!» (el pa, imperatiu)", "o": ["'l", "-lo", "-el"], "e": "Compra'l (acaba en vocal)."},
      {"q": "«Està mirant___.» (la tele, gerundi)", "o": ["-la", "'la", "-lo"], "e": "La darrere del verb sempre amb guionet: mirant-la."},
      {"q": "«___ estime molt.» (a tu)", "o": ["T'", "Et", "Te"], "e": "Et → t' davant de vocal."},
      {"q": "«___ veig demà.» (a tu)", "o": ["Et", "T'", "Te"], "e": "Davant de consonant, forma reforçada: et veig."},
      {"q": "«Ajuda___, per favor!» (a mi)", "o": ["'m", "-me", "-em"], "e": "Darrere de verb acabat en vocal: ajuda'm."},
      {"q": "«Vols ajudar___?» (a mi)", "o": ["-me", "'m", "-em"], "e": "Darrere de verb acabat en consonant: ajudar-me."},
      {"q": "«___ agrada la música.» (a nosaltres)", "o": ["Ens", "'Ns", "Mos"], "e": "Ens: davant del verb no s'apostrofa. «Mos» és col·loquial: en estàndard, ens."},
      {"q": "«Mira___!» (a nosaltres)", "o": ["'ns", "-nos", "-ens"], "e": "Darrere de verb acabat en vocal: mira'ns."},
      {"q": "«Vull veure___.» (a vosaltres)", "o": ["-vos", "'vos", "vos-"], "e": "Darrere del verb, en valencià: -vos (també -us): veure-vos, ajudar-vos."},
      {"q": "«___ espere a la porta.» (a vosaltres)", "o": ["Us", "Vos", "Os"], "e": "Davant del verb: us espere (en valencià col·loquial, també vos)."},
      {"q": "«___ he dit la veritat.» (a ell)", "o": ["Li", "L'", "El"], "e": "Li és el pronom de complement indirecte singular; no s'apostrofa mai."},
      {"q": "«Pregunta___ on viu.» (a ell)", "o": ["-li", "'li", "-lo"], "e": "Darrere del verb: pregunta-li."},
      {"q": "«Vaig a fer___.» (això)", "o": ["-ho", "'ho", "-lo"], "e": "Ho (neutre) sempre amb guionet darrere del verb: fer-ho."},
      {"q": "«___ cal anar demà.» (a la platja, complement de lloc)", "o": ["Hi", "I", "Ni"], "e": "Hi substituïx complements de lloc: hi cal anar, hi vaig."},
      {"q": "«Tens pa? Sí, ___ tinc.»", "o": ["en", "el", "hi"], "e": "En substituïx un complement indeterminat (pa, sense article)."},
      {"q": "«Quantes pomes vols? ___ vull tres.»", "o": ["En", "Les", "Hi"], "e": "Amb quantitats: en vull tres."},
      {"q": "Quina posició del pronom és correcta?", "o": ["El vull comprar. / Vull comprar-lo.", "Vull el comprar.", "Comprar vull-lo."], "e": "Amb perífrasis, el pronom pot anar davant del verb conjugat o darrere de l'infinitiu."},
      {"q": "Escriu el pronom feble que substituïx «el pa» darrere de «comprar»: comprar-___.", "a": ["lo"], "e": "Comprar-lo."},
      {"q": "Escriu el pronom fort de primera persona darrere de «per a»: per a ___.", "a": ["mi"], "e": "Per a mi."},
      {"q": "Escriu el pronom feble de complement indirecte per a «a ella».", "a": ["li"], "e": "Li."},
      {"q": "Escriu «mira + ens» amb el pronom ben escrit.", "a": ["mira'ns"], "e": "Mira'ns."}
    ]
  },
  {
    "id": "bc2f3489-6ae8-468c-aa0f-4b23695a0a02", "type": "b1_mor_pronoms_cd_ci", "sort_order": 5,
    "title": "Pronoms febles: CD, CI i combinacions", "name": "Complement directe, complement indirecte i combinació de dos pronoms",
    "content": "Ús dels pronoms febles en funció de complement directe i indirecte, i combinació de dos pronoms: complement indirecte + complement directe (3.2.2).", "icon": "🔁", "color": "#E1BEE7",
    "exercises": [
      {"q": "«He comprat el pa.» → «___ he comprat.»", "o": ["L'", "Li", "En"], "e": "El pa és complement directe determinat masculí: el / l'."},
      {"q": "«He comprat la llet.» → «___ he comprada.»", "o": ["L'", "Li", "La"], "e": "La llet: CD femení → l' davant de vocal (l'he comprada)."},
      {"q": "«Compraré les pomes.» → «___ compraré.»", "o": ["Les", "Els", "Li"], "e": "Les pomes: CD femení plural → les."},
      {"q": "«Veig els xiquets.» → «___ veig.»", "o": ["Els", "Les", "Li"], "e": "Els xiquets: CD masculí plural → els."},
      {"q": "«He dit que no.» → «___ he dit.»", "o": ["Ho", "El", "Li"], "e": "Una oració o «això» com a CD → ho."},
      {"q": "«Vull pa.» → «___ vull.»", "o": ["En", "El", "Ho"], "e": "CD sense determinant (indeterminat) → en."},
      {"q": "«He escrit una carta a la meua àvia.» Quin és el complement indirecte?", "o": ["a la meua àvia", "una carta", "he escrit"], "e": "El CI indica a qui va destinada l'acció: a la meua àvia."},
      {"q": "«He escrit una carta a la meua àvia.» → «___ he escrit una carta.»", "o": ["Li", "La", "L'"], "e": "CI singular → li (masculí o femení)."},
      {"q": "«Done els regals als meus fills.» → «___ done els regals.»", "o": ["Els", "Li", "Les"], "e": "CI plural → els (masculí o femení): els done."},
      {"q": "«Done els regals a les meues filles.» → «___ done els regals.»", "o": ["Els", "Les", "Li"], "e": "El CI plural sempre és els, també en femení."},
      {"q": "«Telefona a Pere.» → «Telefona___.»", "o": ["-li", "'l", "-lo"], "e": "Telefonar a algú: CI → telefona-li."},
      {"q": "«Pregunte a vosté.» → «___ pregunte.»", "o": ["Li", "El", "La"], "e": "Vosté com a CI: li (li pregunte)."},
      {"q": "«Em dones el llibre?» → «___ dones?»", "o": ["Me'l", "Em el", "M'el"], "e": "CI (em) + CD (el) → me'l."},
      {"q": "«Et done la clau.» → «___ done.»", "o": ["Te la", "Et la", "T'la"], "e": "Et + la → te la."},
      {"q": "«Et porte els papers.» → «___ porte.»", "o": ["Te'ls", "Et els", "T'els"], "e": "Et + els → te'ls."},
      {"q": "«T'explique això.» → «___ explique.»", "o": ["T'ho", "Te ho", "Et ho"], "e": "Et + ho davant de vocal → t'ho."},
      {"q": "«Ens enviaran el paquet.» → «___ enviaran.»", "o": ["Ens l'", "Ens el", "Nos l'"], "e": "Ens + el davant de vocal → ens l' (ens l'enviaran)."},
      {"q": "«Us diré la veritat.» → «___ diré.»", "o": ["Us la", "Vos la", "Us l'"], "e": "Us + la → us la (davant de consonant)."},
      {"q": "«Li done el llibre.» → «___ done.»", "o": ["Li'l", "El li", "Lo li"], "e": "Li + el → li'l (també l'hi)."},
      {"q": "«Li he dit això.» → «___ he dit.»", "o": ["Li ho", "L'ho", "Ho li"], "e": "Li + ho → li ho."},
      {"q": "«Li porte la carta.» → «___ porte.»", "o": ["Li la", "La li", "Li-la"], "e": "Li + la → li la."},
      {"q": "«Els he portat pa.» → «___ he portat.»", "o": ["Els n'", "Els en", "N'els"], "e": "Els + en → els n' davant de vocal."},
      {"q": "«Dona'm el llibre.» → «Dona___!»", "o": ["-me'l", "'m-el", "-el-me"], "e": "Darrere del verb: dona-me'l."},
      {"q": "«Porta'ns la cadira.» → «Porta___!»", "o": ["-nos-la", "'ns-la", "-la-nos"], "e": "Darrere del verb: porta-nos-la."},
      {"q": "«Explica-li això.» → «Explica___!»", "o": ["-li-ho", "-ho-li", "'l-ho"], "e": "Darrere del verb: explica-li-ho."},
      {"q": "«Vull dir-te una cosa.» → «Vull dir-___.» (una cosa → la)", "o": ["te-la", "la-te", "t'la"], "e": "Darrere de l'infinitiu: dir-te-la. També: te la vull dir."},
      {"q": "«Se'n va a casa.» Quins pronoms hi ha?", "o": ["es + en", "es + el", "se + li"], "e": "Anar-se'n: es + en → se'n (davant de consonant)."},
      {"q": "Quina és correcta?", "o": ["Me'n vaig.", "Em en vaig.", "M'en vaig."], "e": "Em + en → me'n."},
      {"q": "Quina és correcta?", "o": ["No me'n recorde.", "No m'en recorde.", "No em en recorde."], "e": "Recordar-se'n: me'n recorde, te'n recordes, se'n recorda."},
      {"q": "Quina és correcta?", "o": ["A Maria, li agrada el cine.", "A Maria, la agrada el cine.", "A Maria, l'agrada el cine."], "e": "Agradar porta CI: li agrada."},
      {"q": "Quina és correcta?", "o": ["A ells, els fa por la foscor.", "A ells, li fa por la foscor.", "A ells, les fa por la foscor."], "e": "CI plural: els."},
      {"q": "Escriu el pronom: «He vist el teu germà» → «___ he vist.»", "a": ["l'", "l"], "e": "L'he vist."},
      {"q": "Escriu el pronom: «Done un regal a ma mare» → «___ done un regal.»", "a": ["li"], "e": "Li."},
      {"q": "Escriu els dos pronoms: «Em dones la sal?» → «___ dones?»", "a": ["me la"], "e": "Me la dones?"},
      {"q": "Escriu els dos pronoms: «Li done el llibre» → «___ done.»", "a": ["li'l", "l'hi"], "e": "Li'l o l'hi."}
    ]
  },
  {
    "id": "a7c5d2a7-6ba3-43ad-86d2-556ac9a00f68", "type": "b1_mor_interrogatius", "sort_order": 6,
    "title": "Pronoms interrogatius", "name": "Què, qui, quin, a on, com, quan i quant",
    "content": "Els pronoms i adverbis interrogatius (què, qui, quin, a on, com) i la distinció entre quan i quant (3.2.2).", "icon": "❓", "color": "#B2DFDB",
    "exercises": [
      {"q": "«___ vols per a sopar?» (una cosa)", "o": ["Què", "Qui", "Quin"], "e": "Què: per a coses."},
      {"q": "«___ ha telefonat?» (una persona)", "o": ["Qui", "Què", "Quin"], "e": "Qui: per a persones."},
      {"q": "«___ llibre estàs llegint?»", "o": ["Quin", "Què", "Qui"], "e": "Quin + nom masculí: quin llibre."},
      {"q": "«___ pel·lícula vols veure?»", "o": ["Quina", "Quin", "Què"], "e": "Quina + nom femení."},
      {"q": "«___ germans tens?» (quantitat)", "o": ["Quants", "Quins", "Quant"], "e": "Quants + nom masculí plural, per a quantitat."},
      {"q": "«___ germanes tens?» (quantitat)", "o": ["Quantes", "Quantas", "Quants"], "e": "Quantes + nom femení plural."},
      {"q": "«___ costa este jersei?»", "o": ["Quant", "Quan", "Quin"], "e": "Quant: quantitat (preu). Quan: temps."},
      {"q": "«___ arribarà el tren?»", "o": ["Quan", "Quant", "Com"], "e": "Quan: temps. Quant: quantitat."},
      {"q": "«___ fa que vius ací?»", "o": ["Quant de temps", "Quan de temps", "Què temps"], "e": "Quant de temps: duració."},
      {"q": "«___ vas aquest estiu?» (lloc)", "o": ["A on", "Com", "Quan"], "e": "A on (o on): lloc."},
      {"q": "«___ et dius?»", "o": ["Com", "Què", "Qui"], "e": "Com: manera. Com et dius?"},
      {"q": "«___ estàs?» «Molt bé, gràcies.»", "o": ["Com", "Què", "On"], "e": "Com estàs?"},
      {"q": "«___ no has vingut?» «Perquè estava malalt.»", "o": ["Per què", "Perquè", "Perque"], "e": "Per què (separat, amb accent): pregunta per la causa. Perquè: resposta."},
      {"q": "«___ és este abric?» (propietari)", "o": ["De qui", "De què", "Qui de"], "e": "De qui: propietat."},
      {"q": "«___ vas al cine?» (companyia)", "o": ["Amb qui", "Amb què", "Qui amb"], "e": "Amb qui: companyia."},
      {"q": "«___ està fet este moble?» (material)", "o": ["De què", "De qui", "Què de"], "e": "De què: material o tema."},
      {"q": "«___ hora és?»", "o": ["Quina", "Què", "Quant"], "e": "Quina hora és?"},
      {"q": "«___ anys tens?»", "o": ["Quants", "Quins", "Quans"], "e": "Quants anys tens?"},
      {"q": "«___ són els teus pares?» (identificar entre diverses persones)", "o": ["Quins", "Qui", "Què"], "e": "Quins: per a triar entre elements d'un grup."},
      {"q": "«No sé ___ fer.» (interrogativa indirecta)", "o": ["què", "que", "qui"], "e": "En les interrogatives indirectes, què també porta accent."},
      {"q": "«M'ha preguntat ___ arribaré.»", "o": ["quan", "quant", "qui"], "e": "Interrogativa indirecta de temps: quan."},
      {"q": "«___ gent hi havia!» (exclamació)", "o": ["Quanta", "Quanta de", "Quan"], "e": "Quanta gent!, quants xiquets!"},
      {"q": "«___ de pa vols?»", "o": ["Quant", "Quan", "Quanta"], "e": "Quant de + nom no comptable: quant de pa, quant de temps."},
      {"q": "Quina pregunta està ben escrita?", "o": ["Què has dit?", "Que has dit?", "Qué has dit?"], "e": "Què interrogatiu porta accent obert (è)."},
      {"q": "Quina pregunta està ben escrita?", "o": ["On vius?", "On vius", "¿On vius?"], "e": "En valencià el signe d'interrogació només es posa al final."},
      {"q": "Escriu l'interrogatiu: «___ arriba l'avió?» (temps)", "a": ["quan"], "e": "Quan."},
      {"q": "Escriu l'interrogatiu: «___ val este llibre?» (preu)", "a": ["quant"], "e": "Quant."},
      {"q": "Escriu l'interrogatiu: «___ és eixa xica?» (persona)", "a": ["qui"], "e": "Qui."},
      {"q": "Escriu l'interrogatiu de causa (dues paraules).", "a": ["per què"], "e": "Per què."}
    ]
  },
  {
    "id": "969469d6-dee2-4b10-bf2b-26bcd3e65e55", "type": "b1_mor_numerals", "sort_order": 7,
    "title": "Els numerals", "name": "Cardinals i ordinals",
    "content": "L'ús dels numerals cardinals (zero, quatre, cinc, catorze, trenta-dos, cent, tres-cents, mil, un milió) i ordinals (primer, segon, quart, cinqué, sisena, vinté...) (3.2.2).", "icon": "🔢", "color": "#FFCCBC",
    "exercises": [
      {"q": "Com s'escriu 8 en valencià?", "o": ["huit", "vuit", "uit"], "e": "En valencià: huit (també vuit en altres variants)."},
      {"q": "Com s'escriu 14?", "o": ["catorze", "catorce", "quatorze"], "e": "Catorze."},
      {"q": "Com s'escriu 17 en valencià?", "o": ["dèsset", "dicisset", "dieciset"], "e": "Dèsset (o disset)."},
      {"q": "Com s'escriu 18 en valencià?", "o": ["díhuit", "dihuit", "devuit"], "e": "Díhuit (o divuit)."},
      {"q": "Com s'escriu 19 en valencià?", "o": ["dènou", "dènau", "diènou"], "e": "Dènou (o dinou)."},
      {"q": "Com s'escriu 32?", "o": ["trenta-dos", "trentaidos", "trenta i dos"], "e": "Desenes i unitats amb guionet: trenta-dos."},
      {"q": "Com s'escriu 21?", "o": ["vint-i-u (o vint-i-un)", "vintiun", "vint i u"], "e": "Entre vint i les unitats, -i-: vint-i-u, vint-i-dos."},
      {"q": "Com s'escriu 300?", "o": ["tres-cents", "trescents", "tres cents"], "e": "Unitats i centenes amb guionet: tres-cents."},
      {"q": "«Hi havia ___ persones.» (200, femení)", "o": ["dues-centes", "dos-cents", "dues cents"], "e": "Les centenes concorden amb el nom: dues-centes persones."},
      {"q": "«Tinc ___ germanes.» (2)", "o": ["dues", "dos", "dós"], "e": "Dos (masculí) / dues (femení)."},
      {"q": "Com s'escriu 1.000.000?", "o": ["un milió", "un millió", "un milló"], "e": "Un milió, dos milions."},
      {"q": "Com s'escriu 1.500?", "o": ["mil cinc-cents", "un mil cinc-cents", "mil-cinc-cents"], "e": "Mil (sense «un») cinc-cents."},
      {"q": "Com s'escriu 105?", "o": ["cent cinc", "cent-cinc", "cent i cinc"], "e": "Centena i unitat, sense guionet ni «i»: cent cinc."},
      {"q": "Quin és l'ordinal de «quatre» en masculí?", "o": ["quart", "quatré", "quarto"], "e": "Primer, segon, tercer, quart."},
      {"q": "Quin és l'ordinal de «cinc» en masculí?", "o": ["cinqué (o quint)", "cinquè (o quinto)", "cinqueno"], "e": "Cinqué (valencià) o quint."},
      {"q": "Quin és l'ordinal femení de «sis»?", "o": ["sisena (o sexta)", "siséa", "sisea"], "e": "Sisena o sexta."},
      {"q": "Quin és l'ordinal de «vint» en masculí?", "o": ["vinté", "vintè", "vintavo"], "e": "Vinté (femení vintena)."},
      {"q": "Quin és el femení de «tercer»?", "o": ["tercera", "tercer", "terça"], "e": "Tercer / tercera."},
      {"q": "Quin és el plural masculí de «primer»?", "o": ["primers", "primeros", "primés"], "e": "Primer / primers / primera / primeres."},
      {"q": "Quin és el plural femení de «quart»?", "o": ["quartes", "quarts", "quartas"], "e": "Quart / quarta / quarts / quartes."},
      {"q": "«Visc en el ___ pis.» (3r)", "o": ["tercer", "tres", "terç"], "e": "Tercer pis (ordinal)."},
      {"q": "«És la ___ vegada que t'ho dic.» (10a)", "o": ["desena", "deu", "décima"], "e": "Desé / desena."},
      {"q": "«Hem arribat en ___ lloc.» (2n)", "o": ["segon", "dos", "segund"], "e": "Segon lloc."},
      {"q": "Quina és la fracció «1/4»?", "o": ["un quart", "un quarta", "un quatre"], "e": "1/4: un quart. 1/2: mig o la meitat. 1/3: un terç."},
      {"q": "«Me'n dones ___ quilo?» (0,5)", "o": ["mig", "mitat", "mitja"], "e": "Mig quilo; mitja hora (femení)."},
      {"q": "«Arribarem a les set i ___.» (30 minuts)", "o": ["mitja", "mig", "mitat"], "e": "Les set i mitja."},
      {"q": "Quin número és «zero»?", "o": ["0", "10", "100"], "e": "Zero (0)."},
      {"q": "Escriu en lletres el número 32.", "a": ["trenta-dos"], "e": "Trenta-dos."},
      {"q": "Escriu en lletres el número 300.", "a": ["tres-cents"], "e": "Tres-cents."},
      {"q": "Escriu l'ordinal masculí de 5 en valencià.", "a": ["cinqué", "quint", "cinquè"], "e": "Cinqué (o quint)."},
      {"q": "Escriu en lletres el número 8 en valencià.", "a": ["huit", "vuit"], "e": "Huit."}
    ]
  },
  {
    "id": "b6c86018-dd00-47e9-88df-9462393e1e84", "type": "b1_mor_quantitatius_indefinits", "sort_order": 8,
    "title": "Quantitatius i indefinits", "name": "Quant, prou, locucions de quantitat, indefinits i res/gens/cap",
    "content": "Quantitatius variables i invariables, l'ús de quant i prou, les locucions de quantitat més freqüents, els indefinits i la distinció entre res, gens i cap/ningun (3.2.2).", "icon": "⚖️", "color": "#DCEDC8",
    "exercises": [
      {"q": "Quin d'estos quantitatius és invariable?", "o": ["massa", "molt", "poc"], "e": "Massa i prou són invariables. Molt, poc, quant varien: molta, pocs, quantes."},
      {"q": "«Hi havia ___ gent a la festa.»", "o": ["molta", "molt", "molts"], "e": "Molt concorda amb el nom: molta gent."},
      {"q": "«Tens ___ temps per a acabar-ho?» (suficient)", "o": ["prou", "pros", "prou de"], "e": "Prou: suficient (invariable)."},
      {"q": "«Ja n'hi ha ___!» (suficient, prou de parlar)", "o": ["prou", "molt", "massa poc"], "e": "Ja n'hi ha prou!: ja és suficient."},
      {"q": "«Hi ha ___ soroll: no puc dormir.» (excés)", "o": ["massa", "masses", "prou"], "e": "Massa: excés, invariable."},
      {"q": "«___ persones vindran?»", "o": ["Quantes", "Quantas", "Quant"], "e": "Quant/quanta/quants/quantes concorda amb el nom."},
      {"q": "«Hi havia ___ gent al concert.» (molta)", "o": ["bona cosa de", "bona cosa", "una bona"], "e": "Bona cosa de: molt, molta."},
      {"q": "«No té ___ de paciència.» (gens)", "o": ["gens ni mica", "res ni gens", "gens de res"], "e": "Gens ni mica (o gens ni miqueta): absolutament gens."},
      {"q": "«Ha collit ___ d'olives amb la mà.» (poca quantitat)", "o": ["un grapat", "un fum", "un milió"], "e": "Un grapat: el que cap en una mà; una quantitat menuda."},
      {"q": "«Tinc ___ de faena!» (molta)", "o": ["un muntó (o un fum)", "un grapat", "una miqueta"], "e": "Un muntó de, un fum de: molta quantitat."},
      {"q": "«Vull una ___ de sucre en el café.» (molt poc)", "o": ["miqueta", "muntó", "bona cosa"], "e": "Una mica, una miqueta: poca quantitat."},
      {"q": "«He visitat ___ països d'Europa.»", "o": ["diversos", "diverses", "divers"], "e": "Diversos/diverses (variable): diversos països."},
      {"q": "«Pots vindre ___ dia.»", "o": ["qualsevol", "qualsevols", "cualsevol"], "e": "Qualsevol (plural: qualssevol)."},
      {"q": "«___ sap que és el millor.» (totes les persones)", "o": ["Tothom", "Tots sabem", "Tothom saben"], "e": "Tothom va amb el verb en singular: tothom sap."},
      {"q": "Quina és correcta?", "o": ["Tothom ha vingut.", "Tothom han vingut.", "Tot el món han vingut."], "e": "Tothom + singular."},
      {"q": "«Vols ___ cosa?» (algun objecte o algun menjar)", "o": ["alguna", "algun", "algú"], "e": "Alguna cosa (o res, en preguntes: vols res?)."},
      {"q": "«Ha telefonat ___?» (alguna persona)", "o": ["algú", "alguna cosa", "algun"], "e": "Algú: alguna persona. Ningú: cap persona."},
      {"q": "«No vol ___.» (cap cosa)", "o": ["res", "gens", "cap"], "e": "Res: cap cosa. No vol res."},
      {"q": "«No queda ___ de vi.» (quantitat no comptable)", "o": ["gens", "res", "cap"], "e": "Gens (de): quantitat de coses no comptables: no queda gens de vi, de pa, de llet."},
      {"q": "«No tinc ___ ordinador.» (comptable)", "o": ["cap (o ningun)", "gens", "res"], "e": "Cap (o ningun/ninguna) davant de nom comptable."},
      {"q": "«No hi ha ___ cadira lliure.»", "o": ["cap", "gens", "res"], "e": "Cap: davant de nom comptable."},
      {"q": "«No ha vingut ___.» (cap persona)", "o": ["ningú", "res", "gens"], "e": "Ningú: cap persona."},
      {"q": "«No m'agrada ___ el futbol.»", "o": ["gens", "res", "cap"], "e": "Gens: en absolut, amb verbs (no m'agrada gens)."},
      {"q": "«Hi ha ___ maneres de fer-ho.» (variades)", "o": ["diferents", "diferent", "diferenta"], "e": "Diferents: diverses."},
      {"q": "«No he vist mai una cosa ___.»", "o": ["tal", "tala", "tals"], "e": "Tal: semblant, d'eixa mena."},
      {"q": "«___ dia vaig al gimnàs.»", "o": ["Cada", "Cades", "Cadascú"], "e": "Cada (invariable). Cadascú: cada persona."},
      {"q": "«Vull ___ cafè, per favor.» (un més)", "o": ["un altre", "otro", "altre un"], "e": "Un altre, una altra, uns altres, unes altres."},
      {"q": "Escriu la paraula: «No queda ___ de llet.»", "a": ["gens"], "e": "Gens."},
      {"q": "Escriu la paraula: «No hi ha ___ taxi lliure.»", "a": ["cap", "ningun"], "e": "Cap (o ningun)."},
      {"q": "Escriu la paraula: «No he menjat ___ en tot el dia.»", "a": ["res"], "e": "Res."},
      {"q": "Escriu el quantitatiu: «Ja n'hi ha ___!» (suficient)", "a": ["prou"], "e": "Prou."}
    ]
  },
  {
    "id": "98325cd9-231e-4aae-80f2-1001b92259d8", "type": "b1_mor_preposicions", "sort_order": 9,
    "title": "Les preposicions", "name": "Preposicions i locucions de mitjà, tema, causa i relació; a amb topònims; a davant del CD",
    "content": "Preposicions i locucions prepositives de mitjà o instrument, de tema, de causa i de relació; la preposició a davant de topònims, classe i casa; i els usos impropis de la preposició a davant del complement directe (3.2.2).", "icon": "➡️", "color": "#CFD8DC",
    "exercises": [
      {"q": "«Hem anat ___ peu fins a la platja.»", "o": ["a", "en", "amb"], "e": "A peu (també a cavall, a mà)."},
      {"q": "«Escriu-ho ___ el bolígraf blau.»", "o": ["amb", "a", "de"], "e": "Amb: instrument."},
      {"q": "«He conegut el meu xicot ___ internet.»", "o": ["a través d'", "per a", "sobre"], "e": "A través de / per mitjà de: mitjà."},
      {"q": "«Vam viatjar ___ tren fins a Madrid.»", "o": ["en (o amb)", "a", "de"], "e": "En tren o amb tren."},
      {"q": "«Hem parlat ___ les vacances.»", "o": ["de (o sobre)", "a", "per a"], "e": "De / sobre: tema."},
      {"q": "«He llegit un llibre ___ la història de València.»", "o": ["sobre", "per", "a"], "e": "Sobre: tema."},
      {"q": "«S'ha suspés el partit ___ la pluja.»", "o": ["a causa de", "gràcies a", "en lloc de"], "e": "A causa de / per culpa de: causa (negativa)."},
      {"q": "«He aprovat ___ la teua ajuda.»", "o": ["gràcies a", "per culpa de", "a causa"], "e": "Gràcies a: causa positiva."},
      {"q": "«Hem arribat tard ___ l'embús.»", "o": ["per culpa de", "gràcies a", "en comptes de"], "e": "Per culpa de: causa negativa, amb valor de retret."},
      {"q": "«___ les festes, l'ajuntament ha posat més autobusos.»", "o": ["Amb motiu de", "En lloc de", "A través de"], "e": "Amb motiu de: amb ocasió de."},
      {"q": "«___ l'accident, han posat un semàfor.»", "o": ["Arran de", "En lloc de", "Sobre"], "e": "Arran de: com a conseqüència de."},
      {"q": "«___ anar en cotxe, anirem amb bicicleta.»", "o": ["En lloc d'", "A causa d'", "Gràcies a"], "e": "En lloc de / en comptes de: substitució."},
      {"q": "«He canviat la camisa ___ una de més gran.»", "o": ["per", "per a", "a"], "e": "Per: canvi, intercanvi."},
      {"q": "«Este regal és ___ tu.» (destinatari)", "o": ["per a", "per", "a"], "e": "Per a: destinació o finalitat."},
      {"q": "«Estudie ___ aprovar.» (finalitat)", "o": ["per a", "per", "a"], "e": "Per a + infinitiu: finalitat."},
      {"q": "«Ho he fet ___ tu: perquè t'estime.» (causa)", "o": ["per", "per a", "a"], "e": "Per: causa."},
      {"q": "«Visc ___ València.»", "o": ["a", "en", "de"], "e": "Davant de topònims: a València, a Alacant."},
      {"q": "«Aquest estiu anirem ___ Itàlia.»", "o": ["a", "en", "cap"], "e": "A Itàlia."},
      {"q": "«Ara estic ___ casa.»", "o": ["a", "en", "dins"], "e": "A casa, a classe, a l'escola."},
      {"q": "«Els alumnes estan ___ classe.»", "o": ["a", "en", "de"], "e": "A classe."},
      {"q": "Quina és correcta?", "o": ["Han vist el mestre.", "Han vist al mestre.", "Han vist a el mestre."], "e": "El complement directe de persona no porta a: he vist el mestre."},
      {"q": "Quina és correcta?", "o": ["Conec Marta des de fa anys.", "Conec a Marta des de fa anys.", "Conec de Marta des de fa anys."], "e": "Sense a davant del CD: conec Marta."},
      {"q": "Quina és correcta?", "o": ["Estime molt els meus pares.", "Estime molt als meus pares.", "Estime molt a els meus pares."], "e": "Estimar algú: CD sense preposició."},
      {"q": "Quina és correcta?", "o": ["Crida a tots.", "Crida tots a.", "Crida de tots."], "e": "Davant de «tots», «tothom», els pronoms forts (a mi, a tu) i en alguns casos per a evitar ambigüitat, el CD pot portar a."},
      {"q": "Quina és correcta?", "o": ["T'he vist a tu.", "He vist tu.", "T'he vist tu a."], "e": "Amb pronom fort de persona, a: t'he vist a tu."},
      {"q": "Quina és correcta?", "o": ["Esperem l'autobús.", "Esperem a l'autobús.", "Esperem per l'autobús."], "e": "Esperar algú/alguna cosa: CD sense a."},
      {"q": "«Vaig ___ el metge.»", "o": ["al", "a el", "el"], "e": "Anar a + el = al metge."},
      {"q": "«Tinc moltes ganes ___ veure't.»", "o": ["de", "a", "per"], "e": "Tindre ganes de."},
      {"q": "Escriu la preposició: «Visc ___ Alacant.»", "a": ["a"], "e": "A Alacant."},
      {"q": "Escriu la preposició: «Este paquet és ___ ta mare.» (destinatari)", "a": ["per a"], "e": "Per a."},
      {"q": "Escriu la locució: «Hem arribat a temps ___ a tu.» (causa positiva)", "a": ["gràcies"], "e": "Gràcies a."},
      {"q": "Corregix la frase: «He vist a ta germana.»", "a": ["he vist ta germana", "he vist la teua germana"], "e": "He vist ta germana (sense a)."}
    ]
  },
  {
    "id": "2b9aa93e-9bff-4dfd-bf80-5de1719a88d5", "type": "b1_mor_adverbis", "sort_order": 10,
    "title": "Els adverbis", "name": "Afirmació i negació, adverbis en -ment i comparatius",
    "content": "Adverbis i locucions d'afirmació i de negació, la formació dels adverbis en -ment i els comparatius més/menys que, tant/tan com (3.2.2).", "icon": "↔️", "color": "#FFE0B2",
    "exercises": [
      {"q": "«Vindràs a la festa?» «___! No me la perdria per res.»", "o": ["I tant", "De cap manera", "Tampoc"], "e": "I tant!: afirmació enfàtica."},
      {"q": "«Ho has fet tu?» «___, ho he fet jo.»", "o": ["Sí, de veres", "De cap manera", "Gens"], "e": "De veres (o de veritat): afirmació."},
      {"q": "En valencià col·loquial, «prou» pot voler dir...", "o": ["«sí, és clar» en una resposta", "«massa»", "«mai»"], "e": "«Vindràs?» «Prou!»: afirmació. També vol dir «suficient»."},
      {"q": "«És ___ el millor jugador de l'equip.» (no hi ha cap dubte)", "o": ["sens dubte", "potser", "de cap manera"], "e": "Sens dubte: afirmació segura."},
      {"q": "«Deixaràs que ho faça sol?» «___!»", "o": ["De cap manera", "I tant", "De veres"], "e": "De cap manera (o de ninguna manera): negació rotunda."},
      {"q": "«Jo no hi vaig.» «Jo ___.»", "o": ["tampoc", "també", "sí"], "e": "Tampoc: negació en coordinació amb una altra negació. També: afirmació."},
      {"q": "«No hi he estat ___.»", "o": ["mai", "sempre", "ja"], "e": "Mai: en cap moment."},
      {"q": "Quin adverbi en -ment es forma a partir de «ràpid»?", "o": ["ràpidament", "ràpidement", "rapidament"], "e": "Femení de l'adjectiu + -ment: ràpida + ment."},
      {"q": "Quin adverbi en -ment es forma a partir de «clar»?", "o": ["clarament", "clarment", "clarement"], "e": "Clara + ment."},
      {"q": "Quin adverbi en -ment es forma a partir de «feliç»?", "o": ["feliçment", "felicment", "felisment"], "e": "Adjectius d'una terminació: feliç → feliçment."},
      {"q": "Quin adverbi en -ment es forma a partir de «fàcil»?", "o": ["fàcilment", "facilment", "fàcilament"], "e": "Fàcil → fàcilment (conserva l'accent)."},
      {"q": "Quin adverbi en -ment es forma a partir de «segur»?", "o": ["segurament", "segurment", "segurement"], "e": "Segura + ment."},
      {"q": "Quina és correcta?", "o": ["Parlava lenta i tranquil·lament.", "Parlava lentament i tranquil·la.", "Parlava lenta i tranquil·la."], "e": "Amb dos adverbis coordinats en -ment, també és correcte posar el sufix només en l'últim: lenta i tranquil·lament (o lentament i tranquil·lament)."},
      {"q": "«Ma germana és ___ alta ___ jo.» (superioritat)", "o": ["més / que", "més / com", "tan / que"], "e": "Més ... que."},
      {"q": "«Este cotxe és ___ car ___ l'altre.» (inferioritat)", "o": ["menys / que", "menys / com", "tan / que"], "e": "Menys ... que."},
      {"q": "«Pau és ___ simpàtic ___ el seu germà.» (igualtat)", "o": ["tan / com", "tant / com", "tan / que"], "e": "Tan + adjectiu o adverbi + com."},
      {"q": "«Treballa ___ ___ tu.» (igualtat amb verb)", "o": ["tant / com", "tan / com", "tant / que"], "e": "Verb + tant com: treballa tant com tu."},
      {"q": "«Té ___ llibres ___ jo.» (igualtat amb nom)", "o": ["tants / com", "tan / com", "tant / que"], "e": "Tant/tanta/tants/tantes + nom + com."},
      {"q": "«Hi havia ___ gent que no podíem entrar.» (consecutiva)", "o": ["tanta", "tan", "tant de"], "e": "Tanta + nom femení + que: consecutiva intensiva."},
      {"q": "«Corre ___ de pressa que ningú l'alcança.»", "o": ["tan", "tant", "tanta"], "e": "Tan + adverbi + que."},
      {"q": "«Viu ___ prop de l'escola.»", "o": ["molt", "molta", "molts"], "e": "Molt com a adverbi és invariable: molt prop."},
      {"q": "«Hui fa ___ més calor que ahir.»", "o": ["molta", "molt", "molts"], "e": "Molta més calor (calor és femení: la calor)."},
      {"q": "«Arribarem ___.» (en poc de temps)", "o": ["prompte", "pronte", "pronto"], "e": "Prompte: aviat."},
      {"q": "«___ no ho sé.» (potser, dubte)", "o": ["Potser", "Sens dubte", "I tant"], "e": "Potser, tal vegada, a la millor: dubte."},
      {"q": "«Ho has fet ___: no hi ha cap error.»", "o": ["perfectament", "perfecta", "perfectement"], "e": "Perfecta + ment."},
      {"q": "Escriu l'adverbi en -ment de «tranquil».", "a": ["tranquil·lament"], "e": "Tranquil·la + ment."},
      {"q": "Escriu l'adverbi en -ment de «lent».", "a": ["lentament"], "e": "Lentament."},
      {"q": "Escriu la paraula de la comparació d'igualtat: «És tan alt ___ son pare.»", "a": ["com"], "e": "Tan ... com."},
      {"q": "Escriu el contrari de «també» en una frase negativa.", "a": ["tampoc"], "e": "Tampoc."}
    ]
  },
  {
    "id": "46796358-e58c-4953-a44d-261766273faa", "type": "b1_mor_connectors", "sort_order": 11,
    "title": "Conjuncions i connectors", "name": "Adversatius, concessius, consecutius, temporals i condicionals",
    "content": "Conjuncions i connectors adversatius i concessius (encara que, sinó, tot i que), consecutius (doncs, per tant, així), temporals (quan, mentres, cada volta que, abans que, després que) i condicionals (si, en cas que) (3.2.2).", "icon": "🔗", "color": "#E6EE9C",
    "exercises": [
      {"q": "«No vull café, ___ te.»", "o": ["sinó", "si no", "però"], "e": "Sinó: corregix una negació anterior (no A, sinó B)."},
      {"q": "«___ vens, avisa'm.» (condició)", "o": ["Si no", "Sinó", "Sino"], "e": "Si no (separat): condició negativa. Sinó: «no A, sinó B»."},
      {"q": "«No és que no vullga, ___ no pot.»", "o": ["sinó que", "si no que", "però que"], "e": "Sinó que + oració."},
      {"q": "«És car, ___ val la pena.»", "o": ["però", "sinó", "perquè"], "e": "Però: oposició."},
      {"q": "«___ plou, eixirem a passejar.» (concessiva)", "o": ["Encara que", "Perquè", "Així que"], "e": "Encara que: concessió (malgrat que)."},
      {"q": "«___ estava cansat, va acabar la faena.»", "o": ["Tot i que", "Per tant", "Sempre que"], "e": "Tot i que = encara que."},
      {"q": "«Ha estudiat molt; ___, ha aprovat.»", "o": ["per tant", "encara que", "sinó"], "e": "Per tant: conseqüència."},
      {"q": "«No t'agrada? ___, no te'l menges.» (conseqüència)", "o": ["Doncs", "Perquè", "Encara que"], "e": "Doncs: consecutiu. No s'usa com a causal («puix»)."},
      {"q": "«Feia molt de fred, ___ vam encendre l'estufa.»", "o": ["així que", "encara que", "sinó"], "e": "Així que / de manera que: conseqüència."},
      {"q": "«___ arribes, telefona'm.»", "o": ["Quan", "Quant", "Mentre que no"], "e": "Quan: temporal."},
      {"q": "«___ cuinava, escoltava la ràdio.» (simultaneïtat)", "o": ["Mentres (o mentre)", "Després que", "Abans que"], "e": "Mentres: dues accions al mateix temps."},
      {"q": "«___ ve, porta un regal.» (repetició)", "o": ["Cada volta que", "Abans que", "Encara que"], "e": "Cada volta (o vegada) que: repetició."},
      {"q": "«Renta't les mans ___ menjar.»", "o": ["abans de", "abans que", "després que"], "e": "Abans de + infinitiu (mateix subjecte)."},
      {"q": "«Hem d'eixir ___ comence a ploure.»", "o": ["abans que (no)", "abans de", "després de"], "e": "Abans que (no) + subjuntiu (subjectes diferents)."},
      {"q": "«___ dinar, farem la becaina.»", "o": ["Després de", "Després que", "Abans que"], "e": "Després de + infinitiu."},
      {"q": "«T'ajudaré ___ m'ho demanes.»", "o": ["sempre que", "sinó", "encara"], "e": "Sempre que: cada vegada que / amb la condició que."},
      {"q": "«___, el partit s'ajornarà.» (condició amb «en cas que»)", "o": ["En cas que ploga", "En cas que plou", "En cas que plourà"], "e": "En cas que + subjuntiu: en cas que ploga."},
      {"q": "«___ tinguera diners, viatjaria.»", "o": ["Si", "Sinó", "Quan"], "e": "Si + imperfet de subjuntiu, condicional en la principal."},
      {"q": "Quina és correcta?", "o": ["Si tinguera temps, t'ajudaria.", "Si tindria temps, t'ajudaria.", "Si tenia temps, t'ajudaria."], "e": "Mai «si» + condicional: si tinguera."},
      {"q": "«No va vindre ___ estava malalt.» (causa)", "o": ["perquè", "per què", "per a què"], "e": "Perquè: causa."},
      {"q": "«Parla més fort ___ et sentim.» (finalitat)", "o": ["perquè", "per què", "per tant"], "e": "Perquè + subjuntiu: finalitat (perquè et sentim)."},
      {"q": "«___ siga difícil, ho aconseguirem.»", "o": ["Per difícil que", "Per tant", "Doncs"], "e": "Per + adjectiu + que + subjuntiu: concessiva."},
      {"q": "«Malgrat ___, vam anar d'excursió.»", "o": ["la pluja", "que la pluja", "de la pluja"], "e": "Malgrat + nom / malgrat que + verb."},
      {"q": "«Esperarem ___ arribe.»", "o": ["fins que", "fins a", "fins"], "e": "Fins que + verb."},
      {"q": "«___ va eixir el sol, vam anar a la platja.»", "o": ["Tan prompte com", "Encara que", "Sinó"], "e": "Tan prompte com: immediatament després que."},
      {"q": "«Tenia raó; ___, ningú li va fer cas.»", "o": ["tanmateix", "per tant", "així que"], "e": "Tanmateix (o no obstant això): oposició."},
      {"q": "Escriu el connector: «No és roig, ___ taronja.»", "a": ["sinó"], "e": "Sinó."},
      {"q": "Escriu el connector: «___ ploga, eixiré.» (concessiu, dues paraules)", "a": ["encara que", "tot i que"], "e": "Encara que."},
      {"q": "Escriu el connector consecutiu de dues paraules: «Ha plogut; per ___, el camp està mullat.»", "a": ["tant"], "e": "Per tant."},
      {"q": "Escriu el connector temporal de simultaneïtat: «___ tu cuines, jo pare la taula.»", "a": ["mentres", "mentre", "mentre que", "mentres que"], "e": "Mentres (o mentre)."}
    ]
  },
  {
    "id": "89c56ceb-f29e-42f7-b327-8f498302c9ed", "type": "b1_mor_verbs_regulars", "sort_order": 12,
    "title": "Verbs regulars", "name": "Present, passat, perfet, plusquamperfet, futur, subjuntiu i condicional",
    "content": "Conjugació dels verbs regulars: present, passat simple i perifràstic, perfet, plusquamperfet, futur d'indicatiu, present i imperfet de subjuntiu i condicional simple (3.2.2).", "icon": "⏳", "color": "#BBDEFB",
    "exercises": [
      {"q": "«Jo ___ en una botiga.» (treballar, present)", "o": ["treballe", "treballo", "treball"], "e": "En valencià, la primera persona del present: treballe, cante, parle."},
      {"q": "«Nosaltres ___ valencià.» (parlar, present)", "o": ["parlem", "parlam", "parlàm"], "e": "Parlem, parleu, parlen."},
      {"q": "«Ells ___ molta fruita.» (menjar, present)", "o": ["mengen", "menjen", "menjan"], "e": "Menjar: menge, menges, menja, mengem, mengeu, mengen."},
      {"q": "«Jo ___ a les set.» (dormir, present)", "o": ["dorm", "dormisc", "dormo"], "e": "Dormir és pur: jo dorm, tu dorms, ell dorm."},
      {"q": "«Jo ___ el menjar.» (servir, present)", "o": ["servisc", "servix", "servixo"], "e": "Verbs incoatius: servisc, servixes, servix, servim, serviu, servixen."},
      {"q": "«Ell ___ molt bé.» (llegir, present)", "o": ["llig", "llegix", "lleix"], "e": "Llegir: llig, lliges, llig, llegim, llegiu, lligen."},
      {"q": "«Ahir ___ al cine.» (anar, perifràstic, jo)", "o": ["vaig anar", "vaig a anar", "aní vaig"], "e": "Passat perifràstic: vaig + infinitiu (vaig anar = aní)."},
      {"q": "«L'any passat ___ a Roma.» (viatjar, perifràstic, nosaltres)", "o": ["vam viatjar (o vàrem viatjar)", "anem viatjar", "vam viatjat"], "e": "Vam / vàrem + infinitiu."},
      {"q": "«Ahir ell ___ tota la vesprada.» (estudiar, passat simple)", "o": ["estudià", "estudiava", "estudie"], "e": "Passat simple: estudií, estudiares, estudià, estudiàrem, estudiàreu, estudiaren."},
      {"q": "Quina és la forma de passat simple de «cantar» per a «tu»?", "o": ["cantares", "cantaves", "cantaràs"], "e": "Tu cantares (= vas cantar)."},
      {"q": "«Hui ___ molt.» (treballar, perfet, jo)", "o": ["he treballat", "havia treballat", "vaig treballar"], "e": "Perfet: he + participi, per a fets d'un temps no acabat (hui, enguany, esta setmana)."},
      {"q": "«Enguany ___ molts llibres.» (llegir, perfet, nosaltres)", "o": ["hem llegit", "havem llegits", "vam llegir hui"], "e": "Hem llegit (també «havem» col·loquial; en estàndard, hem)."},
      {"q": "«Quan vaig arribar, el tren ja ___.» (eixir, plusquamperfet)", "o": ["havia eixit", "ha eixit", "va eixir"], "e": "Plusquamperfet: havia + participi, una acció anterior a una altra del passat."},
      {"q": "«Demà ___ a la platja.» (anar, futur, nosaltres)", "o": ["anirem", "anarem", "anem a anar"], "e": "Futur: aniré, aniràs, anirà, anirem, anireu, aniran."},
      {"q": "«L'any que ve ___ a la universitat.» (estudiar, futur, jo)", "o": ["estudiaré", "estudiarè", "estudiare"], "e": "Estudiaré (amb é tancada)."},
      {"q": "«Vull que ___ prompte.» (arribar, present de subjuntiu, tu)", "o": ["arribes", "arribaràs", "arribe"], "e": "Present de subjuntiu: arribe, arribes, arribe, arribem, arribeu, arriben."},
      {"q": "«Espere que ell ___ el problema.» (entendre, present de subjuntiu)", "o": ["entenga", "entén", "entendrà"], "e": "Entendre: que jo entenga, que ell entenga."},
      {"q": "«Espere que ells ___ la porta.» (obrir, present de subjuntiu)", "o": ["obriguen", "obren", "obrisquen"], "e": "Obrir: que obriga, obrigues, obriga, obrim, obriu, obriguen."},
      {"q": "«Si ___ temps, vindria.» (tindre, imperfet de subjuntiu)", "o": ["tinguera", "tindria", "tenia"], "e": "Imperfet de subjuntiu: tinguera, tingueres, tinguera..."},
      {"q": "«Si ___ més, aprovaries.» (estudiar, imperfet de subjuntiu, tu)", "o": ["estudiares", "estudiaries", "estudiaves"], "e": "Estudiara, estudiares, estudiara, estudiàrem, estudiàreu, estudiaren."},
      {"q": "«M'agradaria que ___ a la festa.» (vindre, imperfet de subjuntiu, vosaltres)", "o": ["vinguéreu", "vindríeu", "veníeu"], "e": "Imperfet de subjuntiu: vinguera, vingueres, vinguera, vinguérem, vinguéreu, vingueren."},
      {"q": "«Jo ___ una casa al camp.» (comprar, condicional)", "o": ["compraria", "compraré", "comprara"], "e": "Condicional: compraria, compraries, compraria, compraríem, compraríeu, comprarien."},
      {"q": "«Nosaltres ___ encantats.» (estar, condicional)", "o": ["estaríem", "estaríam", "estarem"], "e": "Estaríem (amb accent)."},
      {"q": "«Quan era xicotet, ___ a futbol cada dia.» (jugar, imperfet)", "o": ["jugava", "jugaba", "juguí"], "e": "Imperfet: jugava, jugaves, jugava, jugàvem, jugàveu, jugaven."},
      {"q": "Quina és la forma del gerundi de «cantar»?", "o": ["cantant", "cantan", "cantando"], "e": "Gerundi: cantant, temint, dormint."},
      {"q": "Quina és la forma del participi de «temer»?", "o": ["temut", "temit", "temido"], "e": "Participi de la segona conjugació: temut, perdut, venut."},
      {"q": "Escriu el present de «cantar» per a «jo».", "a": ["cante"], "e": "Cante."},
      {"q": "Escriu el futur de «parlar» per a «nosaltres».", "a": ["parlarem"], "e": "Parlarem."},
      {"q": "Escriu el passat perifràstic de «menjar» per a «jo».", "a": ["vaig menjar"], "e": "Vaig menjar."},
      {"q": "Escriu el condicional de «viatjar» per a «jo».", "a": ["viatjaria"], "e": "Viatjaria."},
      {"q": "Escriu l'imperfet de subjuntiu de «parlar» per a «jo».", "a": ["parlara", "parlés"], "e": "Parlara (o parlés)."}
    ]
  },
  {
    "id": "8c30c366-0748-47c4-9314-14ad0cc65797", "type": "b1_mor_verbs_irregulars", "sort_order": 13,
    "title": "Verbs irregulars", "name": "Nàixer, córrer, saber, voler, ser, vore, anar, estar, fer, dir, poder, tindre, conéixer, omplir, obrir i tossir",
    "content": "Conjugació dels verbs irregulars del B1: nàixer, córrer, saber, voler, ser, vore, anar, estar, fer, dir-se, poder, tindre, conéixer, omplir, obrir i tossir (3.2.2).", "icon": "🌀", "color": "#FFCDD2",
    "exercises": [
      {"q": "«Jo ___ a Gandia.» (nàixer, passat perifràstic)", "o": ["vaig nàixer", "vaig naixer", "vaig néixer"], "e": "Nàixer (o néixer): vaig nàixer. Participi: nascut."},
      {"q": "Quin és el participi de «nàixer»?", "o": ["nascut", "naixut", "nacit"], "e": "Nascut / nascuda."},
      {"q": "«Jo ___ cada matí.» (córrer, present)", "o": ["córrec", "corre", "corro"], "e": "Córrer: córrec, corres, corre, correm, correu, corren."},
      {"q": "Quin és el participi de «córrer»?", "o": ["corregut", "corrut", "corrit"], "e": "Corregut."},
      {"q": "«No ___ on viu.» (saber, present, jo)", "o": ["sé", "sap", "sabo"], "e": "Saber: sé, saps, sap, sabem, sabeu, saben."},
      {"q": "«Vull que ho ___.» (saber, subjuntiu, tu)", "o": ["sàpies", "sabes", "sapigues"], "e": "Subjuntiu: sàpia, sàpies, sàpia, sapiem, sapieu, sàpien."},
      {"q": "«Jo ___ un café.» (voler, present)", "o": ["vull", "vol", "volc"], "e": "Voler: vull, vols, vol, volem, voleu, volen."},
      {"q": "«Fes el que ___.» (voler, subjuntiu, tu)", "o": ["vullgues", "vols", "volgues"], "e": "Que jo vullga, que tu vullgues."},
      {"q": "Quin és el participi de «voler»?", "o": ["volgut", "volit", "vullgut"], "e": "Volgut."},
      {"q": "«Nosaltres ___ de València.» (ser, present)", "o": ["som", "sem", "sóm"], "e": "Ser: sóc (o soc), eres, és, som, sou, són."},
      {"q": "«Espere que ___ feliços.» (ser, subjuntiu, vosaltres)", "o": ["sigueu", "sou", "sigau"], "e": "Subjuntiu de ser: siga, sigues, siga, siguem, sigueu, siguen."},
      {"q": "«Si ___ ric, viatjaria.» (ser, imperfet de subjuntiu, jo)", "o": ["fora", "seria", "era"], "e": "Imperfet de subjuntiu de ser: fora, fores, fora, fórem, fóreu, foren."},
      {"q": "«Jo ___ la mar des de la finestra.» (vore, present)", "o": ["veig", "veu", "vec"], "e": "Vore (o veure): veig, veus, veu, veiem, veieu, veuen."},
      {"q": "Quin és el participi de «vore»?", "o": ["vist", "vorut", "veut"], "e": "Vist / vista."},
      {"q": "«Demà ___ la pel·lícula.» (vore, futur, nosaltres)", "o": ["vorem", "vorerem", "veiem"], "e": "Vore: voré, voràs, vorà, vorem, voreu, voran (amb veure: veuré)."},
      {"q": "«Jo ___ a l'escola a peu.» (anar, present)", "o": ["vaig", "vac", "vaig a"], "e": "Anar: vaig, vas, va, anem, aneu, van."},
      {"q": "«Vull que ___ al metge.» (anar, subjuntiu, tu)", "o": ["vages", "vas", "anes"], "e": "Que jo vaja, que tu vages, que ell vaja, que anem, que aneu, que vagen."},
      {"q": "«Jo ___ molt cansat.» (estar, present)", "o": ["estic", "estoc", "estàc"], "e": "Estar: estic, estàs, està, estem, esteu, estan."},
      {"q": "«Espere que ___ bé.» (estar, subjuntiu, tu)", "o": ["estigues", "estàs", "esteves"], "e": "Que estiga, estigues, estiga..."},
      {"q": "«Jo ___ el sopar.» (fer, present)", "o": ["faig", "fac", "fai"], "e": "Fer: faig, fas, fa, fem, feu, fan."},
      {"q": "«Vull que ho ___ ara.» (fer, subjuntiu, tu)", "o": ["faces", "fas", "fagues"], "e": "Que faça, faces, faça, fem, feu, facen."},
      {"q": "«Ahir ell ___ els deures.» (fer, passat simple)", "o": ["féu", "feu", "fiu"], "e": "Passat simple: fiu, feres, féu, férem, féreu, feren."},
      {"q": "«Com et ___?» (dir-se, present, tu)", "o": ["dius", "dieus", "dius-te"], "e": "Dir: dic, dius, diu, diem, dieu, diuen. Com et dius?"},
      {"q": "«Vull que em ___ la veritat.» (dir, subjuntiu, tu)", "o": ["digues", "dius", "diguis"], "e": "Que diga, digues, diga..."},
      {"q": "«Jo no ___ vindre.» (poder, present)", "o": ["puc", "pot", "poc"], "e": "Poder: puc, pots, pot, podem, podeu, poden."},
      {"q": "«Espere que ___ vindre.» (poder, subjuntiu, ell)", "o": ["puga", "pot", "pogue"], "e": "Que puga, pugues, puga, puguem, pugueu, puguen."},
      {"q": "«Jo ___ dos gats.» (tindre, present)", "o": ["tinc", "tenc", "tin"], "e": "Tindre (o tenir): tinc, tens, té, tenim, teniu, tenen."},
      {"q": "Quin és el participi de «tindre»?", "o": ["tingut", "tengut", "tenit"], "e": "Tingut."},
      {"q": "«Jo no ___ ningú ací.» (conéixer, present)", "o": ["conec", "conéixo", "coneix"], "e": "Conéixer: conec, coneixes, coneix, coneixem, coneixeu, coneixen."},
      {"q": "Quin és el participi de «conéixer»?", "o": ["conegut", "conéixut", "coneixit"], "e": "Conegut."},
      {"q": "«Ell ___ el got d'aigua.» (omplir, present)", "o": ["ompli", "omple", "omplix"], "e": "Omplir: omplic, omples, ompli, omplim, ompliu, omplen."},
      {"q": "«Jo ___ la finestra.» (obrir, present)", "o": ["obric", "obro", "obrisc"], "e": "Obrir: obric, obris, obri, obrim, obriu, obrin (o obren)."},
      {"q": "Quin és el participi de «obrir»?", "o": ["obert", "obrit", "obrut"], "e": "Obert / oberta."},
      {"q": "«Ell ___ molt a la nit.» (tossir, present)", "o": ["tus", "tos", "tossix"], "e": "Tossir: tus, tusses, tus, tossim, tossiu, tussen."},
      {"q": "Escriu el present de «tindre» per a «jo».", "a": ["tinc"], "e": "Tinc."},
      {"q": "Escriu el present de «fer» per a «jo».", "a": ["faig"], "e": "Faig."},
      {"q": "Escriu el participi de «obrir».", "a": ["obert"], "e": "Obert."},
      {"q": "Escriu el present de subjuntiu de «anar» per a «jo»: que jo ___.", "a": ["vaja"], "e": "Vaja."},
      {"q": "Escriu el present de «conéixer» per a «jo».", "a": ["conec"], "e": "Conec."}
    ]
  },
  {
    "id": "f7e75d17-2e5c-4058-8a7a-add0197ad5c4", "type": "b1_mor_regim", "sort_order": 14,
    "title": "Verbs de règim preposicional", "name": "Atrevir-se a, començar a, decidir-se a, negar-se a, pensar en, confiar en...",
    "content": "Els verbs que porten una preposició fixa davant del complement (atrevir-se a, començar a, decidir-se a, negar-se a, pensar en, confiar en...) i la caiguda de la preposició davant de que (3.2.2).", "icon": "🧷", "color": "#D7CCC8",
    "exercises": [
      {"q": "«No m'atrevisc ___ dir-li-ho.»", "o": ["a", "de", "en"], "e": "Atrevir-se a."},
      {"q": "«Ha començat ___ ploure.»", "o": ["a", "de", "per"], "e": "Començar a + infinitiu."},
      {"q": "«Per fi s'ha decidit ___ comprar el pis.»", "o": ["a", "de", "en"], "e": "Decidir-se a (però «decidir» sense pronom: he decidit comprar-lo)."},
      {"q": "«Es nega ___ menjar verdura.»", "o": ["a", "de", "en"], "e": "Negar-se a."},
      {"q": "«Pense molt ___ tu.»", "o": ["en", "a", "de"], "e": "Pensar en algú o en alguna cosa."},
      {"q": "«Confie ___ tu: sé que ho faràs bé.»", "o": ["en", "a", "de"], "e": "Confiar en."},
      {"q": "«M'he acostumat ___ matinar.»", "o": ["a", "de", "en"], "e": "Acostumar-se a."},
      {"q": "«Estic aprenent ___ nadar.»", "o": ["a", "de", "per"], "e": "Aprendre a + infinitiu."},
      {"q": "«M'ha ajudat ___ fer la mudança.»", "o": ["a", "de", "en"], "e": "Ajudar a + infinitiu."},
      {"q": "«Ens han convidat ___ sopar.»", "o": ["a", "de", "per"], "e": "Convidar a."},
      {"q": "«S'ha enamorat ___ una companya de classe.»", "o": ["d'", "a", "en"], "e": "Enamorar-se de."},
      {"q": "«No ___ el seu nom.» (recordar)", "o": ["recorde", "recorde de", "me'n recorde el"], "e": "Recordar alguna cosa, sense preposició: no recorde el seu nom. Amb pronom: no me'n recorde."},
      {"q": "«M'he oblidat ___ les claus.»", "o": ["de", "a", "en"], "e": "Oblidar-se de (o oblidar alguna cosa: he oblidat les claus)."},
      {"q": "«No m'he adonat ___ l'error.»", "o": ["de", "a", "en"], "e": "Adonar-se de."},
      {"q": "«S'ha adonat ___ ningú l'escoltava.»", "o": ["que", "de que", "en que"], "e": "Davant de la conjunció que, la preposició cau: s'ha adonat que..."},
      {"q": "«Pense ___ vindrà demà.»", "o": ["que", "en que", "de que"], "e": "Pensar que + oració (sense en)."},
      {"q": "«Confie ___ tot eixirà bé.»", "o": ["que", "en que", "de que"], "e": "Confiar que (la preposició en cau davant de que)."},
      {"q": "«Insistix ___ pagar ell.»", "o": ["a (o en)", "de", "per"], "e": "Insistir a (o en) + infinitiu."},
      {"q": "«El joc consistix ___ endevinar la paraula.»", "o": ["a (o en)", "de", "per"], "e": "Consistir en (o a)."},
      {"q": "«Es dedica ___ la docència.»", "o": ["a", "de", "en"], "e": "Dedicar-se a."},
      {"q": "«Tinc ganes ___ vore't.»", "o": ["de", "a", "per"], "e": "Tindre ganes de."},
      {"q": "«S'ha queixat ___ soroll.»", "o": ["del", "al", "en el"], "e": "Queixar-se de."},
      {"q": "«Ha tardat molt ___ arribar.»", "o": ["a", "de", "per"], "e": "Tardar a (o en) + infinitiu."},
      {"q": "«Han obligat els treballadors ___ fer hores extra.»", "o": ["a", "de", "en"], "e": "Obligar a."},
      {"q": "«Es fia molt ___ la seua germana.»", "o": ["de", "a", "en"], "e": "Fiar-se de."},
      {"q": "«Ens hem posat d'acord ___ el preu.»", "o": ["en (o sobre)", "a", "per"], "e": "Posar-se d'acord en / sobre alguna cosa."},
      {"q": "«Depén ___ tu.»", "o": ["de", "a", "en"], "e": "Dependre de."},
      {"q": "«Està interessat ___ la feina.»", "o": ["en (o per)", "a", "de"], "e": "Interessat en o per."},
      {"q": "Escriu la preposició: «No t'atrevixes ___ saltar?»", "a": ["a"], "e": "Atrevir-se a."},
      {"q": "Escriu la preposició: «Pensa ___ els altres.»", "a": ["en"], "e": "Pensar en."},
      {"q": "Escriu la preposició: «S'ha negat ___ signar.»", "a": ["a"], "e": "Negar-se a."},
      {"q": "Escriu la preposició: «Ens hem enamorat ___ este poble.»", "a": ["de"], "e": "Enamorar-se de."}
    ]
  },
  {
    "id": "e5f3f3e9-5a53-441d-b318-060e27c2c04c", "type": "b1_mor_modes", "sort_order": 15,
    "title": "Indicatiu, subjuntiu i imperatiu", "name": "Usos dels modes verbals",
    "content": "Quan s'usa l'indicatiu, el subjuntiu i l'imperatiu: desig, dubte, finalitat, temps futur, relatives i ordres afirmatives i negatives (3.2.2).", "icon": "🎭", "color": "#B2EBF2",
    "exercises": [
      {"q": "«Sé que ___ raó.» (tindre, tu)", "o": ["tens", "tingues", "tinguera"], "e": "Saber que + indicatiu: es presenta com un fet."},
      {"q": "«Vull que ___ a la festa.» (vindre, tu)", "o": ["vingues", "véns", "vindràs"], "e": "Voler que + subjuntiu (desig)."},
      {"q": "«Espere que ___ bon temps demà.» (fer)", "o": ["faça", "fa", "farà"], "e": "Esperar que + subjuntiu."},
      {"q": "«Tant de bo ___!» (aprovar, tu)", "o": ["aproves", "aprovaràs", "aprovas"], "e": "Tant de bo + subjuntiu: desig."},
      {"q": "«Crec que ___ a ploure.» (anar)", "o": ["va", "vaja", "anara"], "e": "Creure que (afirmatiu) + indicatiu."},
      {"q": "«No crec que ___ a ploure.» (anar)", "o": ["vaja", "va", "anirà"], "e": "No creure que + subjuntiu (dubte)."},
      {"q": "«És possible que ___ tard.» (arribar, ells)", "o": ["arriben", "arribaran", "arribaven"], "e": "És possible / és probable que + subjuntiu."},
      {"q": "«És evident que ___ raó.» (tindre, ell)", "o": ["té", "tinga", "tinguera"], "e": "És evident / és clar que + indicatiu (certesa)."},
      {"q": "«T'ho explique perquè ho ___.» (entendre, tu: finalitat)", "o": ["entengues", "entens", "entendràs"], "e": "Perquè de finalitat + subjuntiu."},
      {"q": "«No ha vingut perquè ___ malalt.» (estar, ell: causa)", "o": ["està", "estiga", "estiguera"], "e": "Perquè de causa + indicatiu."},
      {"q": "«Quan ___ a casa, telefona'm.» (arribar, tu)", "o": ["arribes", "arribaràs", "arribaries"], "e": "Quan + futur → present de subjuntiu: quan arribes."},
      {"q": "«Quan ___ a casa, sempre sopem junts.» (arribar, jo: costum)", "o": ["arribe (indicatiu)", "arribaré", "arribara"], "e": "Quan + costum: indicatiu (arribe)."},
      {"q": "«Busque un pis que ___ terrassa.» (tindre: encara no el conec)", "o": ["tinga", "té", "tindrà"], "e": "Relativa amb antecedent desconegut: subjuntiu."},
      {"q": "«Visc en un pis que ___ terrassa.» (tindre: el conec)", "o": ["té", "tinga", "tinguera"], "e": "Antecedent conegut: indicatiu."},
      {"q": "«M'agradaria que ___ amb mi.» (vindre, tu)", "o": ["vingueres", "vingues", "vindries"], "e": "Condicional en la principal → imperfet de subjuntiu."},
      {"q": "Quin és l'imperatiu de «cantar» per a «tu»?", "o": ["canta", "cantes", "cante"], "e": "Imperatiu: canta (tu), cante (vosté), cantem, canteu, canten (vostés)."},
      {"q": "Quin és l'imperatiu de «cantar» per a «vosté»?", "o": ["cante", "canta", "cantes"], "e": "Vosté: cante (forma del subjuntiu)."},
      {"q": "Quin és l'imperatiu negatiu de «cantar» per a «tu»?", "o": ["no cantes", "no canta", "no cantar"], "e": "L'imperatiu negatiu usa el subjuntiu: no cantes, no canteu."},
      {"q": "Quin és l'imperatiu de «vindre» per a «tu»?", "o": ["vine", "vin", "vens"], "e": "Vine (tu), vinga (vosté), veniu (vosaltres)."},
      {"q": "Quin és l'imperatiu negatiu de «vindre» per a «tu»?", "o": ["no vingues", "no vine", "no véns"], "e": "No vingues."},
      {"q": "Quin és l'imperatiu de «fer» per a «tu»?", "o": ["fes", "fa", "faces"], "e": "Fes (tu), faça (vosté), feu (vosaltres)."},
      {"q": "Quin és l'imperatiu de «anar» per a «tu»?", "o": ["ves", "va", "vages"], "e": "Ves (tu), vaja (vosté), aneu (vosaltres). Ves-te'n!"},
      {"q": "Quin és l'imperatiu de «dir» per a «tu»?", "o": ["digues", "diu", "di"], "e": "Digues (tu), diga (vosté), digueu (vosaltres)."},
      {"q": "Quin és l'imperatiu de «ser» per a «tu»?", "o": ["sigues", "és", "sé"], "e": "Sigues bo!, sigueu puntuals!"},
      {"q": "Quin és l'imperatiu de «tindre» per a «tu» quan dones una cosa?", "o": ["té (o tin)", "tens", "tingues"], "e": "Té! (o tin): agafa. Tingues paciència: tingues."},
      {"q": "Quin és l'imperatiu de «seure» per a «vosaltres»?", "o": ["seieu", "seeu", "seureu"], "e": "Seure: seu (tu), siga o sega (vosté), seieu (vosaltres)."},
      {"q": "«Perdone, ___'m on és l'estació.» (dir, vosté)", "o": ["diga", "digues", "diu"], "e": "Amb vosté: diga'm (diga + em)."},
      {"q": "«No ___ tan de pressa!» (córrer, tu)", "o": ["corregues", "corres", "corre"], "e": "Imperatiu negatiu: no corregues."},
      {"q": "Escriu l'imperatiu de «parlar» per a «tu».", "a": ["parla"], "e": "Parla."},
      {"q": "Escriu l'imperatiu negatiu de «parlar» per a «tu»: no ___.", "a": ["parles"], "e": "No parles."},
      {"q": "Escriu el verb en subjuntiu: «Vull que ___ (vindre, tu).»", "a": ["vingues"], "e": "Vingues."},
      {"q": "Escriu el verb en indicatiu: «Sé que ___ (estar, ell) ací.»", "a": ["està"], "e": "Està."}
    ]
  },
  {
    "id": "379adbb2-a63b-465b-85a8-57fc66b1f877", "type": "b1_mor_perifrasis", "sort_order": 16,
    "title": "Ser, estar, semblar i perífrasis", "name": "Ser i estar locatius, semblar, haver de, caldre i deure",
    "content": "Els verbs ser i estar amb valor locatiu, el verb semblar i les perífrasis d'obligació (haver de, deure, caldre + infinitiu) i de probabilitat (deure + infinitiu) (3.2.2).", "icon": "🧭", "color": "#C8E6C9",
    "exercises": [
      {"q": "«On ___ el museu?» (localització d'un edifici)", "o": ["és (o està)", "hi ha", "fa"], "e": "Per a localitzar, en valencià s'usen ser i estar: on és / on està el museu."},
      {"q": "«El concert ___ a la plaça Major.» (localització d'un esdeveniment)", "o": ["serà", "estarà", "hi haurà a"], "e": "Per als esdeveniments (concerts, festes, reunions), ser: el concert serà a la plaça."},
      {"q": "«La reunió ___ en la sala de professors.»", "o": ["és", "està", "té"], "e": "Esdeveniment → ser."},
      {"q": "«Ara mateix el meu germà ___ a casa.»", "o": ["està (o és)", "hi ha", "té"], "e": "Persones i coses: ser o estar locatiu."},
      {"q": "«___ una farmàcia a prop?» (existència)", "o": ["Hi ha", "Està", "És"], "e": "Hi ha: existència (sense determinant definit)."},
      {"q": "«Està cansat? ___ que no ha dormit.»", "o": ["Sembla", "Assembla", "Es sembla"], "e": "Semblar que: tindre aparença."},
      {"q": "«Què et ___ el pla?» «Em ___ molt bé.»", "o": ["sembla / sembla", "assembla / assembla", "sembles / semblen"], "e": "Semblar: opinió (em sembla bé)."},
      {"q": "«El xiquet ___ molt a son pare.»", "o": ["s'assembla", "sembla", "assembla"], "e": "Assemblar-se a algú: tindre semblança física o de caràcter."},
      {"q": "«Pareixen germans» es pot dir també...", "o": ["«Semblen germans»", "«Assemblen germans»", "«Es semblen a germans»"], "e": "Semblar (o paréixer): tindre l'aparença de."},
      {"q": "«Demà ___ d'anar al metge.» (obligació, jo)", "o": ["he", "tinc que", "deuré de"], "e": "Haver de + infinitiu: he d'anar."},
      {"q": "Quina és la forma correcta d'expressar obligació?", "o": ["Has d'estudiar més.", "Tens que estudiar més.", "Tens de que estudiar més."], "e": "«Tindre que» és un castellanisme: haver de + infinitiu."},
      {"q": "«___ portar el DNI per a votar.» (obligació impersonal)", "o": ["Cal", "Calen", "Tenen que"], "e": "Caldre + infinitiu: cal portar."},
      {"q": "«___ que vingues prompte.»", "o": ["Cal", "Cal de", "Ha de"], "e": "Cal que + subjuntiu."},
      {"q": "«Em ___ uns pantalons nous.» (necessitat)", "o": ["calen", "cal", "fa falta que"], "e": "Caldre concorda amb el que es necessita: em cal un, em calen uns."},
      {"q": "«No ___ que vingues, ja ho faig jo.»", "o": ["cal", "calen", "tens que"], "e": "No cal que: no és necessari."},
      {"q": "«___ ser les cinc: ja es fa fosc.» (probabilitat)", "o": ["Deuen", "Han", "Calen"], "e": "Deure + infinitiu: probabilitat (deuen ser les cinc)."},
      {"q": "«No contesta: ___ estar dormint.» (probabilitat)", "o": ["deu", "ha", "cal"], "e": "Deu estar dormint = probablement està dormint."},
      {"q": "«Els fills ___ respectar els pares.» (obligació moral)", "o": ["deuen", "han de que", "tenen que"], "e": "Deure + infinitiu també pot expressar obligació."},
      {"q": "Quina frase expressa probabilitat?", "o": ["Deu tindre uns trenta anys.", "Ha de pagar la factura.", "Cal reciclar."], "e": "Deure + infinitiu: suposició."},
      {"q": "Quina frase expressa obligació impersonal?", "o": ["Cal reciclar.", "Deu ser tard.", "Sembla cansat."], "e": "Caldre: obligació o necessitat sense subjecte personal."},
      {"q": "«___ dutxar-se abans d'entrar a la piscina.»", "o": ["Cal", "Cal de", "Tens que"], "e": "Caldre + infinitiu, sense preposició: cal dutxar-se (o s'ha de dutxar)."},
      {"q": "«Ara mateix ___ estudiant.» (acció en curs, jo)", "o": ["estic", "sóc", "he"], "e": "Estar + gerundi: acció en curs."},
      {"q": "«___ d'arribar: encara porte l'abric.» (acció acabada fa poc)", "o": ["Acabe", "Comence", "Torne"], "e": "Acabar de + infinitiu: acció que fa molt poc que ha passat."},
      {"q": "«He ___ de fumar.» (ja no fume)", "o": ["deixat", "tornat", "acabat"], "e": "Deixar de + infinitiu: interrupció."},
      {"q": "«Ha ___ a ploure.» (una altra vegada)", "o": ["tornat", "deixat", "acabat"], "e": "Tornar a + infinitiu: repetició."},
      {"q": "Escriu el verb d'obligació: «___ d'anar a treballar.» (jo, present)", "a": ["he"], "e": "He d'anar."},
      {"q": "Escriu el verb impersonal: «___ portar el passaport.»", "a": ["cal"], "e": "Cal."},
      {"q": "Corregix la frase: «Tinc que estudiar.»", "a": ["he d'estudiar"], "e": "He d'estudiar."},
      {"q": "Escriu la forma de probabilitat: «___ ser les deu.» (deure)", "a": ["deuen"], "e": "Deuen ser les deu."}
    ]
  }
]$data$::jsonb) AS t(
  id uuid, type text, sort_order smallint, title text, name text,
  content text, icon text, color text, exercises jsonb
);

INSERT INTO public.resources (id, name, type, category, content, difficulty, xp_earned, sort_order, metadata)
SELECT id, name, type, 'morfosintaxi', content, 'intermedi', 15, sort_order,
       jsonb_build_object('icon', icon, 'color', color, 'section_name', title)
FROM practice_catalog
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  category = EXCLUDED.category,
  content = EXCLUDED.content,
  difficulty = EXCLUDED.difficulty,
  xp_earned = EXCLUDED.xp_earned,
  sort_order = EXCLUDED.sort_order,
  -- Conserva la lliçó fixa («Aprendre lliçó»), que s'afig en una migració posterior.
  metadata = EXCLUDED.metadata || jsonb_strip_nulls(jsonb_build_object('lesson', resources.metadata -> 'lesson'));

DELETE FROM public.practice_exercises e
USING practice_catalog c
WHERE e.resource_id = c.id AND e.level = 'B1';

INSERT INTO public.practice_exercises (resource_id, level, position, kind, prompt, options, answers, explanation)
SELECT c.id, 'B1', x.ord,
       CASE WHEN x.e ? 'a' THEN 'fill' ELSE 'choice' END,
       x.e->>'q',
       CASE WHEN x.e ? 'o' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'o')) END,
       CASE WHEN x.e ? 'a' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'a')) ELSE ARRAY[x.e->'o'->>0] END,
       x.e->>'e'
FROM practice_catalog c
CROSS JOIN LATERAL jsonb_array_elements(c.exercises) WITH ORDINALITY AS x(e, ord);

DROP TABLE practice_catalog;
