-- Fonètica, elocució i ortografia del B1 (Quadern B1 de la JQCV, 3.2.1). Un
-- contingut de la categoria fonetica_ortografia per a cada apartat del temari:
-- elocució i fonètica sintàctica; alfabet i grafies; síl·laba, diftong i hiat;
-- vocals; accentuació, dièresi i guionet; apostrofació i contracció; oclusives
-- i labiodentals; alveolars; palatals; laterals, nasals, ròtiques i h;
-- majúscules i minúscules; i signes de puntuació. Són recursos de nivell
-- intermedi amb exercicis B1. Tornar a aplicar el fitxer no duplica res.

CREATE TEMP TABLE practice_catalog AS
SELECT * FROM jsonb_to_recordset($data$[
  {
    "id": "013139cd-ab6b-45b5-99e7-58104459f974", "type": "b1_fon_elocucio", "sort_order": 1,
    "title": "Elocució i fonètica sintàctica", "name": "Elisions, sons propis, emmudiments, geminacions i entonació",
    "content": "Elisions vocàliques, sons consonàntics propis del valencià, emmudiments consonàntics freqüents, articulació de grups i geminacions i entonació interrogativa i exclamativa (3.2.1).", "icon": "🗣️", "color": "#B2EBF2",
    "exercises": [
      {"q": "En una pronunciació natural de «Quina hora és?», quina vocal no se sol pronunciar?", "o": ["la -a de «quina»", "la o d'«hora»", "la e d'«és»"], "e": "Dues vocals en contacte entre paraules s'unixen: [ki-no-ra-és]. La -a àtona final s'elidix davant d'una altra vocal."},
      {"q": "Com es pronuncia de manera natural «quinze anys»?", "o": ["[kin-zanys]", "[kin-ze-a-nys]", "[kin-zi-anys]"], "e": "La -e àtona final de «quinze» s'elidix davant de la a: [kinzanys]."},
      {"q": "En quina d'estes expressions s'elidix una vocal en la parla?", "o": ["una amiga", "un amic", "tres amics"], "e": "Una_amiga: la -a de «una» s'unix amb la a d'«amiga» [unamiga]. En «un amic» no hi ha dues vocals en contacte."},
      {"q": "Com es pronuncia de manera natural «Me'n vaig a Alacant»?", "o": ["amb una sola a: [aalacant] → [alacant]", "separant clarament [a] i [a-la-cant] amb una pausa", "afegint una consonant entre les dues a"], "e": "Dues vocals iguals en contacte es fonen en una: a_Alacant."},
      {"q": "En «Està a casa», com sona la seqüència «està a»?", "o": ["Les dues a es fonen en una de més llarga", "Es pronuncia «estàs a»", "S'hi afig una e"], "e": "Fusió de vocals iguals: està_a casa."},
      {"q": "Quina d'estes expressions NO té elisió vocàlica en la parla?", "o": ["un home", "quina hora", "quinze anys"], "e": "En «un home» no hi ha dues vocals en contacte: la n s'enllaça amb la vocal següent [u-no-me]. La h és muda."},
      {"q": "El so inicial de «juny» en valencià és...", "o": ["com el de «gent» o «platja», sonor", "com la jota castellana de «junio»", "com una i"], "e": "La j valenciana és una consonant palatal sonora, no la jota castellana."},
      {"q": "Com sona la g de «gener» en valencià?", "o": ["com la j de «jove»: palatal sonora", "com la jota castellana", "com la g de «gat»"], "e": "En valencià no existix el so de la jota castellana: g (davant e, i) i j sonen com en «platja»."},
      {"q": "En quina paraula la r sona forta (vibrant múltiple)?", "o": ["racó", "cara", "pera"], "e": "La r inicial sempre és forta: racó, roda, riu. Entre vocals, la r simple és suau: cara."},
      {"q": "En quina paraula hi ha una r forta entre vocals?", "o": ["carro", "caro", "para"], "e": "Entre vocals, el so fort s'escriu rr: carro, parra, morro."},
      {"q": "Quina parella de paraules es distingix només per la r suau o forta?", "o": ["para / parra", "cara / casa", "pera / pena"], "e": "Para (verb parar) i parra (planta de raïm): r suau / rr forta."},
      {"q": "En quina paraula la s sona sonora, com un brunzit d'abella [z]?", "o": ["casa", "passa", "sol"], "e": "La s entre vocals és sonora [z]: casa, rosa. La ss és sorda: passa."},
      {"q": "Quina parella es distingix per la s sonora / s sorda?", "o": ["rosa / rossa", "rosa / roda", "casa / cara"], "e": "Rosa [z] (flor) i rossa [s] (de cabell clar)."},
      {"q": "La z de «zero» o «dotze» en valencià sona...", "o": ["sonora, com la s de «casa»", "com la z castellana de «zapato»", "muda"], "e": "En valencià la z és una s sonora [z], no la z interdental castellana."},
      {"q": "En quina paraula la consonant final no es pronuncia normalment?", "o": ["camp", "cap", "llop"], "e": "Després de m, la p final s'emmudix: camp [kam]. En «cap» i «llop» sí que sona."},
      {"q": "Com es pronuncia normalment la preposició «amb»?", "o": ["[am]", "[amb] amb b forta", "[ab]"], "e": "La b final darrere de m s'emmudix: amb [am], tomb [tom]."},
      {"q": "En quina paraula hi ha un emmudiment de la p?", "o": ["temps", "tapa", "capsa"], "e": "Temps [tems]: la p no es pronuncia. En «tapa» i «capsa» sona."},
      {"q": "En alguns parlars valencians, quina consonant s'emmudix al final dels infinitius com «comptar» o «cantar»?", "o": ["la -r", "la -t", "la -n"], "e": "La -r final s'emmudix en alguns parlars (comptar, senyor, carrer), però sempre s'escriu."},
      {"q": "En «comptar», quina consonant no se sent mai?", "o": ["la p", "la m", "la t"], "e": "Comptar [kon-tar]: la p no es pronuncia, però s'escriu (com en «compte»)."},
      {"q": "Com s'ha d'articular «col·legi»?", "o": ["amb una l doble, allargada [kol-le-dʒi]", "com «colegi» amb una sola l", "com «colleji» amb ll"], "e": "La l·l és una geminada: es pronuncia una l més llarga, repartida entre dues síl·labes."},
      {"q": "Com s'articula «ametla»?", "o": ["amb una l allargada [a-mel-la]", "amb t i l separades molt marcades", "com «ameta»"], "e": "El grup tl de «ametla», «espatla» o «guatla» se sol pronunciar com una l doble."},
      {"q": "En quina paraula hi ha una geminació de m?", "o": ["immens", "imatge", "mama"], "e": "Immens: im-mens, la m sona doble."},
      {"q": "En quina paraula hi ha una geminació de n?", "o": ["ennuvolat", "enutjat", "enyorar"], "e": "En-nu-vo-lat: n doble (en- + nuvolat)."},
      {"q": "Quin grup consonàntic cal articular clarament, sense afegir-hi cap vocal, en «estrella»?", "o": ["str", "tll", "ell"], "e": "Grups consonàntics com str, pl, bl, tr, cr: es-tre-lla."},
      {"q": "En quina pregunta la veu puja al final?", "o": ["Vindràs demà?", "On vas?", "Quan arribes?"], "e": "Preguntes de resposta sí/no: entonació ascendent. Les que comencen per un interrogatiu (on, quan, qui...) solen baixar al final."},
      {"q": "En valencià col·loquial, quina partícula pot introduir una pregunta de sí o no?", "o": ["que: «Que vindràs demà?»", "quin", "com"], "e": "Que expletiu: «Que tens fred?», «Que ha vingut Maria?»."},
      {"q": "Quina d'estes frases és una exclamació?", "o": ["Que bonic és este poble!", "Este poble és bonic.", "Quin poble és?"], "e": "Que + adjectiu...!: entonació exclamativa, emfàtica."},
      {"q": "Quina d'estes expressions s'usa per a exclamar sorpresa?", "o": ["Mare meua!", "Per favor.", "De res."], "e": "Mare meua!, Ostres!, Caram!: exclamacions de sorpresa."},
      {"q": "Com canvia el sentit «Ja ha vingut.» i «Ja ha vingut?»", "o": ["La primera afirma; la segona pregunta, amb entonació ascendent", "Són iguals", "La segona és una ordre"], "e": "L'entonació (i, en l'escriptura, el signe ?) canvia una afirmació en pregunta."},
      {"q": "Quina és la frase exclamativa ben construïda?", "o": ["Quina calor que fa!", "Quina calor fa?", "Calor fa quina!"], "e": "Quin/quina + nom (+ que...)!: Quina calor que fa!"},
      {"q": "En «Quin dia més bonic!», l'entonació...", "o": ["és emfàtica: puja en «bonic» i baixa al final", "puja al final com una pregunta de sí/no", "és plana, sense canvis"], "e": "Entonació exclamativa: èmfasi en la paraula clau."},
      {"q": "En quina paraula la x sona com «tx» ([tʃ]) després de consonant?", "o": ["panxa", "caixa", "taxi"], "e": "Darrere de consonant, la x sona [tʃ]: panxa, planxa, marxa. «Caixa» té [ʃ] i «taxi», [ks]."},
      {"q": "Quina d'estes paraules té el so [ks]?", "o": ["taxi", "xarop", "caixa"], "e": "Taxi, èxit, fax: la x sona [ks]."},
      {"q": "En «examen», com sona la x?", "o": ["[gz], sonora", "[ʃ] com en «caixa»", "com la jota castellana"], "e": "Ex- + vocal: [gz] (examen, exacte, exèrcit)."},
      {"q": "Quina d'estes paraules té el so de la ny?", "o": ["canya", "cana", "cania"], "e": "Ny és una sola consonant palatal: ca-nya."},
      {"q": "Quin signe es posa al final d'una exclamació en valencià?", "o": ["! (només al final)", "¡ ... ! (al principi i al final)", "? (com una pregunta)"], "e": "En valencià el signe d'exclamació només es posa al final."},
      {"q": "Escriu com es pronuncia «quinze anys» unint les paraules (sense espai).", "a": ["quinzanys", "kinzanys"], "e": "S'elidix la -e: quinzanys."},
      {"q": "Escriu la consonant que no es pronuncia en «camp».", "a": ["p"], "e": "La p final després de m."}
    ]
  },
  {
    "id": "32ddfc19-805e-4315-8534-2fdf65376b76", "type": "b1_fon_alfabet", "sort_order": 2,
    "title": "Alfabet i grafies", "name": "Lletres modificades, dígrafs i geminacions",
    "content": "Les lletres simples i modificades, els dígrafs (rr, ll, l·l, ny, gu, qu, ss, tj, tg, tz, ix, ig, tx) i les geminacions en el vocabulari familiar (3.2.1).", "icon": "🔤", "color": "#FFE0B2",
    "exercises": [
      {"q": "Quina d'estes lletres és una lletra modificada (amb un signe que en canvia el so)?", "o": ["ç", "c", "s"], "e": "La ç (ce trencada) sona [s] davant de a, o, u: plaça, caçar, forçós."},
      {"q": "Què és un dígraf?", "o": ["Dues lletres que representen un sol so", "Dues paraules unides", "Una lletra amb accent"], "e": "Dígrafs: rr, ss, ll, ny, qu, gu, ix, ig, tx, tj, tg, tz, l·l."},
      {"q": "Quina d'estes paraules té un dígraf?", "o": ["canya", "cana", "cala"], "e": "Ny és un dígraf: ca-nya."},
      {"q": "Quina d'estes paraules té el dígraf «tz»?", "o": ["dotze", "dos", "dosi"], "e": "Dot-ze, set-ze, tret-ze, organitzar: tz entre vocals."},
      {"q": "Quina d'estes paraules té el dígraf «tg»?", "o": ["metge", "mega", "menja"], "e": "Met-ge, rellot-ge, viat-ge: tg davant de e, i."},
      {"q": "Quina d'estes paraules té el dígraf «tj»?", "o": ["platja", "plaga", "plaja"], "e": "Plat-ja, pit-jor, mit-jà: tj davant de a, o, u."},
      {"q": "En «guerra», què és «gu»?", "o": ["Un dígraf: la u no sona", "Un diftong", "Dues consonants"], "e": "Gu davant de e, i: la u no es pronuncia (guerra, guitarra)."},
      {"q": "En «quatre», la u...", "o": ["sí que sona: forma diftong amb la a", "no sona, és un dígraf", "és una consonant"], "e": "Qu davant de a, o sempre sona [kw]: qua-tre, quan, quota."},
      {"q": "Quantes lletres i quants sons té «carro»?", "o": ["5 lletres i 4 sons", "5 lletres i 5 sons", "4 lletres i 4 sons"], "e": "El dígraf rr fa un sol so: c-a-rr-o."},
      {"q": "Quantes lletres i quants sons té «caixa»?", "o": ["5 lletres i 4 sons", "5 lletres i 5 sons", "4 lletres i 3 sons"], "e": "Ix és un dígraf amb un sol so [ʃ]: c-a-ix-a."},
      {"q": "Com se separa en síl·labes «carro»?", "o": ["car-ro", "ca-rro", "carr-o"], "e": "Els dígrafs rr, ss, l·l, tj, tg, tz i ix se separen: car-ro."},
      {"q": "Com se separa en síl·labes «callar»?", "o": ["ca-llar", "cal-lar", "call-ar"], "e": "La ll no se separa mai: ca-llar."},
      {"q": "Com se separa en síl·labes «canya»?", "o": ["ca-nya", "can-ya", "cany-a"], "e": "La ny no se separa: ca-nya."},
      {"q": "Com se separa en síl·labes «passar»?", "o": ["pas-sar", "pa-ssar", "pass-ar"], "e": "La ss se separa: pas-sar."},
      {"q": "Com se separa en síl·labes «col·legi»?", "o": ["col-le-gi", "co-l·le-gi", "col·l-e-gi"], "e": "La l·l se separa i el punt volat desapareix en partir la paraula: col-le-gi."},
      {"q": "Com se separa en síl·labes «metge»?", "o": ["met-ge", "me-tge", "metg-e"], "e": "Tg se separa: met-ge."},
      {"q": "Com se separa en síl·labes «dotze»?", "o": ["dot-ze", "do-tze", "dotz-e"], "e": "Tz se separa: dot-ze."},
      {"q": "Com se separa en síl·labes «paquet»?", "o": ["pa-quet", "paq-uet", "paqu-et"], "e": "El dígraf qu no se separa: pa-quet."},
      {"q": "Com se separa «guitarra»?", "o": ["gui-tar-ra", "gu-it-ar-ra", "guit-arr-a"], "e": "Gu no se separa; rr sí: gui-tar-ra."},
      {"q": "Quina paraula està ben escrita?", "o": ["col·lecció", "colecció", "col.lecció"], "e": "Col·lecció: la l·l s'escriu amb punt volat (·), no amb un punt baix."},
      {"q": "Quina paraula està ben escrita?", "o": ["il·lusió", "ilusió", "illusió"], "e": "Il·lusió."},
      {"q": "Quina paraula està ben escrita?", "o": ["pel·lícula", "pelícu·la", "pellícula"], "e": "Pel·lícula."},
      {"q": "Quina d'estes paraules té una geminació (dues consonants iguals que sonen)?", "o": ["innecessari", "carro", "passar"], "e": "In-ne-ces-sa-ri: les dues n sonen. En «carro» i «passar», rr i ss són dígrafs d'un sol so."},
      {"q": "Quina d'estes paraules té el dígraf «ig» a final de paraula?", "o": ["maig", "mag", "mai"], "e": "Ig final sona [tʃ]: maig, roig, mig, lleig."},
      {"q": "Quina d'estes paraules té el dígraf «tx»?", "o": ["cotxe", "coixa", "coca"], "e": "Cot-xe, fit-xa, but-xa-ca: tx entre vocals."},
      {"q": "Quantes lletres i quants sons té «llibre»?", "o": ["6 lletres i 5 sons", "6 lletres i 6 sons", "5 lletres i 5 sons"], "e": "Ll és un dígraf: ll-i-b-r-e."},
      {"q": "Quina d'estes paraules NO té cap dígraf?", "o": ["blau", "carrer", "canya"], "e": "Bl és un grup consonàntic, no un dígraf: els dos sons es pronuncien."},
      {"q": "Quina d'estes paraules té un grup consonàntic (dos sons diferents) i no un dígraf?", "o": ["prat", "pell", "pany"], "e": "Pr: se senten la p i la r. Ll i ny són dígrafs."},
      {"q": "En quina d'estes paraules la u de «qu» no es pronuncia?", "o": ["quilo", "quan", "quota"], "e": "Qu davant de e, i: la u no sona (quilo, queixa). Davant de a, o sí: quan, quota."},
      {"q": "Quina d'estes paraules s'escriu amb «qü» (u que sona davant de e o i)?", "o": ["qüestió", "quilo", "queixa"], "e": "Qüestió, freqüent, aqüeducte: la dièresi indica que la u sona."},
      {"q": "Quina d'estes paraules té el dígraf «ss»?", "o": ["massa", "masa", "mas"], "e": "Mas-sa: ss entre vocals (so sord [s])."},
      {"q": "Com se separa en síl·labes «massa»?", "o": ["mas-sa", "ma-ssa", "mass-a"], "e": "La ss se separa: mas-sa."},
      {"q": "Com se separa en síl·labes «caixa»?", "o": ["cai-xa", "ca-ixa", "caix-a"], "e": "El dígraf ix se separa: cai-xa (la i queda amb la vocal anterior)."},
      {"q": "Com se separa en síl·labes «platja»?", "o": ["plat-ja", "pla-tja", "platj-a"], "e": "Tj se separa: plat-ja."},
      {"q": "Quina d'estes paraules té el dígraf «ix»?", "o": ["peix", "pex", "pexi"], "e": "Peix, caixa, baix: ix sona [ʃ]."},
      {"q": "Quina d'estes paraules NO té cap dígraf?", "o": ["pare", "parra", "parell"], "e": "Pare: cada lletra és un so. Parra (rr) i parell (ll) tenen dígrafs."},
      {"q": "Escriu el nombre de sons de «carrer».", "a": ["5", "cinc"], "e": "C-a-rr-e-r: el dígraf rr fa un sol so."},
      {"q": "Separa en síl·labes «canya» (amb guionets).", "a": ["ca-nya"], "e": "Ca-nya."},
      {"q": "Separa en síl·labes «carro» (amb guionets).", "a": ["car-ro"], "e": "Car-ro."},
      {"q": "Escriu el signe que porta la l·l entre les dues l.", "a": ["·", "punt volat", "el punt volat"], "e": "El punt volat (·)."}
    ]
  },
  {
    "id": "6fda17fe-be10-433f-9955-38698e488c6a", "type": "b1_fon_sillaba", "sort_order": 3,
    "title": "Síl·labes, diftongs i hiats", "name": "Tòniques i àtones, agudes, planes, esdrúixoles, diftongs i hiats",
    "content": "Síl·labes tòniques i àtones, agudes, planes i esdrúixoles, diftongs i hiats, separació sil·làbica i els verbs acabats en -iar (3.2.1).", "icon": "🔊", "color": "#C5CAE9",
    "exercises": [
      {"q": "Quina és la síl·laba tònica de «telèfon»?", "o": ["-lè-", "te-", "-fon"], "e": "Te-LÈ-fon: plana (tònica en la penúltima)."},
      {"q": "Quina d'estes paraules és aguda?", "o": ["camió", "camisa", "càmera"], "e": "Ca-mi-Ó: tònica en l'última síl·laba."},
      {"q": "Quina d'estes paraules és plana?", "o": ["examen", "jardí", "música"], "e": "E-XA-men: tònica en la penúltima."},
      {"q": "Quina d'estes paraules és esdrúixola?", "o": ["fàbrica", "fabrica", "fabricà"], "e": "FÀ-bri-ca: tònica en l'antepenúltima."},
      {"q": "«Ramon» és una paraula...", "o": ["aguda", "plana", "esdrúixola"], "e": "Ra-MON: aguda acabada en -on, per això no porta accent."},
      {"q": "«Fenomen» és una paraula...", "o": ["plana", "aguda", "esdrúixola"], "e": "Fe-NO-men: plana acabada en -en, sense accent."},
      {"q": "Quantes síl·labes àtones té «matemàtiques»?", "o": ["4", "5", "1"], "e": "Ma-te-MÀ-ti-ques: 5 síl·labes, una de tònica i 4 d'àtones."},
      {"q": "Quina d'estes paraules té un diftong decreixent (vocal + i/u)?", "o": ["mai", "via", "dia"], "e": "Mai: a + i en la mateixa síl·laba. Diftongs decreixents: ai, ei, oi, ui, au, eu, iu, ou, uu."},
      {"q": "Quina d'estes paraules té un diftong decreixent?", "o": ["peu", "teatre", "poeta"], "e": "Peu: e + u en una síl·laba. Teatre i poeta tenen hiat."},
      {"q": "Quina d'estes paraules té un diftong creixent?", "o": ["quatre", "cuina", "dia"], "e": "Qua-tre: gu/qu + vocal fan diftong creixent (quatre, aigua, guant)."},
      {"q": "Quina d'estes paraules té un hiat (dues vocals en síl·labes diferents)?", "o": ["teatre", "rei", "nou"], "e": "Te-a-tre: e i a en síl·labes diferents."},
      {"q": "Com se separa «poeta»?", "o": ["po-e-ta", "poe-ta", "p-oe-ta"], "e": "Hiat: po-e-ta."},
      {"q": "Com se separa «aigua»?", "o": ["ai-gua", "a-i-gu-a", "aig-ua"], "e": "Ai-gua: diftong decreixent ai i diftong creixent ua."},
      {"q": "Com se separa «noia»?", "o": ["no-ia", "noi-a", "n-oi-a"], "e": "La i entre vocals és consonant i va amb la vocal següent: no-ia, jo-ia, ma-ior."},
      {"q": "Com se separa «creuen»?", "o": ["cre-uen", "creu-en", "cr-eu-en"], "e": "La u entre vocals és consonant: cre-uen."},
      {"q": "Com se separa «veïna»?", "o": ["ve-ï-na", "veï-na", "vei-na"], "e": "La dièresi indica hiat: ve-ï-na."},
      {"q": "Com se separa «cuina»?", "o": ["cui-na", "cu-i-na", "c-ui-na"], "e": "Ui és diftong decreixent: cui-na."},
      {"q": "Com se separa «país»?", "o": ["pa-ís", "pais", "p-aís"], "e": "L'accent indica hiat: pa-ís (aguda)."},
      {"q": "Quantes síl·labes té «estudia» (ell estudia)?", "o": ["4: es-tu-di-a", "3: es-tu-dia", "2: es-tudia"], "e": "En els verbs en -iar, la i i la vocal de la terminació formen hiat: es-tu-di-a."},
      {"q": "Quantes síl·labes té «canvia»?", "o": ["3: can-vi-a", "2: can-via", "4: ca-n-vi-a"], "e": "Can-vi-a: i i a en síl·labes diferents."},
      {"q": "Quina és la pronunciació correcta de «envia» (ell envia una carta)?", "o": ["en-VI-a", "EN-via", "en-vi-A"], "e": "En-VI-a: la tònica és la i, i hi ha hiat."},
      {"q": "Quantes síl·labes té «copie» (que jo copie)?", "o": ["3: co-pi-e", "2: co-pie", "4: c-o-pi-e"], "e": "Co-pi-e: hiat en les formes dels verbs en -iar."},
      {"q": "Quina d'estes paraules és aguda acabada en diftong?", "o": ["fareu", "féreu", "parlàreu"], "e": "Fa-REU: aguda acabada en diftong decreixent -eu, per això no porta accent."},
      {"q": "Quina d'estes paraules és plana?", "o": ["féreu", "fareu", "cantareu"], "e": "FÉ-reu: plana; porta accent perquè acaba en diftong (-eu)."},
      {"q": "«Justícia» és...", "o": ["esdrúixola: jus-tí-ci-a", "plana: jus-tí-cia", "aguda"], "e": "Les paraules acabades en vocal + vocal (-ia, -ie, -io, -ua) es consideren esdrúixoles: jus-TÍ-ci-a, his-TÒ-ri-a."},
      {"q": "Quina parella canvia de significat segons la síl·laba tònica?", "o": ["fabrica / fàbrica", "taula / taules", "casa / cases"], "e": "Fa-BRI-ca (verb) i FÀ-bri-ca (edifici): canviar la tònica canvia la paraula."},
      {"q": "En «ràpidament», on recau l'accent?", "o": ["En «rà-», com en «ràpida»", "En «-ment»", "No en té"], "e": "Els adverbis en -ment conserven l'accent de l'adjectiu: ràpidament, fàcilment."},
      {"q": "Quina d'estes paraules és un monosíl·lab?", "o": ["pa", "pare", "patata"], "e": "Pa: una síl·laba. Els monosíl·labs no porten accent, excepte els diacrítics."},
      {"q": "Quina és la síl·laba tònica de «paraigua»?", "o": ["-rai-", "pa-", "-gua"], "e": "Pa-RAI-gua: plana."},
      {"q": "Quantes síl·labes té «ou»?", "o": ["1", "2", "3"], "e": "Ou: diftong decreixent, una sola síl·laba."},
      {"q": "Quantes síl·labes té «Raül»?", "o": ["2: Ra-ül", "1: Raül", "3: R-a-ül"], "e": "La dièresi marca hiat: Ra-ül."},
      {"q": "Separa en síl·labes «teatre» (amb guionets).", "a": ["te-a-tre"], "e": "Te-a-tre."},
      {"q": "Separa en síl·labes «aigua» (amb guionets).", "a": ["ai-gua"], "e": "Ai-gua."},
      {"q": "Separa en síl·labes «noia» (amb guionets).", "a": ["no-ia"], "e": "No-ia."},
      {"q": "Escriu la síl·laba tònica de «fàbrica».", "a": ["fà", "fà-"], "e": "FÀ-bri-ca."}
    ]
  },
  {
    "id": "b39add6c-4f6f-4daa-a4b4-a5b4665a3f07", "type": "b1_fon_vocals", "sort_order": 4,
    "title": "Les vocals", "name": "Confusions a/e i o/u, la e inicial, alternances i vocals obertes i tancades",
    "content": "Els principals casos de confusió a/e i o/u, la e de les paraules començades per em-, en-, es-, eix-, les alternances e/i i o/u dels verbs irregulars i les vocals obertes i tancades (3.2.1).", "icon": "🅰️", "color": "#FFCCBC",
    "exercises": [
      {"q": "Quina forma és correcta?", "o": ["afaitar", "afeitar", "afetar"], "e": "Afaitar (i afaitada, afaitadora)."},
      {"q": "Quina forma és correcta?", "o": ["llençol", "llançol", "llinçol"], "e": "Llençol."},
      {"q": "Quina forma és correcta?", "o": ["assemblea", "asamblea", "assamblea"], "e": "Assemblea."},
      {"q": "Quina forma és correcta?", "o": ["teranyina", "taranyina", "teranyana"], "e": "Teranyina (la tela de l'aranya)."},
      {"q": "Quina forma és correcta?", "o": ["sergent", "sargent", "sarjent"], "e": "Sergent."},
      {"q": "Quina forma és correcta?", "o": ["taronja", "teronja", "tarunja"], "e": "Taronja."},
      {"q": "Quina forma és correcta?", "o": ["cobert", "cubert", "cubiert"], "e": "Cobert (i cobrir, coberta)."},
      {"q": "Quina forma és correcta?", "o": ["Joan", "Juan", "Jouan"], "e": "Joan s'escriu amb o encara que la o àtona sone [u]."},
      {"q": "Quina forma és correcta?", "o": ["Josep", "Jusep", "Josèp"], "e": "Josep."},
      {"q": "Quina forma és correcta?", "o": ["joguet", "juguet", "joguèt"], "e": "Joguet (i jugar: alternança o/u)."},
      {"q": "Quina forma és correcta?", "o": ["polsera", "pulsera", "pulçera"], "e": "Polsera (de pols, el canell)."},
      {"q": "Quina forma és correcta?", "o": ["escopir", "escupir", "escapir"], "e": "Escopir."},
      {"q": "Quina forma és correcta?", "o": ["sofrir", "sufrir", "sofrar"], "e": "Sofrir (o patir)."},
      {"q": "Quina forma és correcta?", "o": ["suportar", "soportar", "supurtar"], "e": "Suportar s'escriu amb u."},
      {"q": "Quina forma és correcta?", "o": ["tossir", "tussir", "toser"], "e": "Tossir (però jo tus, ell tus)."},
      {"q": "Quina forma és correcta?", "o": ["entendre", "antendre", "intendre"], "e": "Entendre: les paraules usuals començades per en- s'escriuen amb e."},
      {"q": "Quina forma és correcta?", "o": ["estendre", "astendre", "istendre"], "e": "Estendre (la roba)."},
      {"q": "Quina forma és correcta?", "o": ["eixugar", "aixugar", "ixugar"], "e": "Eixugar: eix- a començament de paraula."},
      {"q": "Quina forma és correcta?", "o": ["embastar", "ambastar", "imbastar"], "e": "Embastar (cosir provisionalment amb punts llargs)."},
      {"q": "Quina forma és correcta?", "o": ["escoltar", "ascoltar", "iscoltar"], "e": "Escoltar."},
      {"q": "Quina forma és correcta?", "o": ["enfadar-se", "anfadar-se", "infadar-se"], "e": "Enfadar-se."},
      {"q": "Quina forma és correcta?", "o": ["eixir", "ixir", "aixir"], "e": "L'infinitiu és eixir (eixim, eixiu), però jo isc, tu ixes, ell ix."},
      {"q": "«Jo ___ el diari cada matí.» (llegir)", "o": ["llig", "lleg", "llegix"], "e": "Llegir: jo llig, tu lliges, ell llig, nosaltres llegim. Alternança e/i."},
      {"q": "«Nosaltres ___ el diari cada matí.» (llegir)", "o": ["llegim", "lligim", "lligem"], "e": "Llegim: en posició àtona apareix la e."},
      {"q": "«Tu ___ de casa molt prompte.» (eixir)", "o": ["ixes", "eixes", "ixeixes"], "e": "Eixir: isc, ixes, ix, eixim, eixiu, ixen."},
      {"q": "«Nosaltres ___ a les huit.» (eixir)", "o": ["eixim", "ixim", "eixem"], "e": "Eixim: en posició àtona apareix eix-."},
      {"q": "«Jo no ___ vindre demà.» (poder)", "o": ["puc", "poc", "pot"], "e": "Poder: jo puc, tu pots, ell pot. Alternança o/u."},
      {"q": "«Que jo ___ o no, ho faré igual.» (voler)", "o": ["vullga", "volga", "vulga"], "e": "Voler: que jo vullga (subjuntiu); jo volia (imperfet): alternança u/o."},
      {"q": "«Quan era xicotet, ___ ser bomber.» (voler)", "o": ["volia", "vullia", "vulia"], "e": "Volia: en posició àtona, o."},
      {"q": "«Ma mare ___ els pantalons.» (cosir)", "o": ["cus", "cos", "cusix"], "e": "Cosir: jo cus, tu cuses, ell cus, nosaltres cosim."},
      {"q": "«Ell ___ taronges a l'hort.» (collir)", "o": ["cull", "coll", "cullix"], "e": "Collir: jo cull, ell cull, nosaltres collim."},
      {"q": "Quin accent porta «perquè»?", "o": ["obert: è", "tancat: é", "no en porta"], "e": "Perquè, què: e oberta (è)."},
      {"q": "Quin accent porta «també»?", "o": ["tancat: é", "obert: è", "no en porta"], "e": "També, només, vosté: e tancada (é)."},
      {"q": "Quin accent porta «cançó»?", "o": ["tancat: ó", "obert: ò", "no en porta"], "e": "Cançó, camió, avió: o tancada (ó)."},
      {"q": "Quin accent porta «història»?", "o": ["obert: ò", "tancat: ó", "no en porta"], "e": "Història, memòria, dòlar: o oberta (ò)."},
      {"q": "Quin accent porta la a tònica (sofà, àvia)?", "o": ["sempre greu: à", "sempre agut: á", "depén de la paraula"], "e": "La a sempre porta accent greu (à); la i i la u, sempre agut (í, ú)."},
      {"q": "Quina parella es distingix per la o oberta / o tancada?", "o": ["sòl (terra) / sol (astre)", "dona / dones", "porta / portes"], "e": "Sòl, amb o oberta, és el terra; sol, l'astre."},
      {"q": "Escriu la forma correcta: «Jo ___ el llibre» (llegir, present).", "a": ["llig"], "e": "Llig."},
      {"q": "Escriu el verb correcte: ___ la roba al sol (eixugar o aixugar).", "a": ["eixugar"], "e": "Eixugar."},
      {"q": "Escriu bé el nom: ___ (Joan o Juan).", "a": ["Joan"], "e": "Joan."}
    ]
  },
  {
    "id": "a2de932f-ba79-43c3-88f4-0432422a5ff2", "type": "b1_fon_accentuacio", "sort_order": 5,
    "title": "Accentuació, dièresi i guionet", "name": "Regles generals de l'accent, accents diacrítics, dièresi i guionet",
    "content": "Normes generals de l'accentuació (agudes, planes i esdrúixoles), accent obert i tancat, accents diacrítics, normes bàsiques de la dièresi i del guionet (3.2.1).", "icon": "✍️", "color": "#FFCDD2",
    "exercises": [
      {"q": "Quines paraules agudes porten accent?", "o": ["Les acabades en vocal, vocal + s, -en i -in", "Totes les agudes", "Només les acabades en consonant"], "e": "Agudes: camió, francés, també, entén, camí. Ramon i fareu no en porten."},
      {"q": "Quines paraules planes porten accent?", "o": ["Les que NO acaben en vocal, vocal + s, -en ni -in", "Totes les planes", "Les acabades en vocal"], "e": "Planes: plàstic, difícil, féreu. Però fenomen, examen, taula: sense accent."},
      {"q": "Quines paraules esdrúixoles porten accent?", "o": ["Totes", "Cap", "Només les acabades en -a"], "e": "Totes les esdrúixoles s'accentuen: fàbrica, música, justícia."},
      {"q": "Quina forma és correcta?", "o": ["Ramon", "Ramón", "Ràmon"], "e": "Aguda acabada en -on: no porta accent."},
      {"q": "Quina forma és correcta?", "o": ["fenomen", "fenómen", "fenòmen"], "e": "Plana acabada en -en: no porta accent."},
      {"q": "Quina forma és correcta?", "o": ["plàstic", "plastic", "plàstíc"], "e": "Plana acabada en -c: porta accent."},
      {"q": "Quina forma és correcta? (vosaltres, futur de fer)", "o": ["fareu", "faréu", "fàreu"], "e": "Fa-REU: aguda acabada en diftong; no porta accent."},
      {"q": "Quina forma és correcta? (vosaltres, passat simple de fer)", "o": ["féreu", "fereu", "fèreu"], "e": "FÉ-reu: plana acabada en diftong (-eu): porta accent."},
      {"q": "Quina forma és correcta?", "o": ["justícia", "justicia", "jústicia"], "e": "Jus-TÍ-ci-a: es considera esdrúixola i porta accent."},
      {"q": "Quina forma és correcta?", "o": ["examen", "exàmen", "exámen"], "e": "Plana acabada en -en: sense accent. Però plural: exàmens (acaba en -ens)."},
      {"q": "Quin plural és correcte?", "o": ["exàmens", "examens", "exámens"], "e": "E-XÀ-mens: plana acabada en -ens, que no és cap de les terminacions sense accent."},
      {"q": "Quina forma és correcta?", "o": ["camins", "camíns", "càmins"], "e": "Ca-MINS: aguda acabada en -ins (no en -in): sense accent. Però camí sí."},
      {"q": "Quina forma és correcta?", "o": ["difícil", "dificil", "difìcil"], "e": "Plana acabada en -l: porta accent agut en la i."},
      {"q": "Quina forma és correcta?", "o": ["anglés", "angles", "ànglés"], "e": "Aguda acabada en vocal + s: porta accent (en valencià, anglés, francés)."},
      {"q": "Quina forma és correcta?", "o": ["fàcilment", "facilment", "fácilment"], "e": "Els adverbis en -ment conserven l'accent de l'adjectiu: fàcil → fàcilment."},
      {"q": "«Ell ___ dos germans.» (tindre)", "o": ["té", "te", "tè"], "e": "Té (verb) porta accent diacrític; te (pronom o infusió) no."},
      {"q": "«Ma germana ___ metgessa.»", "o": ["és", "es", "ès"], "e": "És (verb ser) porta accent; es (pronom) no."},
      {"q": "«Vull ___ pa, per favor.»", "o": ["més", "mes", "mès"], "e": "Més (quantitat) porta accent; mes (part de l'any) no."},
      {"q": "«___, vindré a la festa.»", "o": ["Sí", "Si", "Sì"], "e": "Sí (afirmació) porta accent; si (condició) no."},
      {"q": "«No ___ on he deixat les claus.» (saber)", "o": ["sé", "se", "sè"], "e": "Sé (verb saber) porta accent; se (pronom) no."},
      {"q": "«Ho has fet molt ___.»", "o": ["bé", "be", "bè"], "e": "Bé (adverbi) porta accent; be (corder o lletra) no."},
      {"q": "«Ha fet la volta al ___.»", "o": ["món", "mon", "mòn"], "e": "Món (el planeta) porta accent; mon (possessiu) no."},
      {"q": "«M'he trencat la ___.»", "o": ["mà", "ma", "má"], "e": "Mà (part del cos) porta accent; ma (possessiu) no."},
      {"q": "«Tens un ___ en la jaqueta.»", "o": ["pèl", "pel", "pél"], "e": "Pèl (cabell) porta accent; pel (contracció per + el) no."},
      {"q": "Quina paraula necessita dièresi?", "o": ["veïna", "veí", "veu"], "e": "Ve-ï-na: la dièresi marca que i i a no formen diftong. Veí ja porta accent."},
      {"q": "Quina forma és correcta?", "o": ["raïm", "raím", "raim"], "e": "Ra-ïm: hiat marcat amb dièresi (és aguda acabada en -m: no porta accent)."},
      {"q": "Quina forma és correcta?", "o": ["països", "paísos", "paisos"], "e": "Pa-ï-sos: el singular país porta accent; en el plural la i deixa de ser tònica i cal dièresi."},
      {"q": "Quina forma és correcta?", "o": ["pingüí", "pinguí", "pingui"], "e": "Güi: la dièresi indica que la u es pronuncia."},
      {"q": "Quina forma és correcta?", "o": ["aigües", "aigues", "aigúes"], "e": "Aigua → aigües: la u es pronuncia davant de e."},
      {"q": "Quina forma és correcta?", "o": ["egoisme", "egoïsme", "egóisme"], "e": "No es posa dièresi en les terminacions -isme i -ista: egoisme, egoista."},
      {"q": "Quina forma és correcta?", "o": ["traduir", "traduïr", "tradüir"], "e": "No porten dièresi l'infinitiu, el gerundi, el futur i el condicional: traduir, traduint, traduiré. Sí: traduïa, traduït."},
      {"q": "Quina forma és correcta?", "o": ["reunió", "reünió", "rëunió"], "e": "No es posa dièresi després de prefix: re-unió."},
      {"q": "Quina forma és correcta?", "o": ["vint-i-cinc", "vinticinc", "vint i cinc"], "e": "Desenes i unitats amb guionet; entre desenes i unitats, -i-: vint-i-cinc, trenta-dos."},
      {"q": "Com s'escriu 230?", "o": ["dos-cents trenta", "doscents-trenta", "dos cents trenta"], "e": "Unitats i centenes amb guionet (dos-cents), però centenes i desenes separades."},
      {"q": "Quina forma és correcta?", "o": ["dona-li", "donali", "dona li"], "e": "Els pronoms febles darrere del verb s'unixen amb guionet: dona-li, fes-ho, porta-ho."},
      {"q": "Quina forma és correcta?", "o": ["nord-americà", "nordamericà", "nord americà"], "e": "Compostos amb punts cardinals: nord-americà, sud-est."},
      {"q": "Quina forma és correcta?", "o": ["para-sol", "parasol", "para sol"], "e": "Para-sol, gira-sol, para-xocs: guionet quan la primera part acaba en vocal i la segona comença per r, s o x."},
      {"q": "Quina forma és correcta?", "o": ["paraigua", "para-igua", "para igua"], "e": "Paraigua s'escriu junt."},
      {"q": "Quina forma és correcta?", "o": ["expresident", "ex-president", "ex president"], "e": "El prefix ex- s'escriu junt: expresident."},
      {"q": "Escriu amb l'accent correcte: musica.", "a": ["música"], "e": "Esdrúixola: música."},
      {"q": "Escriu amb l'accent correcte: frances (home de França).", "a": ["francés", "francès"], "e": "Francés: aguda acabada en vocal + s."},
      {"q": "Escriu amb la dièresi correcta: veina.", "a": ["veïna"], "e": "Veïna."},
      {"q": "Escriu el número 45 en lletres.", "a": ["quaranta-cinc"], "e": "Quaranta-cinc."}
    ]
  },
  {
    "id": "05b13ba1-42eb-432d-af83-a16cac7346ab", "type": "b1_fon_apostrofacio", "sort_order": 6,
    "title": "Apostrofació i contracció", "name": "Apòstrof de l'article, de la preposició de i dels pronoms febles",
    "content": "Regles generals d'apostrofació dels articles el/la i de la preposició de, l'apòstrof en els pronoms febles units al verb, combinacions bàsiques de pronoms i contraccions (3.2.1).", "icon": "🔗", "color": "#D7CCC8",
    "exercises": [
      {"q": "Quina forma és correcta?", "o": ["l'ase", "el ase", "la ase"], "e": "L'article el s'apostrofa davant de vocal: l'ase."},
      {"q": "Quina forma és correcta?", "o": ["l'era", "la era", "le era"], "e": "La s'apostrofa davant de vocal: l'era."},
      {"q": "Quina forma és correcta?", "o": ["l'illa", "la illa", "lilla"], "e": "L'illa: la i és tònica."},
      {"q": "Quina forma és correcta?", "o": ["l'home", "el home", "lhome"], "e": "Davant de h muda s'apostrofa: l'home, l'hora."},
      {"q": "Quina forma és correcta?", "o": ["l'ungla", "la ungla", "lungla"], "e": "L'ungla: u tònica."},
      {"q": "Quina forma és correcta?", "o": ["la infermera", "l'infermera", "l'infirmera"], "e": "La no s'apostrofa davant de i o u àtones (amb h o sense): la infermera."},
      {"q": "Quina forma és correcta?", "o": ["la universitat", "l'universitat", "la' universitat"], "e": "U àtona: la universitat."},
      {"q": "Quina forma és correcta?", "o": ["la història", "l'història", "la' història"], "e": "Hi- àtona: la història. Però l'hora (o tònica)."},
      {"q": "Quina forma és correcta?", "o": ["l'altra setmana", "la altra setmana", "l altra setmana"], "e": "La s'apostrofa davant de vocal tònica o àtona que no siga i/u: l'altra, l'escola, l'amiga."},
      {"q": "Quina forma és correcta?", "o": ["la indústria", "l'indústria", "la' indústria"], "e": "I àtona: la indústria. Però d'indústria, perquè la preposició de sí que s'apostrofa."},
      {"q": "Quina forma és correcta?", "o": ["el iogurt", "l'iogurt", "le iogurt"], "e": "No s'apostrofa davant de i o u semiconsonants: el iogurt, la iaia."},
      {"q": "Quina forma és correcta? (l'hora)", "o": ["És la una.", "És l'una.", "És la' una."], "e": "Amb l'hora no s'apostrofa: la una."},
      {"q": "Quina forma és correcta?", "o": ["un got d'aigua", "un got de aigua", "un got d aigua"], "e": "De s'apostrofa davant de vocal o h muda: d'aigua, d'home."},
      {"q": "Quina forma és correcta?", "o": ["el gos d'Isabel", "el gos de Isabel", "el gos dIsabel"], "e": "De s'apostrofa sempre davant de vocal, encara que siga i o u àtones: d'Isabel, d'una."},
      {"q": "Quina forma és correcta?", "o": ["la casa de l'amo", "la casa del amo", "la casa d'el amo"], "e": "De + l'amo: no es contrau quan l'article està apostrofat."},
      {"q": "Quina forma és correcta?", "o": ["Vaig a l'escola.", "Vaig al escola.", "Vaig a la escola."], "e": "A + l'escola: no hi ha contracció."},
      {"q": "Quina forma és correcta?", "o": ["Vaig al mercat.", "Vaig a el mercat.", "Vaig a'l mercat."], "e": "A + el = al."},
      {"q": "Quina forma és correcta?", "o": ["Passem pel parc.", "Passem per el parc.", "Passem per'l parc."], "e": "Per + el = pel; per + els = pels."},
      {"q": "Quina forma és correcta?", "o": ["el llibre dels xiquets", "el llibre de els xiquets", "el llibre d'els xiquets"], "e": "De + els = dels."},
      {"q": "Quina forma és correcta?", "o": ["M'agrada molt.", "Me agrada molt.", "Em agrada molt."], "e": "Em davant de verb que comença per vocal: m'agrada."},
      {"q": "Quina forma és correcta?", "o": ["T'estime.", "Te estime.", "Et estime."], "e": "Et → t' davant de vocal: t'estime."},
      {"q": "Quina forma és correcta?", "o": ["L'he vist.", "El he vist.", "Lo he vist."], "e": "El → l' davant de vocal o h: l'he vist."},
      {"q": "Quina forma és correcta?", "o": ["N'hi ha molts.", "En hi ha molts.", "Ni ha molts."], "e": "En + hi davant de ha: n'hi ha."},
      {"q": "Quina forma és correcta?", "o": ["Ens agrada.", "'Ns agrada.", "Ens'agrada."], "e": "Ens no s'apostrofa davant del verb: ens agrada, ens ajuda."},
      {"q": "Quina forma és correcta?", "o": ["Compra'l.", "Compra-el.", "Compral."], "e": "Darrere de verb acabat en vocal, el → 'l: compra'l."},
      {"q": "Quina forma és correcta?", "o": ["Mira'ns.", "Mira-ens.", "Mira'ens."], "e": "Ens → 'ns darrere de verb acabat en vocal: mira'ns."},
      {"q": "Quina forma és correcta?", "o": ["Porta'm al metge.", "Porta-em al metge.", "Portam al metge."], "e": "Em → 'm darrere de verb acabat en vocal: porta'm."},
      {"q": "Quina forma és correcta?", "o": ["Fes-ho.", "Fes'ho.", "Fesho."], "e": "Ho sempre va amb guionet darrere del verb: fes-ho, compra-ho."},
      {"q": "Quina forma és correcta?", "o": ["Obri-la.", "Obri'la.", "Obrila."], "e": "La darrere del verb va amb guionet, no s'apostrofa mai: obri-la."},
      {"q": "Quina forma és correcta?", "o": ["Me'l dones?", "Em el dones?", "M'el dones?"], "e": "Em + el davant de verb → me'l."},
      {"q": "Quina forma és correcta?", "o": ["Se'n va.", "S'en va.", "Es en va."], "e": "Es + en → se'n: se'n va, me'n vaig, te'n vas."},
      {"q": "Quina forma és correcta?", "o": ["M'ho ha dit.", "Me ho ha dit.", "Em ho ha dit."], "e": "Em + ho → m'ho (davant de verb)."},
      {"q": "Quina forma és correcta?", "o": ["Dona-me'l.", "Dona'm el.", "Dona-m'el."], "e": "Darrere del verb: dona-me'l, porta-te'l."},
      {"q": "Quina forma és correcta?", "o": ["Te'n recordes?", "T'en recordes?", "Et en recordes?"], "e": "Et + en → te'n."},
      {"q": "Escriu amb apòstrof: de + aigua.", "a": ["d'aigua"], "e": "D'aigua."},
      {"q": "Escriu la forma correcta: la + universitat.", "a": ["la universitat"], "e": "La universitat (u àtona: no s'apostrofa)."},
      {"q": "Escriu la contracció de per + els.", "a": ["pels"], "e": "Pels."},
      {"q": "Escriu el verb amb el pronom: compra + el.", "a": ["compra'l"], "e": "Compra'l."}
    ]
  },
  {
    "id": "f482c820-b45e-4661-bd1f-af514dcaad47", "type": "b1_fon_oclusives", "sort_order": 7,
    "title": "Oclusives i labiodentals", "name": "Oclusives finals, cu/qu, xc/cc, b/v i la -v- de l'imperfet",
    "content": "Alternances de les oclusives finals en la flexió i la derivació, paraules acabades en oclusiva, els grups cu/qu, les grafies xc i cc, la b i la v, i la -v- de l'imperfet de la primera conjugació (3.2.1).", "icon": "🅱️", "color": "#C8E6C9",
    "exercises": [
      {"q": "Com s'escriu el masculí de «lloba»?", "o": ["llop", "llob", "llopp"], "e": "Llop / lloba: a final de paraula s'escriu p, però en el femení sona b."},
      {"q": "Com s'escriu el masculí de «cunyada»?", "o": ["cunyat", "cunyad", "cuñat"], "e": "Cunyat / cunyada: t final, d en el femení."},
      {"q": "Com s'escriu el masculí de «salada»?", "o": ["salat", "salad", "salatt"], "e": "Salat / salada."},
      {"q": "Com s'escriu el masculí de «verda»?", "o": ["verd", "vert", "berd"], "e": "Verd / verda: la d del femení es manté en el masculí."},
      {"q": "Com s'escriu el masculí de «torta» (no recta)?", "o": ["tort", "tord", "tortt"], "e": "Tort / torta."},
      {"q": "Com s'escriu el femení de «groc»?", "o": ["groga", "groca", "grogua"], "e": "Groc / groga / grocs / grogues."},
      {"q": "Com s'escriu el femení plural de «llarg»?", "o": ["llargues", "llarges", "llargas"], "e": "Llarg / llarga / llargs / llargues: davant de e cal escriure gu."},
      {"q": "Com s'escriu el femení plural de «amic»?", "o": ["amigues", "amiges", "amicues"], "e": "Amic / amiga / amics / amigues."},
      {"q": "«Ell ___ moltes cartes.» (rebre)", "o": ["rep", "reb", "rebe"], "e": "Rebre: ell rep, nosaltres rebem. A final de paraula, p."},
      {"q": "«Nosaltres ___ el paquet demà.» (rebre)", "o": ["rebem", "repem", "rebim"], "e": "Rebem: entre vocals sona i s'escriu b."},
      {"q": "Quina forma és correcta?", "o": ["àrab", "àrap", "àrabe"], "e": "Àrab (àrabs, àraba)."},
      {"q": "Quina forma és correcta?", "o": ["covard", "covart", "cobard"], "e": "Covard (covarda): amb v i d final."},
      {"q": "Quina forma és correcta?", "o": ["sang", "sanc", "sangre"], "e": "Sang: g final (sanguini, sagnar)."},
      {"q": "Quina forma és correcta?", "o": ["fred", "fret", "fredd"], "e": "Fred (freda, fredor)."},
      {"q": "Quina forma és correcta?", "o": ["sord", "sort", "sorth"], "e": "Sord / sorda. Sort és una altra paraula (la bona sort)."},
      {"q": "Quina forma és correcta?", "o": ["tímid", "tímit", "tímide"], "e": "Tímid (tímida): els adjectius en -id s'escriuen amb d."},
      {"q": "Quina forma és correcta?", "o": ["amarg", "amarc", "amargue"], "e": "Amarg / amarga / amargs / amargues."},
      {"q": "Quina forma és correcta?", "o": ["quatre", "cuatre", "quatra"], "e": "Qua- en quatre, quan, qualitat, quadre."},
      {"q": "Quina forma és correcta?", "o": ["quota", "cuota", "qüota"], "e": "Quota (la quota del gimnàs): qu davant de o."},
      {"q": "Quina forma és correcta?", "o": ["cua", "qua", "cüa"], "e": "Cua (del gat, de la fila): c + u vocal + a."},
      {"q": "Quina forma és correcta?", "o": ["evacuar", "evaquar", "evaqüar"], "e": "Evacuar: la u és vocal (e-va-cu-ar)."},
      {"q": "Quina forma és correcta?", "o": ["adequar", "adecuar", "adequär"], "e": "Adequar: qu + a forma diftong (a-de-quar)."},
      {"q": "Quina forma és correcta?", "o": ["excés", "acés", "eccés"], "e": "Excés (ex + cés). Accés és l'entrada a un lloc."},
      {"q": "«L'___ al parc és lliure.»", "o": ["accés", "excés", "exés"], "e": "Accés: entrada. Accedir."},
      {"q": "Quina forma és correcta?", "o": ["excursió", "escursió", "eccursió"], "e": "Excursió."},
      {"q": "Quina forma és correcta?", "o": ["excel·lent", "escel·lent", "eccel·lent"], "e": "Excel·lent: xc i l·l."},
      {"q": "Quina forma és correcta?", "o": ["accident", "axident", "acsident"], "e": "Accident: cc [ks]."},
      {"q": "Quina forma és correcta?", "o": ["acceptar", "aceptar", "axeptar"], "e": "Acceptar: cc."},
      {"q": "Quina forma és correcta?", "o": ["excepte", "eccepte", "esepte"], "e": "Excepte, excepció: xc."},
      {"q": "Quina forma de l'imperfet és correcta?", "o": ["trobava", "trobaba", "trobàva"], "e": "En l'imperfet de la primera conjugació, -v-: trobava, trobaves, trobava."},
      {"q": "«Nosaltres ___ a l'escola junts.» (anar, imperfet)", "o": ["anàvem", "anàbem", "anavem"], "e": "Anàvem: amb v i accent (esdrúixola)."},
      {"q": "«Vosaltres ___ molt de pressa.» (parlar, imperfet)", "o": ["parlàveu", "parlàbeu", "parlaveu"], "e": "Parlàveu: esdrúixola, porta accent."},
      {"q": "Quina forma és correcta?", "o": ["advocat", "abogat", "avogat"], "e": "Advocat (amb dv)."},
      {"q": "Quina forma és correcta?", "o": ["avorrit", "aburrit", "abvorrit"], "e": "Avorrit, avorrir: amb v."},
      {"q": "Quina forma és correcta?", "o": ["govern", "gobern", "gubern"], "e": "Govern, governar: amb v."},
      {"q": "Quina forma és correcta? (tastar o comprovar alguna cosa)", "o": ["provar", "probar", "prouar"], "e": "Provar: amb v. La prova."},
      {"q": "Quina forma és correcta?", "o": ["berenar", "verenar", "merendar"], "e": "Berenar, amb b."},
      {"q": "Escriu el femení de «groc».", "a": ["groga"], "e": "Groga."},
      {"q": "Escriu el masculí de «verda».", "a": ["verd"], "e": "Verd."},
      {"q": "Escriu l'imperfet de «cantar» per a «nosaltres».", "a": ["cantàvem"], "e": "Cantàvem."},
      {"q": "Escriu el femení plural de «llarg».", "a": ["llargues"], "e": "Llargues."}
    ]
  },
  {
    "id": "37c00f03-8d75-42ea-baa1-89cd4efd3442", "type": "b1_fon_alveolars", "sort_order": 8,
    "title": "Consonants alveolars", "name": "c/ç, -ança/-ença, x/cc, -esa/-essa, s/ss i -sc-",
    "content": "La variació c/ç, les paraules en -ança i -ença, el so [ks] i [gz], les paraules en -esa i -essa, els gentilicis en -és, els derivats de les agudes en vocal + s i el grup -sc- (3.2.1).", "icon": "🐍", "color": "#FFF59D",
    "exercises": [
      {"q": "Quin és el plural de «pinça»?", "o": ["pinces", "pinçes", "pinsses"], "e": "Davant de e i i s'escriu c: pinça → pinces."},
      {"q": "Quin és el plural de «plaça»?", "o": ["places", "plaçes", "plasses"], "e": "Plaça → places."},
      {"q": "Quin és el plural de «braç»?", "o": ["braços", "bracos", "brasos"], "e": "Davant de o s'escriu ç: braç → braços."},
      {"q": "Quin és el participi de «véncer»?", "o": ["vençut", "vencut", "venssut"], "e": "Véncer → vençut: davant de u, ç."},
      {"q": "«Nosaltres ___ la porta.» (forçar, present)", "o": ["forcem", "forçem", "forssem"], "e": "Forçar → forcem: davant de e, c."},
      {"q": "«Nosaltres ___ a les huit.» (començar, present)", "o": ["comencem", "començem", "comensem"], "e": "Començar → comencem."},
      {"q": "Quin és el femení de «dolç»?", "o": ["dolça", "dolsa", "dolca"], "e": "Dolç / dolça / dolços / dolces."},
      {"q": "Quina forma és correcta?", "o": ["esperança", "esperanza", "esperansa"], "e": "Esperança: sufix -ança."},
      {"q": "Quina forma és correcta?", "o": ["confiança", "confiansa", "confiánça"], "e": "Confiança."},
      {"q": "Quina forma és correcta?", "o": ["mudança", "mudansa", "mudanza"], "e": "Mudança."},
      {"q": "Quina forma és correcta?", "o": ["complaença", "complaensa", "complaència"], "e": "Complaença: sufix -ença."},
      {"q": "Quina forma és correcta?", "o": ["creença", "creència", "creensa"], "e": "Creença."},
      {"q": "Quina forma és correcta?", "o": ["paciència", "paciença", "pacienssa"], "e": "Paciència, ciència, experiència: -ència (amb accent)."},
      {"q": "Quina forma és correcta?", "o": ["diferència", "diferença", "diferénsia"], "e": "Diferència (però diferent)."},
      {"q": "Quina forma és correcta? (impost que es paga)", "o": ["taxa", "tassa", "tacsa"], "e": "Taxa [ks]: impost. Tassa: recipient per a beure."},
      {"q": "Quina forma és correcta?", "o": ["èxit", "écsit", "èccit"], "e": "Èxit: x [gz]."},
      {"q": "Quina forma és correcta?", "o": ["exèrcit", "egzèrcit", "exèrsit"], "e": "Exèrcit: x [gz], c davant de i."},
      {"q": "Quina forma és correcta?", "o": ["acció", "axió", "accsió"], "e": "Acció: cc [ks] davant de i."},
      {"q": "Quina forma és correcta?", "o": ["direcció", "direxió", "direció"], "e": "Direcció (i director): cc."},
      {"q": "Quina forma és correcta?", "o": ["exacte", "eczacte", "exaccte"], "e": "Exacte: x [gz]."},
      {"q": "Quina forma és correcta?", "o": ["bellesa", "bellessa", "belleza"], "e": "Noms abstractes derivats d'adjectius: -esa (bellesa, tristesa, timidesa, riquesa)."},
      {"q": "Quina forma és correcta?", "o": ["timidesa", "timidessa", "timidez"], "e": "Timidesa (de tímid)."},
      {"q": "Quina forma és correcta?", "o": ["marquesa", "marquessa", "marqueza"], "e": "Marquesa, princesa: -esa."},
      {"q": "Quina forma és correcta?", "o": ["alcaldessa", "alcaldesa", "alcaldeza"], "e": "Alcaldessa, metgessa, comtessa: -essa."},
      {"q": "Quina forma és correcta?", "o": ["metgessa", "metgesa", "metjessa"], "e": "Metgessa."},
      {"q": "Quina forma és correcta?", "o": ["comtessa", "comtesa", "condesa"], "e": "Comtessa."},
      {"q": "Quin és el femení de «xinés»?", "o": ["xinesa", "xinessa", "xineza"], "e": "Xinés / xinesa / xinesos / xineses: s sonora."},
      {"q": "Quin és el plural masculí de «xinés»?", "o": ["xinesos", "xinessos", "xinés"], "e": "Xinesos."},
      {"q": "Quin és el plural masculí de «anglés»?", "o": ["anglesos", "anglessos", "anglés"], "e": "Anglés / anglesa / anglesos / angleses."},
      {"q": "Quin és el femení de «gos»?", "o": ["gossa", "gosa", "gossia"], "e": "Gos → gossa (s sorda: ss)."},
      {"q": "Quin és el plural de «pas»?", "o": ["passos", "pasos", "pàssos"], "e": "Pas → passos."},
      {"q": "Quin és el femení de «calorós»?", "o": ["calorosa", "calorossa", "caloroza"], "e": "Calorós → calorosa (s sonora: s)."},
      {"q": "Quin és el plural de «mes»?", "o": ["mesos", "messos", "meses"], "e": "Mes → mesos."},
      {"q": "Quin és el femení de «gras»?", "o": ["grassa", "grasa", "graça"], "e": "Gras → grassa."},
      {"q": "Quin és el plural de «interés»?", "o": ["interessos", "interesos", "interessus"], "e": "Interés → interessos."},
      {"q": "Quina forma és correcta?", "o": ["piscina", "pissina", "picina"], "e": "Piscina: grup -sc-."},
      {"q": "Quina forma és correcta?", "o": ["escena", "esena", "essena"], "e": "Escena: -sc-."},
      {"q": "Quina forma és correcta?", "o": ["ascensor", "asensor", "assensor"], "e": "Ascensor (i ascens): -sc-."},
      {"q": "Quina forma és correcta?", "o": ["adolescent", "adolesent", "adolessent"], "e": "Adolescent: -sc-."},
      {"q": "Escriu el plural de «plaça».", "a": ["places"], "e": "Places."},
      {"q": "Escriu el femení de «metge».", "a": ["metgessa"], "e": "Metgessa."},
      {"q": "Escriu el femení de «gos».", "a": ["gossa"], "e": "Gossa."},
      {"q": "Escriu el nom abstracte de «trist».", "a": ["tristesa", "tristor"], "e": "Tristesa (o tristor)."}
    ]
  },
  {
    "id": "ce18cc3f-74e3-44b7-9613-2853cb3b3290", "type": "b1_fon_palatals", "sort_order": 9,
    "title": "Consonants palatals", "name": "g/j, tg/tj, ig, x/tx i les seues alternances",
    "content": "Les palatals g, j, tg, tj i ig, les excepcions de la j davant de e i i, la norma de la x i la tx, la variació en la flexió (boja/boges, platja/platges), els derivats de -tx i -ig i la pronunciació de la x (3.2.1).", "icon": "🌊", "color": "#B3E5FC",
    "exercises": [
      {"q": "Quina forma és correcta?", "o": ["gener", "jener", "gené"], "e": "Davant de e i i, normalment g: gener, gent, girar."},
      {"q": "Quina forma és correcta?", "o": ["jove", "gove", "jobe"], "e": "Davant de a, o, u, sempre j: jove, juny, jardí."},
      {"q": "Quina forma és correcta?", "o": ["objecte", "obgecte", "objete"], "e": "Excepció: j davant de e en objecte, projecte, subjecte, trajecte."},
      {"q": "Quina forma és correcta?", "o": ["Jesús", "Gesús", "Jesus"], "e": "Excepció: Jesús, jersei, injecció."},
      {"q": "Quina forma és correcta?", "o": ["projecte", "progecte", "projete"], "e": "Projecte: j davant de e (excepció)."},
      {"q": "Quina forma és correcta?", "o": ["injecció", "ingecció", "injeció"], "e": "Injecció: j (excepció) i cc."},
      {"q": "Quina forma és correcta?", "o": ["platja", "plaja", "platga"], "e": "Entre vocals, tj davant de a, o, u: platja."},
      {"q": "Quin és el plural de «platja»?", "o": ["platges", "platjes", "plages"], "e": "Davant de e: tg. Platja → platges."},
      {"q": "Quin és el plural de «mitja» (peça de roba)?", "o": ["mitges", "mitjes", "miges"], "e": "Mitja → mitges."},
      {"q": "Quin és el femení plural de «boig»?", "o": ["boges", "bojes", "botges"], "e": "Boig / boja / bojos / boges."},
      {"q": "Quin és el masculí plural de «boig»?", "o": ["bojos", "boigs", "bogos"], "e": "Bojos: davant de o, j."},
      {"q": "Quin és el plural de «pluja»?", "o": ["pluges", "plujes", "pluetges"], "e": "Pluja → pluges."},
      {"q": "Quin és el plural de «taronja»?", "o": ["taronges", "taronjes", "tarongues"], "e": "Taronja → taronges."},
      {"q": "«Nosaltres ___ a les dues.» (menjar, present)", "o": ["mengem", "menjem", "mengim"], "e": "Menjar → mengem: davant de e, g."},
      {"q": "«Nosaltres ___ per l'escala.» (pujar, present)", "o": ["pugem", "pujem", "putgem"], "e": "Pujar → pugem."},
      {"q": "Quina forma és correcta?", "o": ["metge", "metje", "mege"], "e": "Tg davant de e: metge, rellotge, viatge, fetge, jutge."},
      {"q": "Quina forma és correcta?", "o": ["pitjor", "pitgor", "pijor"], "e": "Tj davant de o: pitjor."},
      {"q": "Quina forma és correcta?", "o": ["raig", "raitx", "rach"], "e": "A final de paraula, darrere de vocal, -ig: raig, fuig, roig, mig, maig."},
      {"q": "Quina forma és correcta? (ell se'n va corrent)", "o": ["fuig", "fuitx", "fugi"], "e": "Fugir: ell fuig."},
      {"q": "Quin és el femení de «lleig»?", "o": ["lletja", "lleja", "lleitja"], "e": "Lleig → lletja (tj, perquè sona [dʒ])."},
      {"q": "Quin és el nom derivat de «roig» que indica el color?", "o": ["rojor", "rotjor", "roigor"], "e": "Roig → roja, rojor (j)."},
      {"q": "Quin és el verb derivat de «desig»?", "o": ["desitjar", "desijar", "desigar"], "e": "Desig → desitjar."},
      {"q": "Quin és el verb derivat de «passeig»?", "o": ["passejar", "passetjar", "passeigar"], "e": "Passeig → passejar."},
      {"q": "Quina forma és correcta?", "o": ["planxa", "plantxa", "plancha"], "e": "Darrere de consonant, x: planxa, panxa, marxa, punxa."},
      {"q": "Quina forma és correcta? (targeta per a anotar dades o peça d'un joc)", "o": ["fitxa", "ficha", "fitja"], "e": "Entre vocals, tx: fitxa, cotxe, butxaca, motxilla."},
      {"q": "Quina forma és correcta?", "o": ["xarop", "txarop", "charop"], "e": "A començament de paraula, x: xarop, xica, xocolate, xufa."},
      {"q": "Quina forma és correcta?", "o": ["motxilla", "moxilla", "mochilla"], "e": "Motxilla: tx entre vocals."},
      {"q": "Quina forma és correcta?", "o": ["marxar", "martxar", "marchar"], "e": "Marxar: x darrere de r."},
      {"q": "Quin és el plural de «despatx»?", "o": ["despatxos", "despatxs", "despaxos"], "e": "Despatx → despatxos."},
      {"q": "Quin és el verb derivat de «escabetx»?", "o": ["escabetxar", "escabexar", "escabetjar"], "e": "Escabetx → escabetxar."},
      {"q": "Quin és l'adjectiu derivat de «capritx»?", "o": ["capritxós", "caprixós", "capritjós"], "e": "Capritx → capritxós."},
      {"q": "En valencià, com es pronuncia normalment la x inicial de «xic»?", "o": ["[tʃ], com «tx»", "[ks]", "com la jota castellana"], "e": "La x inicial se sol pronunciar africada [tʃ]: xic, xarop."},
      {"q": "Com es pronuncia la x de «Xàtiva»?", "o": ["[ʃ], com la x de «caixa»", "[ks], com en «taxi»", "[gz], com en «examen»"], "e": "En el nom de Xàtiva es manté el so fricatiu [ʃ], com en «caixa» o «peix»."},
      {"q": "Com es pronuncia la x de «panxa»?", "o": ["[tʃ], com «tx»", "[ks]", "[ʃ] suau"], "e": "Darrere de consonant, la x sona [tʃ]: panxa, planxa."},
      {"q": "Escriu el plural de «platja».", "a": ["platges"], "e": "Platges."},
      {"q": "Escriu el femení de «lleig».", "a": ["lletja"], "e": "Lletja."},
      {"q": "Escriu la forma correcta: ___ (fitxa o ficha).", "a": ["fitxa"], "e": "Fitxa."},
      {"q": "Escriu el plural de «taronja».", "a": ["taronges"], "e": "Taronges."}
    ]
  },
  {
    "id": "7baaddb7-7eaf-4f14-bfc3-b2e2e1c04964", "type": "b1_fon_laterals_h", "sort_order": 10,
    "title": "Laterals, nasals, ròtiques i la h", "name": "l·l, tl/tll, m davant de b/p/m, -ny, r/rr i la h",
    "content": "La l·l en al·l-, col·l-, il·l-, -el·la, -il·la; les grafies tl/tll; la m davant de b, p, m; la -ny final; la r i la rr i la -r final; la h inicial i intercalada i el verb haver (3.2.1).", "icon": "🌙", "color": "#D1C4E9",
    "exercises": [
      {"q": "Quina forma és correcta?", "o": ["al·lèrgia", "alèrgia", "allèrgia"], "e": "Al·l-: al·lèrgia, al·lusió."},
      {"q": "Quina forma és correcta?", "o": ["col·laborar", "colaborar", "collaborar"], "e": "Col·l-: col·laborar, col·legi, col·lecció, col·locar."},
      {"q": "Quina forma és correcta?", "o": ["il·luminar", "iluminar", "illuminar"], "e": "Il·l-: il·luminar, il·lusió, il·legal, il·lustrar."},
      {"q": "Quina forma és correcta?", "o": ["il·legal", "ilegal", "illegal"], "e": "Il·legal (in- + legal)."},
      {"q": "Quina forma és correcta?", "o": ["novel·la", "novela", "novella"], "e": "-el·la: novel·la, cel·la, parcel·la."},
      {"q": "Quina forma és correcta?", "o": ["pastil·la", "pastilla", "pastila"], "e": "-il·la: pastil·la, vil·la."},
      {"q": "Quina forma és correcta?", "o": ["intel·ligent", "inteligent", "intelligent"], "e": "Intel·ligent, excel·lent, pel·lícula, tranquil·la."},
      {"q": "Quina forma és correcta?", "o": ["tranquil·la", "tranquila", "tranquilla"], "e": "Tranquil → tranquil·la."},
      {"q": "Quina forma és correcta?", "o": ["ametla", "ametl·la", "ametlla"], "e": "Ametla (i ametler): grup tl."},
      {"q": "Quina forma és correcta?", "o": ["ratlla", "ralla", "rat·lla"], "e": "Ratlla (i ratllar): grup tll."},
      {"q": "Quina forma és correcta?", "o": ["espatla", "espal·la", "espalla"], "e": "Espatla (o muscle): grup tl."},
      {"q": "Quina forma és correcta?", "o": ["bitllet", "billet", "bit·let"], "e": "Bitllet: grup tll."},
      {"q": "Quina forma és correcta?", "o": ["vetlar", "vel·lar", "vellar"], "e": "Vetlar (passar la nit desperts), la vetla."},
      {"q": "Quina forma és correcta?", "o": ["ambulància", "anbulància", "amvulància"], "e": "Davant de b i p s'escriu m: ambulància, temps, camp."},
      {"q": "Quina forma és correcta?", "o": ["combinar", "conbinar", "convinar"], "e": "Combinar: m davant de b."},
      {"q": "Quina forma és correcta?", "o": ["immens", "inmens", "imens"], "e": "Immens: in- davant de m es fa im-: immens, immediat, immigrant."},
      {"q": "Quina forma és correcta?", "o": ["immediat", "inmediat", "imediat"], "e": "Immediat."},
      {"q": "Quina forma és correcta?", "o": ["enviar", "emviar", "embiar"], "e": "Davant de v s'escriu n: enviar, convidar, invent, canviar."},
      {"q": "Quina forma és correcta?", "o": ["convidar", "comvidar", "combidar"], "e": "Convidar: n davant de v."},
      {"q": "Quina forma és correcta?", "o": ["umbracle", "unbracle", "umbracl·le"], "e": "Umbracle (cobert per a fer ombra): m davant de b."},
      {"q": "Quina forma és correcta?", "o": ["disseny", "diseny", "dissenyo"], "e": "Disseny (dissenyar): -ny final."},
      {"q": "Quina forma és correcta? (mà tancada)", "o": ["puny", "punyo", "puñ"], "e": "Puny: -ny final. Tindre el cor en un puny."},
      {"q": "Quina forma és correcta? (inflor al cap per un colp)", "o": ["bony", "bonyo", "boni"], "e": "Bony: -ny final."},
      {"q": "Quina forma és correcta? (queixa de dolor)", "o": ["plany", "planyo", "plañ"], "e": "Plany (planyer-se)."},
      {"q": "En quina paraula la r és forta encara que s'escriu amb una sola r?", "o": ["Enric", "cara", "pera"], "e": "Després de n, l o s, la r és forta però s'escriu simple: Enric, honra, Israel."},
      {"q": "Quina forma és correcta?", "o": ["Enric", "Enrric", "Henric"], "e": "Enric: r simple darrere de n."},
      {"q": "Quina forma és correcta?", "o": ["honra", "honrra", "onra"], "e": "Honra: r simple darrere de n, i h inicial."},
      {"q": "Quina forma és correcta?", "o": ["rosa", "rrosa", "hrosa"], "e": "A començament de paraula, sempre r simple (que sona forta)."},
      {"q": "Quina forma és correcta?", "o": ["carrers", "carres", "carrés"], "e": "La -r final de «carrer» s'escriu sempre, encara que en alguns parlars no se senta, i es manté en el plural."},
      {"q": "Quina forma és correcta?", "o": ["senyors", "senyós", "senyoros"], "e": "Senyor → senyors."},
      {"q": "Quina forma és correcta?", "o": ["harmonia", "armonia", "harmonía"], "e": "Harmonia: amb h inicial."},
      {"q": "Quina forma és correcta?", "o": ["hui", "ui", "huy"], "e": "Hui s'escriu amb h. També huit."},
      {"q": "Quina forma és correcta?", "o": ["ahir", "aïr", "air"], "e": "Ahir: h intercalada."},
      {"q": "Quina forma és correcta?", "o": ["vehicle", "veicle", "vehícle"], "e": "Vehicle: h intercalada."},
      {"q": "Quina forma és correcta?", "o": ["prohibit", "proibit", "prohibít"], "e": "Prohibit, prohibir: h intercalada."},
      {"q": "Quina forma és correcta?", "o": ["vehement", "veement", "vehemènt"], "e": "Vehement: h intercalada."},
      {"q": "Quina forma és correcta?", "o": ["ou", "hou", "huevo"], "e": "Ou s'escriu sense h (cast. «huevo»). També os, orfe, ós, ermita, orxata."},
      {"q": "Quina forma és correcta?", "o": ["orxata", "horxata", "horchata"], "e": "Orxata: sense h."},
      {"q": "Quina forma és correcta?", "o": ["M'ha agradat molt.", "M'a agradat molt.", "Ma agradat molt."], "e": "En els temps compostos, el verb haver: ha agradat, has vist, he anat."},
      {"q": "Quina forma és correcta?", "o": ["Ha anat a València.", "A anat a València.", "Ha anat ha València."], "e": "Ha (verb haver) amb h; a (preposició) sense h."},
      {"q": "Quina forma és correcta?", "o": ["Hi ha molta gent.", "I ha molta gent.", "Hi a molta gent."], "e": "Hi ha: pronom hi + verb haver."},
      {"q": "Escriu amb la grafia correcta: «colegi».", "a": ["col·legi"], "e": "Col·legi."},
      {"q": "Escriu amb la grafia correcta: «inmens».", "a": ["immens"], "e": "Immens."},
      {"q": "Escriu amb la grafia correcta: «air» (el dia anterior a hui).", "a": ["ahir"], "e": "Ahir."},
      {"q": "Escriu amb la grafia correcta: «diseño» en valencià.", "a": ["disseny"], "e": "Disseny."}
    ]
  },
  {
    "id": "b556615d-c4c5-4daa-b132-d8a87ed6a179", "type": "b1_fon_majuscules", "sort_order": 11,
    "title": "Majúscules i minúscules", "name": "Normes bàsiques de l'ús de les majúscules",
    "content": "Quan s'escriu majúscula (inici de text i de frase, noms propis, festes, institucions, títols, sigles i tractaments abreujats) i quan minúscula (dies, mesos, llengües, gentilicis, càrrecs i noms comuns geogràfics) (3.2.1).", "icon": "🔠", "color": "#FFE082",
    "exercises": [
      {"q": "Quina frase està ben escrita?", "o": ["Ens veiem el dilluns 3 de març.", "Ens veiem el Dilluns 3 de Març.", "Ens veiem el dilluns 3 de Març."], "e": "Els dies de la setmana i els mesos s'escriuen amb minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["A la primavera fa bon temps.", "A la Primavera fa bon temps.", "a la primavera fa bon temps."], "e": "Les estacions, amb minúscula; però la frase comença amb majúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Parle valencià i anglés.", "Parle Valencià i Anglés.", "Parle valencià i Anglés."], "e": "Els noms de llengües s'escriuen amb minúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["Els valencians celebren el 9 d'Octubre.", "Els Valencians celebren el 9 d'octubre.", "Els valencians celebren el 9 d'octubre."], "e": "Els gentilicis, amb minúscula; les dates que donen nom a una festa o a un fet històric, amb majúscula: el 9 d'Octubre."},
      {"q": "Quina frase està ben escrita?", "o": ["Per Nadal anirem a Morella.", "Per nadal anirem a Morella.", "Per Nadal anirem a morella."], "e": "Les festes (Nadal, Pasqua, Falles) i els noms de lloc, amb majúscula."},
      {"q": "Quina frase està ben escrita?", "o": ["El riu Túria passa per València.", "El Riu Túria passa per València.", "El riu túria passa per València."], "e": "El nom comú (riu, serra, mar) amb minúscula; el nom propi, amb majúscula."},
      {"q": "Quina és correcta?", "o": ["la serra de Mariola", "la Serra de Mariola", "la serra de mariola"], "e": "Nom comú geogràfic en minúscula: la serra de Mariola, el cap de la Nau."},
      {"q": "Quina és correcta?", "o": ["el mar Mediterrani", "el Mar Mediterrani", "el mar mediterrani"], "e": "El mar Mediterrani."},
      {"q": "Quina és correcta?", "o": ["Visc en el carrer de la Pau.", "Visc en el Carrer de la Pau.", "Visc en el carrer de la pau."], "e": "Carrer, plaça, avinguda amb minúscula; el nom propi, amb majúscula."},
      {"q": "Quina és correcta?", "o": ["la Generalitat Valenciana", "la generalitat valenciana", "la Generalitat valenciana"], "e": "Els noms d'institucions porten majúscula en totes les paraules significatives."},
      {"q": "Quina és correcta?", "o": ["la Universitat de València", "la universitat de València", "la Universitat de valència"], "e": "Nom propi d'institució: la Universitat de València."},
      {"q": "Quina és correcta?", "o": ["L'alcaldessa ha inaugurat la biblioteca.", "L'Alcaldessa ha inaugurat la biblioteca.", "l'alcaldessa ha inaugurat la Biblioteca."], "e": "Els càrrecs (alcaldessa, president, rei) s'escriuen amb minúscula."},
      {"q": "Quina és correcta?", "o": ["el president de la Generalitat", "el President de la Generalitat", "el president de la generalitat"], "e": "Càrrec en minúscula; institució en majúscula."},
      {"q": "Quina és correcta?", "o": ["Sr. Martí", "sr. Martí", "Sr. martí"], "e": "Els tractaments abreujats van amb majúscula: Sr., Sra., Dr. Escrits sencers, amb minúscula: el senyor Martí."},
      {"q": "Quina és correcta?", "o": ["el senyor Martí", "el Senyor Martí", "El senyor martí"], "e": "Tractament no abreujat, amb minúscula."},
      {"q": "Quin és el títol ben escrit?", "o": ["He llegit «La plaça del Diamant».", "He llegit «La Plaça Del Diamant».", "He llegit «la plaça del diamant»."], "e": "En els títols d'obres, majúscula només en la primera paraula i en els noms propis."},
      {"q": "Quina és correcta?", "o": ["Viu al nord de Castelló.", "Viu al Nord de Castelló.", "Viu al nord de castelló."], "e": "Els punts cardinals, amb minúscula, excepte quan formen part d'un nom propi (Amèrica del Nord)."},
      {"q": "Quina és correcta?", "o": ["Ha viatjat a Amèrica del Nord.", "Ha viatjat a Amèrica del nord.", "Ha viatjat a amèrica del Nord."], "e": "Part d'un nom propi: Amèrica del Nord."},
      {"q": "Quina és correcta?", "o": ["la UE (Unió Europea)", "la ue (unió europea)", "la Ue (Unió europea)"], "e": "Les sigles, en majúscules."},
      {"q": "Després d'un signe d'interrogació que acaba una frase, la paraula següent...", "o": ["va amb majúscula", "va amb minúscula", "va entre parèntesis"], "e": "«On vas? Vinc amb tu.»: si ? o ! tanca la frase, majúscula."},
      {"q": "Després de dos punts, normalment s'escriu...", "o": ["minúscula, excepte si és una cita o el començament d'una carta", "sempre majúscula", "sempre un número"], "e": "«Necessitem tres coses: farina, ous i sucre.» Però va amb majúscula si és una cita literal (Va dir: «Vinc demà.») o després de la salutació d'una carta."},
      {"q": "Quina és correcta?", "o": ["Me'n vaig a les Falles de València.", "Me'n vaig a les falles de València.", "Me'n vaig a les Falles de valència."], "e": "El nom de la festa, en majúscula: les Falles. (El monument faller és «una falla», en minúscula.)"},
      {"q": "Quina és correcta?", "o": ["La falla del meu barri és molt gran.", "La Falla del meu barri és molt gran.", "la falla del meu barri és molt gran."], "e": "El monument (una falla) és un nom comú: minúscula."},
      {"q": "Quina és correcta?", "o": ["el segle XV", "el segle xv", "el Segle XV"], "e": "Els segles, en xifres romanes majúscules; «segle», en minúscula."},
      {"q": "Quina és correcta?", "o": ["la Comunitat Valenciana", "la comunitat valenciana", "la comunitat Valenciana"], "e": "Nom propi del territori: la Comunitat Valenciana."},
      {"q": "Quina és correcta? (el planeta)", "o": ["La Terra gira al voltant del Sol.", "La terra gira al voltant del sol.", "la Terra gira al voltant del Sol."], "e": "Els noms d'astres i planetes com a noms propis: la Terra, el Sol, la Lluna. «Terra» com a sòl: minúscula."},
      {"q": "Quina és correcta?", "o": ["Plantem tomaques a la terra de l'hort.", "Plantem tomaques a la Terra de l'hort.", "Plantem Tomaques a la terra de l'hort."], "e": "Terra com a sòl és un nom comú: minúscula."},
      {"q": "Quina és correcta?", "o": ["el rei Jaume I", "el Rei Jaume I", "el rei jaume I"], "e": "El càrrec (rei) en minúscula; el nom propi, amb majúscula."},
      {"q": "Quina és correcta?", "o": ["l'Edat Mitjana", "l'edat mitjana", "l'Edat mitjana"], "e": "Els noms de períodes històrics porten majúscula: l'Edat Mitjana, el Renaixement."},
      {"q": "Quina és correcta?", "o": ["el Museu de Belles Arts", "el museu de belles arts", "el Museu de belles arts"], "e": "Nom propi d'un museu o d'un edifici: majúscula en les paraules significatives."},
      {"q": "Quina és correcta?", "o": ["Han aprovat la llei en les Corts Valencianes.", "Han aprovat la Llei en les corts valencianes.", "Han aprovat la llei en les corts Valencianes."], "e": "Institució: les Corts Valencianes. «Llei», nom comú, en minúscula."},
      {"q": "Quina és correcta?", "o": ["Hem anat a l'ajuntament a fer un tràmit.", "Hem anat a l'Ajuntament a Fer un tràmit.", "hem anat a l'ajuntament a fer un tràmit."], "e": "Quan es referix a l'edifici, nom comú (l'ajuntament); quan és la institució amb el nom (l'Ajuntament de Gandia), majúscula."},
      {"q": "Quina és correcta?", "o": ["la Mare de Déu dels Desemparats", "la mare de déu dels desemparats", "la Mare de déu dels desemparats"], "e": "Noms religiosos propis amb majúscula."},
      {"q": "Com s'escriu el nom del mes dins d'una frase?", "o": ["gener", "Gener", "GENER"], "e": "Els mesos, amb minúscula."},
      {"q": "Com s'escriu el nom de la festa dins d'una frase?", "o": ["Nadal", "nadal", "NADAL"], "e": "Les festes, amb majúscula."},
      {"q": "Com s'escriu el nom de la llengua dins d'una frase?", "o": ["valencià", "Valencià", "VALENCIÀ"], "e": "Les llengües, amb minúscula."},
      {"q": "Escriu l'abreviatura de «senyora».", "a": ["Sra.", "Sra"], "e": "Sra."}
    ]
  },
  {
    "id": "5c7449fa-9786-46ef-ad08-f264cf30ec59", "type": "b1_fon_puntuacio", "sort_order": 12,
    "title": "Signes de puntuació", "name": "Punt i coma, dos punts, punts suspensius i parèntesis",
    "content": "L'ús del punt i coma, dels dos punts, dels punts suspensius i dels parèntesis (3.2.1).", "icon": "❗", "color": "#F8BBD0",
    "exercises": [
      {"q": "Quina frase usa bé el punt i coma?", "o": ["A Pau li agrada el futbol, el bàsquet i el tennis; a Marta, la música i el cine.", "A Pau; li agrada el futbol.", "A Pau li agrada; el futbol, el bàsquet i el tennis."], "e": "El punt i coma separa parts d'una enumeració que ja tenen comes dins."},
      {"q": "Per a què servix el punt i coma?", "o": ["Per a separar elements llargs o que ja tenen comes, amb una pausa més forta que la coma", "Per a acabar un text", "Per a fer una pregunta"], "e": "Pausa més llarga que la coma i més curta que el punt."},
      {"q": "Quina frase usa bé el punt i coma davant d'un connector?", "o": ["Vam estudiar molt durant tot el trimestre; tanmateix, no vam aprovar.", "Vam estudiar; molt.", "Vam; estudiar molt."], "e": "Davant de connectors com tanmateix, per tant, no obstant això, en frases llargues."},
      {"q": "Quina frase usa bé els dos punts?", "o": ["Necessitem tres coses: farina, ous i sucre.", "Necessitem: tres coses farina, ous i sucre.", "Necessitem tres: coses farina, ous i sucre."], "e": "Els dos punts introduïxen una enumeració anunciada."},
      {"q": "Quina frase usa bé els dos punts per a una cita?", "o": ["Ma mare va dir: «Torna prompte.»", "Ma mare: va dir «Torna prompte.»", "Ma mare va: dir «Torna prompte.»"], "e": "Davant d'una cita literal, dos punts i cometes."},
      {"q": "Com comença correctament una carta formal?", "o": ["Benvolguda senyora:", "Benvolguda senyora;", "Benvolguda: senyora"], "e": "Després de la salutació d'una carta, dos punts (o coma en cartes personals)."},
      {"q": "Quina frase usa els dos punts per a introduir una explicació o una causa?", "o": ["No vindrà a la festa: està malalt.", "No: vindrà a la festa.", "No vindrà: a la festa."], "e": "Els dos punts poden introduir una conseqüència, una causa o una conclusió."},
      {"q": "Quina frase usa bé els punts suspensius?", "o": ["Al mercat hi havia pomes, peres, taronges...", "Al mercat hi havia... pomes, peres.", "Al mercat... hi... havia."], "e": "Indiquen una enumeració inacabada."},
      {"q": "Quina és la forma correcta?", "o": ["pomes, peres, taronges, etc.", "pomes, peres, taronges, etc...", "pomes, peres, taronges... etc."], "e": "No es posen punts suspensius després de «etc.»: tots dos indiquen el mateix."},
      {"q": "Quants punts tenen els punts suspensius?", "o": ["Sempre tres", "Dos o tres", "Tants com vulgues"], "e": "Sempre tres (...)."},
      {"q": "Quina frase expressa dubte o suspens amb punts suspensius?", "o": ["Doncs... no sé què dir-te.", "Doncs no sé què dir-te.", "Doncs, no sé què dir-te."], "e": "Els punts suspensius poden indicar dubte, vacil·lació o suspens."},
      {"q": "Quina frase deixa una frase feta inacabada amb punts suspensius?", "o": ["Ja saps el que diuen: a qui matina...", "Ja saps el que diuen: a qui matina Déu l'ajuda.", "Ja saps el que diuen."], "e": "Quan el lector pot completar una frase coneguda, es tallen amb punts suspensius."},
      {"q": "Què indiquen els punts suspensius entre parèntesis (...) dins d'una cita?", "o": ["Que s'ha omés un tros del text", "Que l'autor dubtava", "Que la cita és falsa"], "e": "(...) o [...]: s'ha suprimit una part del text citat."},
      {"q": "Quina frase usa bé els parèntesis?", "o": ["La Dama d'Elx (segle V aC) és una escultura ibera.", "La Dama (d'Elx segle V aC) és una escultura ibera.", "(La Dama d'Elx) segle V aC és una escultura ibera."], "e": "Els parèntesis tanquen informació complementària: dates, aclariments."},
      {"q": "Quina frase usa bé els parèntesis per a una sigla?", "o": ["Estudia a la Universitat de València (UV).", "Estudia a la (Universitat de València) UV.", "Estudia a la Universitat (de València UV)."], "e": "Els parèntesis poden contindre la sigla o el seu desenvolupament."},
      {"q": "On va el punt final quan la frase acaba amb un parèntesi?", "o": ["Darrere del parèntesi: ...(UV).", "Davant del parèntesi: ....(UV)", "No cal punt"], "e": "Si el parèntesi forma part de la frase, el punt va darrere: Estudia a la UV (Universitat de València)."},
      {"q": "Quina frase usa els parèntesis per a una aclaració?", "o": ["El meu cosí (el fill de la tia Remei) viu a Lió.", "El meu cosí el fill (de la tia Remei) viu a Lió.", "El meu (cosí el fill de la tia Remei viu a Lió)."], "e": "Aclaració que es podria llevar sense que la frase perdera el sentit."},
      {"q": "Quins signes es poden usar en lloc dels parèntesis per a una aclaració?", "o": ["Els guions llargs o les comes", "Els punts suspensius", "Els signes d'interrogació"], "e": "El meu cosí —el fill de la tia Remei— viu a Lió. O amb comes."},
      {"q": "Quines cometes es recomanen en valencià per a citar?", "o": ["Les baixes o angulars: « »", "Només les simples: ' '", "Cap: no se'n posen"], "e": "Cometes baixes « »; dins d'elles, altes “ ” i després simples ‘ ’."},
      {"q": "Quina frase està ben puntuada?", "o": ["Volíem anar a la platja; però, com que plovia, ens vam quedar a casa.", "Volíem anar; a la platja però com que plovia ens vam quedar a casa.", "Volíem: anar a la platja però com que plovia, ens vam quedar a casa."], "e": "Punt i coma davant de «però» en una frase llarga amb comes."},
      {"q": "Quin signe falta? «Hi ha dues opcions ___ quedar-nos o eixir.»", "o": ["dos punts (:)", "punt i coma (;)", "punts suspensius (...)"], "e": "Dos punts per a anunciar les opcions."},
      {"q": "Quin signe falta? «Si vens a la festa, porta beguda ___ si no vens, avisa'm.»", "o": ["punt i coma (;)", "dos punts (:)", "parèntesis"], "e": "Punt i coma entre dues parts llargues i relacionades."},
      {"q": "Quina frase usa bé els dos punts per a una conclusió?", "o": ["Ha plogut tota la setmana: el pantà està ple.", "Ha plogut: tota la setmana el pantà està ple.", "Ha: plogut tota la setmana."], "e": "Els dos punts poden introduir la conseqüència del que s'ha dit."},
      {"q": "Quina frase usa bé els dos punts després d'una expressió com «per exemple»?", "o": ["Hi ha moltes festes valencianes, per exemple: les Falles, les Fogueres i la Magdalena.", "Hi ha moltes: festes valencianes, per exemple les Falles.", "Hi ha moltes festes valencianes per: exemple les Falles."], "e": "Per exemple, és a dir, com ara... poden anar seguits de dos punts davant d'una enumeració."},
      {"q": "Quina frase usa bé el punt i coma en una llista de dades?", "o": ["Han vingut Joan, de Gandia; Marta, d'Alcoi; i Pere, de Xàtiva.", "Han vingut Joan; de Gandia, Marta; d'Alcoi.", "Han vingut; Joan, de Gandia, Marta, d'Alcoi."], "e": "Cada element ja té una coma: se separen amb punt i coma."},
      {"q": "Quina frase usa bé els punts suspensius per a expressar sorpresa?", "o": ["I quan vaig obrir la porta... estaven tots allí!", "I quan vaig... obrir la porta estaven tots allí!", "I quan vaig obrir la porta estaven... tots... allí."], "e": "Els punts suspensius creen expectació abans d'una sorpresa."},
      {"q": "Quina frase usa bé els parèntesis per a una forma alternativa?", "o": ["Es busca dependent(a) amb experiència.", "Es busca (dependent) a amb experiència.", "Es busca dependent a(mb experiència)."], "e": "En anuncis i formularis, els parèntesis poden indicar la forma femenina."},
      {"q": "Quina frase usa bé els parèntesis per a una dada numèrica?", "o": ["L'Albufera (unes 21.000 hectàrees de parc natural) està al sud de València.", "L'Albufera unes (21.000 hectàrees) de parc natural està al sud de València.", "(L'Albufera unes 21.000 hectàrees) de parc natural."], "e": "Dades complementàries entre parèntesis."},
      {"q": "Quina frase NO necessita punt i coma?", "o": ["Vine prompte.", "Ell estudia medicina; ella, dret.", "Uns es queden; els altres se'n van."], "e": "Una frase curta i simple no necessita punt i coma."},
      {"q": "Quin signe falta? «El metge li ho va dir clar ___ ha de deixar de fumar.»", "o": ["dos punts (:)", "punt i coma (;)", "parèntesis"], "e": "Els dos punts introduïxen el contingut del que s'ha dit."},
      {"q": "Quin signe es posa després de «Benvolgut senyor» en una carta formal?", "o": ["dos punts (:)", "punt i coma (;)", "punts suspensius (...)"], "e": "Dos punts."},
      {"q": "Quin signe indica que una enumeració continua, sense escriure «etc.»?", "o": ["els punts suspensius (...)", "el punt i coma (;)", "els dos punts (:)"], "e": "Punts suspensius."},
      {"q": "Quina frase usa bé els parèntesis per a indicar l'any?", "o": ["Joanot Martorell (segle XV) va escriure el «Tirant».", "Joanot (Martorell segle XV) va escriure el «Tirant».", "Joanot Martorell segle (XV) va escriure el «Tirant»."], "e": "Dades complementàries, com dates o segles, entre parèntesis."},
      {"q": "Quina frase usa bé els dos punts davant d'un exemple?", "o": ["Tinc una idea: anem a la platja.", "Tinc: una idea anem a la platja.", "Tinc una: idea anem a la platja."], "e": "Els dos punts introduïxen allò que s'anuncia."},
      {"q": "Quina és correcta?", "o": ["Va dir: «No vindré.»", "Va dir; «No vindré.»", "Va dir... «No vindré.»"], "e": "Dos punts davant d'una cita en estil directe."},
      {"q": "Quina frase NO necessita dos punts?", "o": ["Demà anirem a la platja.", "Porta això: crema, tovallola i aigua.", "Ho tinc clar: no hi vaig."], "e": "Una frase simple sense enumeració, cita ni explicació no necessita dos punts."},
      {"q": "Quina frase usa massa punts suspensius?", "o": ["Doncs... jo... no... sé...", "Doncs... no sé.", "Hi havia pomes, peres..."], "e": "Cal usar els punts suspensius amb moderació."},
      {"q": "Quina és correcta?", "o": ["Tinc tres germans (Pau, Marta i Joan).", "Tinc tres germans (Pau, Marta i Joan.)", "Tinc tres germans. (Pau, Marta i Joan)"], "e": "El punt de la frase va fora del parèntesi."},
      {"q": "Escriu quants punts tenen sempre els punts suspensius (en número).", "a": ["3", "tres"], "e": "Tres."}
    ]
  }
]$data$::jsonb) AS t(
  id uuid, type text, sort_order smallint, title text, name text,
  content text, icon text, color text, exercises jsonb
);

INSERT INTO public.resources (id, name, type, category, content, difficulty, xp_earned, sort_order, metadata)
SELECT id, name, type, 'fonetica_ortografia', content, 'intermedi', 15, sort_order,
       jsonb_build_object('icon', icon, 'color', color, 'section_name', title)
FROM practice_catalog
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  category = EXCLUDED.category,
  content = EXCLUDED.content,
  difficulty = EXCLUDED.difficulty,
  xp_earned = EXCLUDED.xp_earned,
  sort_order = EXCLUDED.sort_order,
  metadata = EXCLUDED.metadata;

DELETE FROM public.practice_exercises e
USING practice_catalog c
WHERE e.resource_id = c.id AND e.level = 'B1';

INSERT INTO public.practice_exercises (resource_id, level, position, kind, prompt, options, answers, explanation)
SELECT c.id, 'B1', x.ord,
       CASE WHEN x.e ? 'a' THEN 'fill' ELSE 'choice' END,
       x.e->>'q',
       CASE WHEN x.e ? 'o' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'o')) END,
       CASE WHEN x.e ? 'a' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'a')) ELSE ARRAY[x.e->'o'->>0] END,
       x.e->>'e'
FROM practice_catalog c
CROSS JOIN LATERAL jsonb_array_elements(c.exercises) WITH ORDINALITY AS x(e, ord);

DROP TABLE practice_catalog;
