-- Vocabulari bàsic de l'A2 (Quadern A2 de la JQCV, 4.3 Lèxic i semàntica).
-- El contingut «Vocabulari» de 20260930110000 tenia 10 preguntes de tots els
-- àmbits; es dividix en un contingut per àmbit del temari, perquè la pantalla
-- mostra tots els exercicis d'un contingut alhora. El primer àmbit conserva
-- l'id del recurs original i les seues preguntes es reparteixen entre els àmbits.
-- Formació de paraules i Sinònims passen darrere (sort_order 9 i 10).
-- Tornar a aplicar el fitxer no duplica res: es reescriuen els exercicis A2.

CREATE TEMP TABLE practice_catalog AS
SELECT * FROM jsonb_to_recordset($data$[
  {
    "id": "be7ce637-a745-4ec9-8d00-502b96b164a1", "type": "vocabulari", "sort_order": 1,
    "title": "Família, escola i vivenda", "name": "Família, noms, estudis, professions i vivenda",
    "content": "La família, els noms propis, els estudis i l'escola, les professions i els oficis i la vivenda.", "icon": "🏠", "color": "#FFCCBC",
    "exercises": [
      {"q": "Com es diu la mare de ta mare?", "o": ["l'àvia", "la tia", "la cosina"], "e": "La mare del pare o de la mare és l'àvia."},
      {"q": "Com es diu el pare de ton pare?", "o": ["l'avi", "el tio", "el nebot"], "e": "El pare del pare o de la mare és l'avi."},
      {"q": "Els pares del teu pare i de la teua mare són els teus...", "o": ["avis", "oncles", "sogres"], "e": "L'avi i l'àvia: els avis."},
      {"q": "El germà de ta mare és...", "o": ["el tio", "el cosí", "el nebot"], "e": "El germà del pare o de la mare és el tio (o l'oncle)."},
      {"q": "La filla del teu tio és...", "o": ["la cosina", "la neboda", "la néta"], "e": "Els fills dels tios són els cosins."},
      {"q": "El fill del teu germà és...", "o": ["el nebot", "el cosí", "el nét"], "e": "El fill d'un germà o d'una germana és el nebot."},
      {"q": "La filla del teu fill és...", "o": ["la néta", "la neboda", "la cosina"], "e": "La filla d'un fill o d'una filla és la néta."},
      {"q": "Els fills dels mateixos pares són...", "o": ["germans", "cosins", "nebots"], "e": "Germans: tenen el mateix pare i la mateixa mare."},
      {"q": "El marit de ta germana és...", "o": ["el cunyat", "el sogre", "el gendre"], "e": "El marit d'una germana és el cunyat."},
      {"q": "La mare de la teua dona és...", "o": ["la sogra", "la cunyada", "la nora"], "e": "La mare de la parella és la sogra."},
      {"q": "La dona del teu fill és...", "o": ["la nora", "la sogra", "la cunyada"], "e": "La dona d'un fill és la nora."},
      {"q": "El marit de la teua filla és...", "o": ["el gendre", "el cunyat", "el sogre"], "e": "El marit d'una filla és el gendre."},
      {"q": "Una persona que no s'ha casat és...", "o": ["soltera", "viuda", "divorciada"], "e": "Soltera: que no s'ha casat."},
      {"q": "Una dona a qui se li ha mort el marit és...", "o": ["viuda", "soltera", "divorciada"], "e": "Viuda (o vídua)."},
      {"q": "Quin és el nom valencià de «José»?", "o": ["Josep", "Jusep", "Josè"], "e": "José → Josep."},
      {"q": "Quin és el nom valencià de «Vicente»?", "o": ["Vicent", "Vicento", "Visent"], "e": "Vicente → Vicent."},
      {"q": "Quin és el nom valencià de «Juan»?", "o": ["Joan", "Jon", "Juà"], "e": "Juan → Joan."},
      {"q": "Quin és el nom valencià de «Pedro»?", "o": ["Pere", "Pedre", "Pèdro"], "e": "Pedro → Pere."},
      {"q": "Quin és el nom valencià de «Jorge»?", "o": ["Jordi", "Jorxe", "Jòrdi"], "e": "Jorge → Jordi."},
      {"q": "Quin és el nom valencià de «Carmen»?", "o": ["Carme", "Càrmen", "Carmena"], "e": "Carmen → Carme."},
      {"q": "Quin és el nom valencià de «Jaime»?", "o": ["Jaume", "Jaim", "Jàume"], "e": "Jaime → Jaume."},
      {"q": "On escriu la mestra a classe perquè ho veja tothom?", "o": ["a la pissarra", "a la cadira", "a la motxilla"], "e": "La pissarra."},
      {"q": "Amb què esborrem el que hem escrit amb llapis?", "o": ["amb la goma", "amb el regle", "amb la carpeta"], "e": "La goma."},
      {"q": "Amb què fem línies rectes?", "o": ["amb el regle", "amb la goma", "amb l'estoig"], "e": "El regle."},
      {"q": "On guardem els llapis i els bolis?", "o": ["a l'estoig", "a la pissarra", "a la paperera"], "e": "L'estoig."},
      {"q": "On portem els llibres a l'escola, a l'esquena?", "o": ["a la motxilla", "a l'estoig", "a la cartera de mà"], "e": "La motxilla es porta a l'esquena."},
      {"q": "La persona que ensenya en una escola és...", "o": ["el mestre o la mestra", "l'alumne o l'alumna", "el conserge o la conserja"], "e": "El mestre o la mestra ensenya; l'alumne aprén."},
      {"q": "El temps de descans entre les classes és...", "o": ["l'esplai", "l'examen", "la matrícula"], "e": "L'esplai (o el pati): temps de descans a l'escola."},
      {"q": "Els treballs que la mestra mana fer a casa són...", "o": ["els deures", "les notes", "les classes"], "e": "Els deures."},
      {"q": "Per a aprovar, has de traure bona nota en l'...", "o": ["examen", "esplai", "esmorzar"], "e": "L'examen."},
      {"q": "Si no aproves una assignatura, la...", "o": ["suspens", "apuntes", "matricules"], "e": "Suspendre: no aprovar."},
      {"q": "Els estudis que es fan a la universitat són...", "o": ["la carrera", "l'escola infantil", "la primària"], "e": "La carrera universitària."},
      {"q": "Qui cura els animals malalts?", "o": ["el veterinari", "el metge", "el farmacèutic"], "e": "El veterinari."},
      {"q": "Qui treballa en una farmàcia?", "o": ["el farmacèutic", "l'infermer", "el cambrer"], "e": "El farmacèutic."},
      {"q": "Qui servix el menjar i les begudes en un bar?", "o": ["el cambrer", "el cuiner", "el forner"], "e": "El cambrer servix; el cuiner cuina."},
      {"q": "Qui fa el pa?", "o": ["el forner", "el carnisser", "el peixater"], "e": "El forner treballa al forn."},
      {"q": "Qui ven carn?", "o": ["el carnisser", "el forner", "el fuster"], "e": "El carnisser treballa a la carnisseria."},
      {"q": "Qui porta les cartes a casa?", "o": ["el carter", "el conductor", "el cambrer"], "e": "El carter."},
      {"q": "Qui apaga els incendis?", "o": ["el bomber", "el policia", "el mecànic"], "e": "El bomber."},
      {"q": "Qui arregla els cotxes?", "o": ["el mecànic", "el fontaner", "el pintor"], "e": "El mecànic treballa en un taller."},
      {"q": "Qui arregla les canonades i les aixetes?", "o": ["el fontaner", "el mecànic", "el fuster"], "e": "El fontaner (o lampista)."},
      {"q": "Qui talla els cabells?", "o": ["el perruquer", "el sastre", "el pintor"], "e": "El perruquer."},
      {"q": "Qui cultiva la terra?", "o": ["el llaurador", "el pescador", "el mariner"], "e": "El llaurador."},
      {"q": "Qui defén una persona en un judici?", "o": ["l'advocat", "el jutge", "el policia"], "e": "L'advocat."},
      {"q": "On treballa un metge?", "o": ["a l'hospital", "a l'escola", "al forn"], "e": "A l'hospital o al centre de salut."},
      {"q": "On cuinem?", "o": ["a la cuina", "al bany", "al dormitori"], "e": "A la cuina."},
      {"q": "On dormim?", "o": ["al dormitori", "al menjador", "a la cuina"], "e": "Al dormitori (o l'habitació)."},
      {"q": "On ens dutxem?", "o": ["al bany", "al rebedor", "a la terrassa"], "e": "Al bany."},
      {"q": "On mengem amb la família i rebem les visites?", "o": ["al menjador", "al bany", "al garatge"], "e": "Al menjador."},
      {"q": "On guardem el cotxe?", "o": ["al garatge", "al balcó", "al rebedor"], "e": "Al garatge."},
      {"q": "Quin moble servix per a guardar la roba?", "o": ["l'armari", "la nevera", "el sofà"], "e": "L'armari."},
      {"q": "Quin electrodomèstic manté fresc el menjar?", "o": ["la nevera", "la rentadora", "el forn"], "e": "La nevera."},
      {"q": "Quin electrodomèstic renta la roba?", "o": ["la rentadora", "la nevera", "el microones"], "e": "La rentadora."},
      {"q": "On rentem els plats?", "o": ["a la pica", "al llit", "a l'armari"], "e": "A la pica de la cuina."},
      {"q": "On et gites per a dormir?", "o": ["al llit", "a la cadira", "a la taula"], "e": "Al llit."},
      {"q": "Per on puges d'un pis a un altre si no hi ha ascensor?", "o": ["per l'escala", "pel balcó", "per la finestra"], "e": "Per l'escala."},
      {"q": "Un habitatge dins d'un edifici amb altres veïns és un...", "o": ["pis", "xalet", "mas"], "e": "Un pis."},
      {"q": "Una casa amb jardí, fora de la ciutat, és un...", "o": ["xalet", "pis", "ascensor"], "e": "Un xalet."},
      {"q": "Les persones que viuen al teu edifici són els teus...", "o": ["veïns", "cosins", "cunyats"], "e": "Els veïns."},
      {"q": "Si la casa no és teua, cada mes pagues el...", "o": ["lloguer", "bitllet", "sou"], "e": "El lloguer."},
      {"q": "Escriu la paraula: el germà del teu pare és el teu ___.", "a": ["tio", "oncle"], "e": "El tio o l'oncle."},
      {"q": "Escriu la paraula: la professió de qui cura els malalts a l'hospital i ajuda el metge.", "a": ["infermer", "infermera"], "e": "L'infermer o la infermera."},
      {"q": "Escriu el nom valencià de «Francisco».", "a": ["Francesc"], "e": "Francisco → Francesc."},
      {"q": "Escriu la paraula: lloc de la casa on es cuina.", "a": ["cuina"], "e": "La cuina."}
    ]
  },
  {
    "id": "8fb32978-b788-4be5-81da-4993e52cf2f5", "type": "vocab_paisos_transport", "sort_order": 2,
    "title": "Països, transports i vies", "name": "Països, nacionalitats, transport i comunicació",
    "content": "Els països i les nacionalitats, el transport i la comunicació i les vies urbanes i no urbanes.", "icon": "🚆", "color": "#B3E5FC",
    "exercises": [
      {"q": "Com es diu un home d'Itàlia?", "o": ["italià", "italianer", "italiés"], "e": "Itàlia → italià, italiana."},
      {"q": "Una dona d'Alemanya és...", "o": ["alemanya", "alemana", "alemanyesa"], "e": "Alemanya → alemany, alemanya."},
      {"q": "Un home d'Anglaterra és...", "o": ["anglés", "anglesenc", "anglí"], "e": "Anglaterra → anglés, anglesa."},
      {"q": "Una dona de França és...", "o": ["francesa", "francessa", "francina"], "e": "França → francés, francesa."},
      {"q": "Un home del Marroc és...", "o": ["marroquí", "marroquenc", "marroqués"], "e": "el Marroc → marroquí, marroquina."},
      {"q": "Un home de Portugal és...", "o": ["portugués", "portugalés", "portuguenc"], "e": "Portugal → portugués, portuguesa."},
      {"q": "Una dona de Romania és...", "o": ["romanesa", "romana", "romaniana"], "e": "Romania → romanés, romanesa."},
      {"q": "Un home de la Xina és...", "o": ["xinés", "xinenc", "xinà"], "e": "la Xina → xinés, xinesa."},
      {"q": "Un home del Japó és...", "o": ["japonés", "japonenc", "japonà"], "e": "el Japó → japonés, japonesa."},
      {"q": "Un home dels Estats Units és...", "o": ["nord-americà", "estatunià", "americanés"], "e": "els Estats Units → nord-americà (o estatunidenc)."},
      {"q": "Un home de Rússia és...", "o": ["rus", "russenc", "rusà"], "e": "Rússia → rus, russa."},
      {"q": "Una dona de Grècia és...", "o": ["grega", "greca", "grecesa"], "e": "Grècia → grec, grega."},
      {"q": "Un home de Suïssa és...", "o": ["suís", "suïssenc", "suissà"], "e": "Suïssa → suís, suïssa."},
      {"q": "Una dona del Brasil és...", "o": ["brasilera", "brasilenca", "brasilana"], "e": "el Brasil → brasiler, brasilera."},
      {"q": "Com es diu en valencià el país «Inglaterra»?", "o": ["Anglaterra", "Inglaterra", "Englaterra"], "e": "Anglaterra."},
      {"q": "Com es diu en valencià el país «Alemania»?", "o": ["Alemanya", "Alemània", "Alemana"], "e": "Alemanya."},
      {"q": "Quina llengua es parla a Alemanya?", "o": ["l'alemany", "l'alemanyol", "l'alemanés"], "e": "L'alemany."},
      {"q": "Quina llengua es parla al Brasil?", "o": ["el portugués", "l'espanyol", "el brasiler"], "e": "Al Brasil es parla portugués."},
      {"q": "Quin mitjà de transport va per les vies?", "o": ["el tren", "el vaixell", "l'avió"], "e": "El tren va per les vies."},
      {"q": "Quin vehicle té dues rodes i pedals?", "o": ["la bicicleta", "la moto", "el cotxe"], "e": "La bicicleta."},
      {"q": "Quin transport va per davall de terra a la ciutat?", "o": ["el metro", "el tramvia", "el taxi"], "e": "El metro."},
      {"q": "Un cotxe que et porta on vols i pagues al conductor és un...", "o": ["taxi", "autobús", "tramvia"], "e": "El taxi."},
      {"q": "On esperes l'autobús?", "o": ["a la parada", "a l'aeroport", "al port"], "e": "A la parada."},
      {"q": "On agafes l'avió?", "o": ["a l'aeroport", "al port", "a l'estació"], "e": "A l'aeroport."},
      {"q": "On agafes el vaixell?", "o": ["al port", "a l'aeroport", "a la parada"], "e": "Al port."},
      {"q": "On agafes el tren?", "o": ["a l'estació", "al port", "a l'aeroport"], "e": "A l'estació."},
      {"q": "Què has de comprar per a pujar al tren?", "o": ["el bitllet", "el segell", "la carta"], "e": "El bitllet."},
      {"q": "Un bitllet per a anar i tornar és d'...", "o": ["anada i tornada", "eixida i entrada", "pujada i baixada"], "e": "Bitllet d'anada i tornada."},
      {"q": "La persona que condueix un autobús és...", "o": ["el conductor", "el pilot", "el mariner"], "e": "El conductor."},
      {"q": "La persona que condueix un avió és...", "o": ["el pilot", "el conductor", "el taxista"], "e": "El pilot."},
      {"q": "Per a conduir un cotxe necessites el...", "o": ["carnet de conduir", "passaport", "bitllet"], "e": "El carnet de conduir."},
      {"q": "Per a viatjar a un país de fora d'Europa necessites el...", "o": ["passaport", "carnet de conduir", "segell"], "e": "El passaport."},
      {"q": "El cotxe no té benzina. On vas?", "o": ["a la gasolinera", "al taller", "a la parada"], "e": "A la gasolinera."},
      {"q": "Per a enviar una carta, necessites un...", "o": ["segell", "bitllet", "tiquet"], "e": "El segell."},
      {"q": "On compres segells i envies paquets?", "o": ["a Correus", "a la farmàcia", "al forn"], "e": "A l'oficina de Correus."},
      {"q": "On tirem les cartes per a enviar-les?", "o": ["a la bústia", "a la paperera", "al calaix"], "e": "A la bústia."},
      {"q": "Dins de què posem la carta?", "o": ["dins d'un sobre", "dins d'un segell", "dins d'una bústia de paper"], "e": "La carta va dins d'un sobre."},
      {"q": "Amb què fem una telefonada?", "o": ["amb el mòbil", "amb la bústia", "amb el sobre"], "e": "Amb el mòbil o el telèfon."},
      {"q": "Un missatge que envies per internet és un...", "o": ["correu electrònic", "segell", "sobre"], "e": "Un correu electrònic."},
      {"q": "Quan algú et telefona, el mòbil...", "o": ["sona", "canta", "crida"], "e": "El mòbil sona."},
      {"q": "Una via ampla d'una ciutat, amb arbres, és una...", "o": ["avinguda", "senda", "autopista"], "e": "Una avinguda."},
      {"q": "Una via ràpida per a cotxes entre ciutats és una...", "o": ["autopista", "plaça", "vorera"], "e": "Una autopista (o autovia)."},
      {"q": "Per on caminen les persones en un carrer?", "o": ["per la vorera", "per la carretera", "per l'autopista"], "e": "Per la vorera."},
      {"q": "Per on travessem el carrer?", "o": ["pel pas de vianants", "per la rotonda", "per l'autopista"], "e": "Pel pas de vianants."},
      {"q": "La llum que diu quan pots passar (roja, groga, verda) és...", "o": ["el semàfor", "el fanal", "el pont"], "e": "El semàfor."},
      {"q": "Un encreuament en forma de cercle on giren els cotxes és...", "o": ["una rotonda", "una plaça", "un pont"], "e": "Una rotonda."},
      {"q": "Un lloc ample i obert en un poble, sovint amb una font, és...", "o": ["una plaça", "una autovia", "una senda"], "e": "Una plaça."},
      {"q": "Un camí estret per a caminar pel camp o la muntanya és...", "o": ["una senda", "una avinguda", "una autopista"], "e": "Una senda."},
      {"q": "Una construcció per a passar per damunt d'un riu és...", "o": ["un pont", "un túnel", "un passeig"], "e": "Un pont."},
      {"q": "Un carrer molt estret i curt és...", "o": ["un carreró", "una avinguda", "una carretera"], "e": "Un carreró."},
      {"q": "El passeig al costat de la mar és...", "o": ["el passeig marítim", "la carretera", "l'autopista"], "e": "El passeig marítim."},
      {"q": "Escriu la nacionalitat: una dona d'Anglaterra és ___.", "a": ["anglesa"], "e": "Anglesa."},
      {"q": "Escriu la nacionalitat: un home d'Espanya és ___.", "a": ["espanyol"], "e": "Espanyol."},
      {"q": "Escriu la paraula: on esperes l'autobús? A la ___.", "a": ["parada"], "e": "A la parada."},
      {"q": "Escriu la professió de qui porta les cartes.", "a": ["carter", "cartera"], "e": "El carter o la cartera."}
    ]
  },
  {
    "id": "cef4ecd9-b084-43b8-8ee5-d305e3b702f8", "type": "vocab_temps", "sort_order": 3,
    "title": "L'hora i el calendari", "name": "La mesura del temps",
    "content": "L'hora, les parts del dia, els dies de la setmana, els mesos i les estacions.", "icon": "🕒", "color": "#FFF9C4",
    "exercises": [
      {"q": "Són les 17.30. Com ho dius?", "o": ["Són les cinc i mitja de la vesprada.", "Són les set i mitja.", "És la una i mitja."], "e": "Les 17.30 són les cinc i mitja de la vesprada."},
      {"q": "Són les 8.00 del matí. Com ho dius?", "o": ["Són les huit del matí.", "Són les huit de la nit.", "És la huit del matí."], "e": "Són les huit (o vuit) del matí."},
      {"q": "Són les 13.00. Com ho dius?", "o": ["És la una del migdia.", "Són la una.", "Són les u."], "e": "Amb la una s'usa el singular: és la una."},
      {"q": "Són les 21.15. Com ho dius?", "o": ["Són les nou i quart de la nit.", "Són les nou i quart del matí.", "Són les deu i quart de la nit."], "e": "Les 21.15 són les nou i quart de la nit."},
      {"q": "Són les 10.45. Com ho dius?", "o": ["Són les onze menys quart.", "Són les deu menys quart.", "Són les onze i quart."], "e": "Falta un quart per a les onze: les onze menys quart (o tres quarts d'onze)."},
      {"q": "Són les 12.00 de la nit. Com ho dius?", "o": ["És mitjanit.", "És migdia.", "És de vesprada."], "e": "Les 12 de la nit: mitjanit."},
      {"q": "Són les 12.00 del dia. Com ho dius?", "o": ["És migdia.", "És mitjanit.", "És de vesprada."], "e": "Les 12 del dia: migdia."},
      {"q": "Com preguntes l'hora?", "o": ["Quina hora és?", "Quant hora és?", "Què hora és?"], "e": "Quina hora és?"},
      {"q": "Com preguntes quan comença una cosa?", "o": ["A quina hora comença?", "En quina hora comença?", "Quina hora comença?"], "e": "A quina hora...?"},
      {"q": "La primera part del dia és...", "o": ["el matí", "la vesprada", "la nit"], "e": "El matí."},
      {"q": "La part del dia després de dinar és...", "o": ["la vesprada", "el matí", "la matinada"], "e": "La vesprada."},
      {"q": "Quan es fa fosc, abans de la nit, és...", "o": ["el vespre", "el matí", "la matinada"], "e": "El vespre."},
      {"q": "Les hores després de mitjanit, abans que isca el sol, són...", "o": ["la matinada", "la vesprada", "el migdia"], "e": "La matinada."},
      {"q": "El menjar del matí és...", "o": ["l'esmorzar", "el sopar", "el dinar"], "e": "L'esmorzar."},
      {"q": "El menjar del migdia és...", "o": ["el dinar", "el sopar", "l'esmorzar"], "e": "El dinar."},
      {"q": "El menjar de la nit és...", "o": ["el sopar", "el dinar", "el berenar"], "e": "El sopar."},
      {"q": "El menjar de mitja vesprada, sobretot dels xiquets, és...", "o": ["el berenar", "el sopar", "l'esmorzar"], "e": "El berenar."},
      {"q": "Quin dia va després de dimecres?", "o": ["dijous", "dimarts", "divendres"], "e": "Dilluns, dimarts, dimecres, dijous, divendres, dissabte i diumenge."},
      {"q": "Quin dia va abans de diumenge?", "o": ["dissabte", "dilluns", "divendres"], "e": "Dissabte va abans de diumenge."},
      {"q": "Quin és el primer dia de la setmana laboral?", "o": ["dilluns", "diumenge", "dimarts"], "e": "Dilluns."},
      {"q": "Dissabte i diumenge són...", "o": ["el cap de setmana", "dies feiners", "la quinzena"], "e": "El cap de setmana."},
      {"q": "Els dies de dilluns a divendres són dies...", "o": ["feiners", "festius", "vells"], "e": "Dies feiners: dies de treball."},
      {"q": "Si hui és dimarts, demà passat serà...", "o": ["dijous", "dimecres", "divendres"], "e": "Demà: dimecres; demà passat: dijous."},
      {"q": "Si hui és dilluns, abans-d'ahir va ser...", "o": ["dissabte", "diumenge", "divendres"], "e": "Ahir: diumenge; abans-d'ahir: dissabte."},
      {"q": "Set dies fan una...", "o": ["setmana", "quinzena", "mesada"], "e": "Una setmana."},
      {"q": "Quinze dies fan una...", "o": ["quinzena", "setmana", "dotzena"], "e": "Una quinzena."},
      {"q": "Quin és el primer mes de l'any?", "o": ["gener", "febrer", "desembre"], "e": "Gener."},
      {"q": "Quin mes va després de març?", "o": ["abril", "maig", "febrer"], "e": "Març, abril, maig."},
      {"q": "Quin mes té 28 dies (o 29)?", "o": ["febrer", "gener", "juny"], "e": "Febrer."},
      {"q": "Quin mes va entre juny i agost?", "o": ["juliol", "maig", "setembre"], "e": "Juny, juliol, agost."},
      {"q": "Quin mes va després de setembre?", "o": ["octubre", "novembre", "agost"], "e": "Setembre, octubre, novembre."},
      {"q": "Quin és l'últim mes de l'any?", "o": ["desembre", "novembre", "octubre"], "e": "Desembre."},
      {"q": "En quin mes és Nadal?", "o": ["desembre", "gener", "novembre"], "e": "Nadal és el 25 de desembre."},
      {"q": "En quin mes solen començar les classes?", "o": ["setembre", "juliol", "gener"], "e": "Setembre."},
      {"q": "Dotze mesos fan un...", "o": ["any", "segle", "trimestre"], "e": "Un any."},
      {"q": "En quina estació de l'any fa més calor?", "o": ["l'estiu", "l'hivern", "la tardor"], "e": "L'estiu."},
      {"q": "En quina estació fa més fred?", "o": ["l'hivern", "l'estiu", "la primavera"], "e": "L'hivern."},
      {"q": "En quina estació cauen les fulles dels arbres?", "o": ["la tardor", "la primavera", "l'estiu"], "e": "La tardor."},
      {"q": "En quina estació ixen les flors?", "o": ["la primavera", "la tardor", "l'hivern"], "e": "La primavera."},
      {"q": "Quantes estacions té l'any?", "o": ["quatre", "tres", "dotze"], "e": "Primavera, estiu, tardor i hivern."},
      {"q": "Seixanta minuts fan una...", "o": ["hora", "setmana", "quinzena"], "e": "Una hora."},
      {"q": "Seixanta segons fan un...", "o": ["minut", "hora", "dia"], "e": "Un minut."},
      {"q": "Mitja hora són...", "o": ["trenta minuts", "quinze minuts", "quaranta-cinc minuts"], "e": "Mitja hora = 30 minuts."},
      {"q": "Un quart d'hora són...", "o": ["quinze minuts", "trenta minuts", "deu minuts"], "e": "Un quart d'hora = 15 minuts."},
      {"q": "Cent anys fan un...", "o": ["segle", "trimestre", "mes"], "e": "Un segle."},
      {"q": "El dia abans d'ahir és...", "o": ["abans-d'ahir", "demà passat", "anit"], "e": "Abans-d'ahir."},
      {"q": "La nit d'ahir és...", "o": ["anit", "demà", "enguany"], "e": "Anit."},
      {"q": "L'any en què estem és...", "o": ["enguany", "l'any que ve", "l'any passat"], "e": "Enguany: este any."},
      {"q": "Escriu el dia que va després de dijous.", "a": ["divendres"], "e": "Divendres."},
      {"q": "Escriu el mes que va després de juliol.", "a": ["agost"], "e": "Agost."},
      {"q": "Escriu l'estació que va després de l'estiu.", "a": ["tardor", "la tardor"], "e": "La tardor."},
      {"q": "Escriu el nom del menjar de la nit.", "a": ["sopar", "el sopar"], "e": "El sopar."}
    ]
  },
  {
    "id": "6cb790d3-59d2-40f2-ad09-b465ae03a471", "type": "vocab_menjar", "sort_order": 4,
    "title": "El menjar", "name": "Aliments, begudes, envasos i mesures",
    "content": "Els aliments, les begudes, els envasos i les mesures; al restaurant i a la taula.", "icon": "🍅", "color": "#DCEDC8",
    "exercises": [
      {"q": "Quina d'estes és una hortalissa?", "o": ["la ceba", "la poma", "la pera"], "e": "La ceba és una hortalissa; la poma i la pera són fruites."},
      {"q": "Quina fruita és groga i llarga?", "o": ["el plàtan", "la maduixa", "la cirera"], "e": "El plàtan."},
      {"q": "Quina fruita és roja, xicoteta i té un pinyol?", "o": ["la cirera", "la síndria", "el meló"], "e": "La cirera."},
      {"q": "Quina fruita és gran, verda per fora i roja per dins?", "o": ["la síndria", "el meló", "la pinya"], "e": "La síndria."},
      {"q": "Quina fruita valenciana fem servir per a fer suc?", "o": ["la taronja", "la pinya", "la pera"], "e": "La taronja."},
      {"q": "Amb quina fruita es fa el vi?", "o": ["amb el raïm", "amb la pera", "amb la poma"], "e": "El vi es fa amb raïm."},
      {"q": "Quina hortalissa roja fem servir per a l'amanida i el gaspatxo?", "o": ["la tomaca", "la creïlla", "la ceba"], "e": "La tomaca (o tomàquet)."},
      {"q": "Amb què fem la truita i les patates fregides?", "o": ["amb creïlles", "amb cebes", "amb carabasses"], "e": "La creïlla (o patata)."},
      {"q": "Quina hortalissa és taronja i llarga?", "o": ["la safanòria", "la ceba", "la col"], "e": "La safanòria (o pastanaga)."},
      {"q": "Quina verdura de fulles verdes posem a l'amanida?", "o": ["l'enciam", "l'all", "la ceba"], "e": "L'enciam."},
      {"q": "Quin condiment xicotet i blanc té un sabor molt fort?", "o": ["l'all", "l'enciam", "el julivert"], "e": "L'all (per a l'allioli)."},
      {"q": "Quin d'estos aliments és un llegum?", "o": ["els cigrons", "les pomes", "els raïms"], "e": "Els cigrons, les llentilles i les mongetes són llegums."},
      {"q": "Quin llegum és xicotet, redó i marró?", "o": ["les llentilles", "les cireres", "les olives"], "e": "Les llentilles."},
      {"q": "La paella valenciana porta pollastre i...", "o": ["conill", "vedella", "sardina"], "e": "La paella valenciana porta pollastre i conill."},
      {"q": "La carn de vaca jove és...", "o": ["la vedella", "el corder", "el porc"], "e": "La vedella."},
      {"q": "La carn de l'ovella jove és...", "o": ["el corder", "la vedella", "el conill"], "e": "El corder (o xai)."},
      {"q": "Quin és un peix blau xicotet i molt comú?", "o": ["la sardina", "el lluç", "la gamba"], "e": "La sardina."},
      {"q": "Quin animal de la mar té pinces?", "o": ["el cranc", "la sardina", "la tonyina"], "e": "El cranc."},
      {"q": "Quin aliment blanc ens donen les vaques?", "o": ["la llet", "l'oli", "la farina"], "e": "La llet."},
      {"q": "Quin aliment fet amb llet pot ser tendre o curat?", "o": ["el formatge", "el iogurt", "la mantega"], "e": "El formatge."},
      {"q": "Què ponen les gallines?", "o": ["ous", "llet", "carn"], "e": "Les gallines ponen ous."},
      {"q": "Què comprem al forn?", "o": ["el pa", "la carn", "el peix"], "e": "Al forn comprem pa."},
      {"q": "Quin cereal és l'ingredient principal de la paella?", "o": ["l'arròs", "el blat", "la civada"], "e": "L'arròs."},
      {"q": "Quin plat es fa amb ous batuts i creïlla?", "o": ["la truita", "la paella", "el gaspatxo"], "e": "La truita de creïlla."},
      {"q": "Pa obert amb formatge, pernil o truita dins és...", "o": ["un entrepà", "un pastís", "una sopa"], "e": "Un entrepà."},
      {"q": "Quin dolç mengem en els aniversaris?", "o": ["el pastís", "l'entrepà", "el pa"], "e": "El pastís."},
      {"q": "Quin condiment blanc ve de la mar?", "o": ["la sal", "el sucre", "el pebre"], "e": "La sal."},
      {"q": "Què endolcix el café?", "o": ["el sucre", "la sal", "l'oli"], "e": "El sucre."},
      {"q": "Amb què amanim l'amanida?", "o": ["amb oli i sal", "amb sucre i llet", "amb farina i ous"], "e": "Amb oli, sal i vinagre."},
      {"q": "Quina beguda calenta es fa amb fulles?", "o": ["el te", "el café", "la llet"], "e": "El te."},
      {"q": "Quina beguda de raïm té alcohol?", "o": ["el vi", "el suc", "l'orxata"], "e": "El vi."},
      {"q": "Quina beguda té alcohol, es fa amb ordi i fa escuma?", "o": ["la cervesa", "el vi", "el suc"], "e": "La cervesa."},
      {"q": "Quina beguda es fa esprement fruita?", "o": ["el suc", "el vi", "la cervesa"], "e": "El suc."},
      {"q": "Quina beguda valenciana es fa amb xufa?", "o": ["l'orxata", "la llimonada", "el granissat de café"], "e": "L'orxata de xufa."},
      {"q": "Una beguda amb bombolles i sense alcohol és...", "o": ["un refresc", "un vi", "un cava"], "e": "Un refresc."},
      {"q": "Quin d'estos és un envàs?", "o": ["una botella", "un quilo", "un litre"], "e": "La botella és un envàs. Quilo i litre són mesures."},
      {"q": "L'envàs de metall per als refrescos o la tonyina és...", "o": ["la llanda", "el sac", "la safata"], "e": "La llanda (o llauna)."},
      {"q": "L'envàs de vidre amb tapa per a la melmelada és...", "o": ["el pot", "la bossa", "el sobre"], "e": "El pot."},
      {"q": "Les galetes i l'arròs els comprem en un...", "o": ["paquet", "pot de vidre", "got"], "e": "Un paquet."},
      {"q": "La carn del supermercat ve en una...", "o": ["safata", "botella", "llanda"], "e": "Una safata."},
      {"q": "L'oli i la llet es venen per...", "o": ["litres", "quilos", "metres"], "e": "Els líquids es venen per litres."},
      {"q": "La fruita es ven per...", "o": ["quilos", "litres", "metres"], "e": "Per quilos."},
      {"q": "Mig quilo són...", "o": ["cinc-cents grams", "cent grams", "mil grams"], "e": "Un quilo = 1.000 grams; mig quilo = 500 grams."},
      {"q": "Els ous es venen per...", "o": ["dotzenes", "litres", "metres"], "e": "Una dotzena = 12 ous."},
      {"q": "Un tros pla de pa és una...", "o": ["llesca", "tassa", "botella"], "e": "Una llesca de pa."},
      {"q": "Amb què mengem la sopa?", "o": ["amb la cullera", "amb la forqueta", "amb el ganivet"], "e": "Amb la cullera."},
      {"q": "Amb què tallem la carn?", "o": ["amb el ganivet", "amb la cullera", "amb el got"], "e": "Amb el ganivet."},
      {"q": "On bevem l'aigua?", "o": ["en un got", "en un plat", "en una forqueta"], "e": "En un got."},
      {"q": "Al restaurant, per a saber què hi ha per a menjar, demanes...", "o": ["la carta", "el compte", "la propina"], "e": "La carta."},
      {"q": "Al restaurant, per a pagar, demanes...", "o": ["el compte", "la carta", "el menú"], "e": "El compte, per favor."},
      {"q": "Després del segon plat mengem...", "o": ["les postres", "l'esmorzar", "l'entrant"], "e": "Les postres."},
      {"q": "Escriu el nom de la beguda valenciana que es fa amb xufa.", "a": ["orxata", "l'orxata"], "e": "L'orxata."},
      {"q": "Escriu el nom de la fruita groga i àcida.", "a": ["llima", "llimona"], "e": "La llima (o llimona)."},
      {"q": "Escriu el nom del plat valencià d'arròs que es cuina en una paella.", "a": ["paella"], "e": "La paella."},
      {"q": "Escriu el nom del lloc on es compra el pa.", "a": ["forn", "el forn", "al forn", "fleca", "la fleca"], "e": "El forn (o la fleca)."}
    ]
  },
  {
    "id": "a08cc2d7-a3db-4e92-9661-7c15b9342144", "type": "vocab_roba_cos", "sort_order": 5,
    "title": "La roba, el cos i els colors", "name": "Vestit, complements, cos humà i colors",
    "content": "El vestit i els complements, el cos humà i els colors.", "icon": "👕", "color": "#F8BBD0",
    "exercises": [
      {"q": "Quina peça de roba portem a les cames?", "o": ["els pantalons", "la camisa", "la jaqueta"], "e": "Els pantalons."},
      {"q": "Quina peça de màniga curta portem quan fa calor?", "o": ["la samarreta", "l'abric", "la bufanda"], "e": "La samarreta."},
      {"q": "Quina peça llarga portem damunt de la roba quan fa molt de fred?", "o": ["l'abric", "el banyador", "la samarreta"], "e": "L'abric."},
      {"q": "Què portem per a nadar a la platja?", "o": ["el banyador", "l'abric", "la corbata"], "e": "El banyador."},
      {"q": "Quina peça cobrix de la cintura a les cames i la porten sobretot les dones?", "o": ["la falda", "la camisa", "la jaqueta"], "e": "La falda."},
      {"q": "Què portem als peus, dins de les sabates?", "o": ["els calcetins", "els guants", "els botons"], "e": "Els calcetins."},
      {"q": "Què portem a les mans quan fa fred?", "o": ["els guants", "els calcetins", "les arracades"], "e": "Els guants."},
      {"q": "Què portem al coll quan fa fred?", "o": ["la bufanda", "la gorra", "el cinturó"], "e": "La bufanda."},
      {"q": "Què portem al cap per a protegir-nos del sol?", "o": ["el barret", "la bufanda", "el cinturó"], "e": "El barret (o la gorra)."},
      {"q": "Què servix perquè no caiguen els pantalons?", "o": ["el cinturó", "la corbata", "la bufanda"], "e": "El cinturó."},
      {"q": "Què porten alguns homes al coll, amb camisa i jaqueta?", "o": ["la corbata", "el cinturó", "el rellotge"], "e": "La corbata."},
      {"q": "Quin calcer alt portem quan plou?", "o": ["les botes", "les sandàlies", "les espardenyes"], "e": "Les botes."},
      {"q": "Quin calcer obert portem a l'estiu?", "o": ["les sandàlies", "les botes", "els calcetins"], "e": "Les sandàlies."},
      {"q": "Quina roba portem per a dormir?", "o": ["el pijama", "el banyador", "l'abric"], "e": "El pijama."},
      {"q": "On guardem els diners i les targetes?", "o": ["a la cartera", "a la corbata", "al cinturó"], "e": "A la cartera."},
      {"q": "Quin complement ens diu l'hora?", "o": ["el rellotge", "l'anell", "la polsera"], "e": "El rellotge."},
      {"q": "Quina joia portem al dit?", "o": ["l'anell", "l'arracada", "el collar"], "e": "L'anell."},
      {"q": "Quines joies portem a les orelles?", "o": ["les arracades", "els anells", "les polseres"], "e": "Les arracades."},
      {"q": "Què fem servir perquè no ens mulle la pluja?", "o": ["el paraigua", "el barret de palla", "la bufanda"], "e": "El paraigua."},
      {"q": "Què ens posem per a protegir els ulls del sol?", "o": ["les ulleres de sol", "els guants", "les arracades"], "e": "Les ulleres de sol."},
      {"q": "On guardes les claus en els pantalons?", "o": ["a la butxaca", "a la màniga", "al coll"], "e": "A la butxaca."},
      {"q": "Quina part de la camisa cobrix el braç?", "o": ["la màniga", "la butxaca", "el botó"], "e": "La màniga."},
      {"q": "A la botiga, on vas per a provar-te la roba?", "o": ["a l'emprovador", "a la caixa", "a l'aparador"], "e": "A l'emprovador."},
      {"q": "On et poses les sabates?", "o": ["als peus", "a les mans", "al cap"], "e": "Les sabates van als peus."},
      {"q": "Amb què veiem?", "o": ["amb els ulls", "amb les orelles", "amb el nas"], "e": "Amb els ulls."},
      {"q": "Amb què sentim?", "o": ["amb les orelles", "amb els ulls", "amb la boca"], "e": "Amb les orelles."},
      {"q": "Amb què olorem?", "o": ["amb el nas", "amb la boca", "amb les mans"], "e": "Amb el nas."},
      {"q": "Què tenim dins de la boca per a mastegar?", "o": ["les dents", "els llavis", "les ungles"], "e": "Les dents."},
      {"q": "Què tenim dins de la boca per a notar el sabor?", "o": ["la llengua", "les dents", "els llavis"], "e": "La llengua."},
      {"q": "Quina part del cos va entre el cap i les espatles?", "o": ["el coll", "el colze", "el genoll"], "e": "El coll."},
      {"q": "Quina part del braç es doblega?", "o": ["el colze", "el genoll", "el turmell"], "e": "El colze."},
      {"q": "Quina part de la cama es doblega?", "o": ["el genoll", "el colze", "el canell"], "e": "El genoll."},
      {"q": "Quina part del cos va entre la cama i el peu?", "o": ["el turmell", "el canell", "el colze"], "e": "El turmell."},
      {"q": "Quina part del cos va entre el braç i la mà?", "o": ["el canell", "el turmell", "el genoll"], "e": "El canell."},
      {"q": "Quants dits tenim en cada mà?", "o": ["cinc", "quatre", "deu"], "e": "Cinc dits en cada mà."},
      {"q": "La part de darrere del cos, de les espatles a la cintura, és...", "o": ["l'esquena", "la panxa", "el pit"], "e": "L'esquena."},
      {"q": "La part de davant del cos on tenim el melic és...", "o": ["la panxa", "l'esquena", "el coll"], "e": "La panxa."},
      {"q": "El pèl que tenim al cap són...", "o": ["els cabells", "les celles", "les pestanyes"], "e": "Els cabells."},
      {"q": "El pèl de la cara d'alguns homes, a la barbeta, és...", "o": ["la barba", "les celles", "els cabells"], "e": "La barba."},
      {"q": "Quin òrgan bomba la sang?", "o": ["el cor", "l'estómac", "el pulmó"], "e": "El cor."},
      {"q": "Amb què respirem?", "o": ["amb els pulmons", "amb l'estómac", "amb el cor"], "e": "Amb els pulmons."},
      {"q": "On va el menjar quan l'empassem?", "o": ["a l'estómac", "als pulmons", "al cor"], "e": "A l'estómac."},
      {"q": "De quin color és la neu?", "o": ["blanca", "negra", "roja"], "e": "La neu és blanca."},
      {"q": "De quin color és el cel quan fa sol?", "o": ["blau", "verd", "marró"], "e": "Blau."},
      {"q": "De quin color és l'herba?", "o": ["verda", "groga", "blava"], "e": "Verda."},
      {"q": "De quin color és la sang?", "o": ["roja", "blava", "verda"], "e": "Roja."},
      {"q": "De quin color són les llimes?", "o": ["grogues", "morades", "blanques"], "e": "Grogues."},
      {"q": "De quin color és el carbó?", "o": ["negre", "blanc", "groc"], "e": "Negre."},
      {"q": "De quin color és la xocolata?", "o": ["marró", "groc", "verd"], "e": "Marró."},
      {"q": "Si mesclem blanc i negre, quin color ix?", "o": ["gris", "rosa", "marró"], "e": "Gris."},
      {"q": "Si mesclem roig i blanc, quin color ix?", "o": ["rosa", "taronja", "gris"], "e": "Rosa."},
      {"q": "Si mesclem blau i roig, quin color ix?", "o": ["morat", "verd", "taronja"], "e": "Morat."},
      {"q": "Si mesclem groc i blau, quin color ix?", "o": ["verd", "morat", "gris"], "e": "Verd."},
      {"q": "Quin és el femení de «roig»?", "o": ["roja", "roiga", "rotja"], "e": "Roig → roja."},
      {"q": "Quin és el femení de «groc»?", "o": ["groga", "groca", "grogua"], "e": "Groc → groga."},
      {"q": "Quin és el plural de «blau» (masculí)?", "o": ["blaus", "blavos", "blaves"], "e": "Blau → blaus (femení: blava, blaves)."},
      {"q": "Escriu la part del cos amb què veiem (en plural).", "a": ["ulls", "els ulls"], "e": "Els ulls."},
      {"q": "Escriu el nom de la peça de roba que portem a les cames.", "a": ["pantalons", "els pantalons", "pantaló", "el pantaló"], "e": "Els pantalons."},
      {"q": "Escriu el color de la neu (en masculí).", "a": ["blanc"], "e": "Blanc."}
    ]
  },
  {
    "id": "4cd60711-b1d4-4d5a-b88e-d277d3989a0e", "type": "vocab_oci", "sort_order": 6,
    "title": "Oci, viatges i festes", "name": "Temps lliure, aficions, viatges i festes",
    "content": "El temps lliure i les aficions, els viatges i les vacances i les festes.", "icon": "🎉", "color": "#FFE082",
    "exercises": [
      {"q": "Si t'agrada llegir, pots traure llibres de...", "o": ["la biblioteca", "la farmàcia", "el gimnàs"], "e": "La biblioteca."},
      {"q": "On veiem pel·lícules en una pantalla gran?", "o": ["al cine", "al museu", "a la biblioteca"], "e": "Al cine."},
      {"q": "On veiem obres de teatre?", "o": ["al teatre", "al cine", "a l'estadi"], "e": "Al teatre."},
      {"q": "On veiem quadres i escultures?", "o": ["al museu", "a l'estadi", "al mercat"], "e": "Al museu."},
      {"q": "On fem esport amb màquines i peses?", "o": ["al gimnàs", "a la biblioteca", "al museu"], "e": "Al gimnàs."},
      {"q": "Quin esport es juga amb una pilota i dues porteries?", "o": ["el futbol", "el tenis", "la natació"], "e": "El futbol."},
      {"q": "Quin esport fem a la piscina?", "o": ["la natació", "el ciclisme", "el bàsquet"], "e": "La natació."},
      {"q": "En quin esport anem amb bicicleta?", "o": ["el ciclisme", "la natació", "l'atletisme"], "e": "El ciclisme."},
      {"q": "Quin és l'esport tradicional valencià que es juga amb la mà?", "o": ["la pilota valenciana", "el tenis", "el golf"], "e": "La pilota valenciana."},
      {"q": "Anar a caminar per la muntanya és fer...", "o": ["senderisme", "natació", "ciclisme"], "e": "Senderisme."},
      {"q": "Quin instrument té tecles blanques i negres?", "o": ["el piano", "la guitarra", "el violí"], "e": "El piano."},
      {"q": "Quin instrument de vent sona en moltes festes valencianes, amb el tabal?", "o": ["la dolçaina", "el piano", "la guitarra"], "e": "La dolçaina i el tabal."},
      {"q": "Una persona que toca música és...", "o": ["un músic", "un pintor", "un escriptor"], "e": "Un músic."},
      {"q": "Si t'agrada fer fotos, la teua afició és la...", "o": ["fotografia", "pintura", "natació"], "e": "La fotografia."},
      {"q": "Jugar a la baralla és jugar a les...", "o": ["cartes", "pilotes", "raquetes"], "e": "Jugar a les cartes."},
      {"q": "Mirar botigues i comprar roba és anar de...", "o": ["compres", "vacances", "excursió"], "e": "Anar de compres."},
      {"q": "Per a entrar al cine o a un concert necessites...", "o": ["l'entrada", "el segell", "el passaport"], "e": "L'entrada."},
      {"q": "On dorms quan vas de viatge?", "o": ["a l'hotel", "a l'hospital", "a l'estació"], "e": "A l'hotel."},
      {"q": "Una habitació d'hotel per a dues persones és...", "o": ["doble", "individual", "senzilla"], "e": "Doble: per a dues persones. Individual: per a una."},
      {"q": "On guardes la roba quan vas de viatge?", "o": ["a la maleta", "a la cartera", "a la bústia"], "e": "A la maleta."},
      {"q": "Un mapa dels carrers d'una ciutat és...", "o": ["un plànol", "un calendari", "un horari"], "e": "Un plànol."},
      {"q": "On donen informació als turistes?", "o": ["a l'oficina de turisme", "a l'oficina de Correus", "a la comissaria"], "e": "A l'oficina de turisme."},
      {"q": "Una persona que visita una ciutat per a conéixer-la és...", "o": ["un turista", "un veí", "un alumne"], "e": "Un turista."},
      {"q": "La persona que explica la ciutat als turistes és...", "o": ["el guia", "el xofer", "el cambrer"], "e": "El guia."},
      {"q": "Quan tornes d'un viatge, a vegades portes als amics un...", "o": ["record", "bitllet", "segell"], "e": "Un record del viatge."},
      {"q": "Una targeta amb la foto d'un lloc que enviem per correu és...", "o": ["una postal", "un segell", "un sobre"], "e": "Una postal."},
      {"q": "A la platja ens gitem damunt de la...", "o": ["tovallola", "catifa", "cadira de l'oficina"], "e": "La tovallola."},
      {"q": "Quan anem d'acampada dormim en una...", "o": ["tenda de campanya", "maleta", "piscina"], "e": "Una tenda de campanya."},
      {"q": "Els dies que no treballes a l'estiu són les...", "o": ["vacances", "feines", "classes"], "e": "Les vacances."},
      {"q": "Passar el dia fora, per exemple a la muntanya, és fer...", "o": ["una excursió", "una reunió", "una classe"], "e": "Una excursió."},
      {"q": "Quina festa valenciana se celebra al mes de març?", "o": ["les Falles", "el Nadal", "Sant Joan"], "e": "Les Falles, del 15 al 19 de març."},
      {"q": "Quina festa se celebra la nit del 23 al 24 de juny, amb fogueres a la platja?", "o": ["Sant Joan", "Nadal", "Pasqua"], "e": "La nit de Sant Joan."},
      {"q": "Com es diuen les festes de Sant Joan a Alacant?", "o": ["les Fogueres", "les Falles", "la Magdalena"], "e": "Les Fogueres de Sant Joan."},
      {"q": "Quina és la festa de Castelló a la primavera?", "o": ["la Magdalena", "les Fogueres", "les Falles"], "e": "Les festes de la Magdalena."},
      {"q": "En quina festa hi ha desfilades de «moros» i «cristians», com a Alcoi?", "o": ["els Moros i Cristians", "les Falles", "la Magdalena"], "e": "Els Moros i Cristians."},
      {"q": "A les Falles, el soroll de pólvora que se sent al migdia és...", "o": ["la mascletà", "la cremà", "l'ofrena"], "e": "La mascletà."},
      {"q": "La nit del 19 de març, quan es cremen les falles, és...", "o": ["la cremà", "la mascletà", "l'ofrena"], "e": "La cremà."},
      {"q": "Quan els fallers porten flors a la Mare de Déu, és...", "o": ["l'ofrena", "la cremà", "la mascletà"], "e": "L'ofrena de flors."},
      {"q": "Quina festa se celebra el 25 de desembre?", "o": ["Nadal", "Pasqua", "Cap d'Any"], "e": "Nadal."},
      {"q": "El primer dia de l'any, l'1 de gener, és...", "o": ["Cap d'Any", "Nadal", "Reis"], "e": "Cap d'Any."},
      {"q": "Qui porta regals el 6 de gener?", "o": ["els Reis Mags", "els fallers", "els turistes"], "e": "Els Reis Mags (o Reis d'Orient)."},
      {"q": "En quina festa de primavera mengem la mona?", "o": ["Pasqua", "Nadal", "les Falles"], "e": "La mona de Pasqua."},
      {"q": "El dia que fas anys és el teu...", "o": ["aniversari", "casament", "bateig"], "e": "L'aniversari."},
      {"q": "Què dius a algú el dia del seu aniversari?", "o": ["Per molts anys!", "Bon profit!", "Bon viatge!"], "e": "Per molts anys!"},
      {"q": "Què dius a la gent el dia de Nadal?", "o": ["Bon Nadal!", "Bon profit!", "Que et millores!"], "e": "Bon Nadal!"},
      {"q": "La celebració en què es casen dues persones és...", "o": ["el casament", "el bateig", "l'aniversari"], "e": "El casament (o la boda)."},
      {"q": "Els coets de colors que il·luminen el cel de nit són...", "o": ["els focs artificials", "les campanes", "les fogueres"], "e": "Els focs artificials."},
      {"q": "Escriu el nom de la festa del 25 de desembre.", "a": ["Nadal"], "e": "Nadal."},
      {"q": "Escriu on vas a vore pel·lícules.", "a": ["cine", "el cine", "al cine", "cinema", "al cinema"], "e": "Al cine (o cinema)."},
      {"q": "Escriu on guardes la roba quan vas de viatge.", "a": ["maleta", "la maleta", "una maleta"], "e": "La maleta."}
    ]
  },
  {
    "id": "9e98c74e-b152-480c-a5c8-c74760011079", "type": "vocab_salut", "sort_order": 7,
    "title": "La salut", "name": "Les malalties i els remeis",
    "content": "Símptomes i malalties comunes, el metge, la farmàcia i els remeis.", "icon": "💊", "color": "#B2DFDB",
    "exercises": [
      {"q": "Tinc tos i mocs: estic ___.", "o": ["refredat", "afamat", "avorrit"], "e": "Refredat: amb tos, mocs i a vegades febre."},
      {"q": "Tinc la temperatura molt alta: tinc...", "o": ["febre", "gana", "son"], "e": "Febre."},
      {"q": "Em fa mal el cap: tinc...", "o": ["mal de cap", "mal de panxa", "mal de queixal"], "e": "Mal de cap."},
      {"q": "Em fa mal una dent: tinc mal de...", "o": ["queixal", "cap", "esquena"], "e": "Mal de queixal."},
      {"q": "He menjat massa i em fa mal...", "o": ["la panxa", "l'orella", "el genoll"], "e": "Mal de panxa."},
      {"q": "Em fa mal quan empasse i tinc la gola roja: tinc mal de...", "o": ["gola", "panxa", "peu"], "e": "Mal de gola."},
      {"q": "Quan fas «atxim!»...", "o": ["esternudes", "tussis", "plores"], "e": "Esternudar."},
      {"q": "Quina malaltia de l'hivern dona febre i mal de cos?", "o": ["la grip", "el mal de queixal", "la ferida"], "e": "La grip."},
      {"q": "A la primavera em ploren els ulls i esternude per les flors: tinc...", "o": ["al·lèrgia", "grip", "fam"], "e": "Al·lèrgia."},
      {"q": "M'he caigut i no puc moure el braç: potser el tinc...", "o": ["trencat", "refredat", "cansat"], "e": "Trencat."},
      {"q": "Quan et talles, ix...", "o": ["sang", "suor", "llàgrimes"], "e": "Sang."},
      {"q": "Si prens massa sol, et pots...", "o": ["cremar", "refredar", "trencar"], "e": "Cremar-se amb el sol."},
      {"q": "No he dormit bé i estic molt...", "o": ["cansat", "refredat", "afamat"], "e": "Cansat."},
      {"q": "Qui ens visita quan estem malalts?", "o": ["el metge", "el mecànic", "el cambrer"], "e": "El metge (o la metgessa)."},
      {"q": "El metge de les dents és...", "o": ["el dentista", "l'oculista", "el pediatre"], "e": "El dentista."},
      {"q": "El metge dels xiquets és...", "o": ["el pediatre", "el dentista", "l'oculista"], "e": "El pediatre."},
      {"q": "El metge dels ulls és...", "o": ["l'oculista", "el dentista", "el pediatre"], "e": "L'oculista."},
      {"q": "Per a anar al metge, primer has de demanar...", "o": ["cita", "recepta", "factura"], "e": "Demanar cita."},
      {"q": "El lloc de salut del barri, més xicotet que l'hospital, és...", "o": ["el centre de salut", "la farmàcia", "l'ajuntament"], "e": "El centre de salut."},
      {"q": "El paper on el metge escriu els medicaments és...", "o": ["la recepta", "la factura", "la carta"], "e": "La recepta."},
      {"q": "On comprem els medicaments?", "o": ["a la farmàcia", "al forn", "a la carnisseria"], "e": "A la farmàcia."},
      {"q": "Un medicament xicotet que empassem amb aigua és...", "o": ["una pastilla", "una xeringa", "una tireta"], "e": "Una pastilla."},
      {"q": "Un medicament líquid i dolç per a la tos és...", "o": ["un xarop", "una bena", "una tireta"], "e": "Un xarop."},
      {"q": "Una crema que ens posem damunt de la pell és...", "o": ["una pomada", "una pastilla", "un xarop"], "e": "Una pomada."},
      {"q": "Amb què tapem una ferida xicoteta?", "o": ["amb una tireta", "amb una xeringa", "amb un termòmetre"], "e": "Amb una tireta."},
      {"q": "Amb què emboliquem un turmell torçat?", "o": ["amb una bena", "amb una tireta", "amb una pastilla"], "e": "Amb una bena."},
      {"q": "Amb què mirem si tenim febre?", "o": ["amb el termòmetre", "amb el rellotge", "amb el telèfon"], "e": "Amb el termòmetre."},
      {"q": "Amb què es posa una injecció?", "o": ["amb una xeringa", "amb una tireta", "amb una bena"], "e": "Amb una xeringa."},
      {"q": "Si és molt greu, has d'anar a...", "o": ["urgències", "la perruqueria", "el gimnàs"], "e": "A urgències de l'hospital."},
      {"q": "Quin vehicle porta els malalts a l'hospital?", "o": ["l'ambulància", "el taxi", "el tramvia"], "e": "L'ambulància."},
      {"q": "Una persona malalta que atén el metge és...", "o": ["un pacient", "un client", "un alumne"], "e": "Un pacient."},
      {"q": "Quan estàs malalt, el metge et diu que has de fer...", "o": ["repòs", "esport", "festa"], "e": "Fer repòs: descansar."},
      {"q": "Quan una persona malalta es posa bé, es...", "o": ["cura", "trenca", "refreda"], "e": "Curar-se."},
      {"q": "Què li dius a una persona que està malalta?", "o": ["Que et millores!", "Bon profit!", "Per molts anys!"], "e": "Que et millores!"},
      {"q": "Escriu on comprem els medicaments.", "a": ["farmàcia", "la farmàcia", "a la farmàcia"], "e": "A la farmàcia."},
      {"q": "Escriu la paraula: tinc la temperatura molt alta, tinc ___.", "a": ["febre"], "e": "Febre."},
      {"q": "Escriu el nom de la persona que ens cura quan estem malalts.", "a": ["metge", "metgessa", "el metge", "la metgessa"], "e": "El metge o la metgessa."}
    ]
  },
  {
    "id": "a3a75594-576c-4088-9f19-68b24435470e", "type": "vocab_adjectius", "sort_order": 8,
    "title": "Com és? Adjectius", "name": "Adjectius referits a persones i coses",
    "content": "Adjectius per a descriure l'aspecte i el caràcter de les persones i les coses.", "icon": "🎭", "color": "#D7CCC8",
    "exercises": [
      {"q": "Una persona que pesa molt és...", "o": ["grossa", "prima", "baixa"], "e": "Grossa."},
      {"q": "Quin és el contrari de «gros»?", "o": ["prim", "alt", "lleig"], "e": "Gros ↔ prim."},
      {"q": "Quin és el contrari de «guapo»?", "o": ["lleig", "prim", "ros"], "e": "Guapo ↔ lleig."},
      {"q": "Una persona amb els cabells de color groc és...", "o": ["rossa", "morena", "pèl-roja"], "e": "Rossa."},
      {"q": "Una persona amb els cabells rojos és...", "o": ["pèl-roja", "rossa", "morena"], "e": "Pèl-roja."},
      {"q": "Una persona que no té cabells és...", "o": ["calba", "rossa", "arrissada"], "e": "Calba."},
      {"q": "Els cabells que no són llisos són...", "o": ["arrissats", "llargs", "curts"], "e": "Arrissats ↔ llisos."},
      {"q": "Una persona de noranta anys és una persona...", "o": ["gran", "jove", "xicoteta"], "e": "Una persona gran (o major)."},
      {"q": "Una persona de díhuit anys és...", "o": ["jove", "gran", "vella"], "e": "Jove."},
      {"q": "Una persona que sempre riu i està contenta és...", "o": ["alegre", "trista", "avorrida"], "e": "Alegre."},
      {"q": "Quin és el contrari de «simpàtic»?", "o": ["antipàtic", "alegre", "treballador"], "e": "Simpàtic ↔ antipàtic."},
      {"q": "Una persona que no vol treballar és...", "o": ["gandula", "treballadora", "generosa"], "e": "Gandula ↔ treballadora."},
      {"q": "Una persona que compartix les seues coses és...", "o": ["generosa", "egoista", "tímida"], "e": "Generosa."},
      {"q": "Una persona que només pensa en ella mateixa és...", "o": ["egoista", "generosa", "amable"], "e": "Egoista."},
      {"q": "Una persona a qui li costa parlar amb gent nova és...", "o": ["tímida", "xarraire", "simpàtica"], "e": "Tímida."},
      {"q": "Una persona que sempre diu la veritat és...", "o": ["sincera", "mentidera", "tímida"], "e": "Sincera ↔ mentidera."},
      {"q": "Una persona que aprén ràpid i sap moltes coses és...", "o": ["llesta", "tonta", "gandula"], "e": "Llesta (o intel·ligent)."},
      {"q": "Una persona que tracta bé els altres és...", "o": ["amable", "maleducada", "egoista"], "e": "Amable."},
      {"q": "Quin és el contrari de «nerviós»?", "o": ["tranquil", "content", "trist"], "e": "Nerviós ↔ tranquil."},
      {"q": "Quin és el contrari de «content»?", "o": ["trist", "alegre", "feliç"], "e": "Content ↔ trist."},
      {"q": "Una persona que té molts diners és...", "o": ["rica", "pobra", "cara"], "e": "Rica ↔ pobra."},
      {"q": "Quin és el contrari de «car»?", "o": ["barat", "nou", "gran"], "e": "Car ↔ barat."},
      {"q": "Quin és el contrari de «nou»?", "o": ["vell", "xicotet", "barat"], "e": "Nou ↔ vell."},
      {"q": "Quin és el contrari de «llarg»?", "o": ["curt", "ample", "estret"], "e": "Llarg ↔ curt."},
      {"q": "Quin és el contrari de «ample»?", "o": ["estret", "llarg", "alt"], "e": "Ample ↔ estret."},
      {"q": "Quin és el contrari de «pesat»?", "o": ["lleuger", "dur", "fort"], "e": "Pesat ↔ lleuger."},
      {"q": "Quin és el contrari de «dur»?", "o": ["tou", "fort", "gros"], "e": "Dur ↔ tou."},
      {"q": "Quin és el contrari de «calent»?", "o": ["fred", "sec", "dolç"], "e": "Calent ↔ fred."},
      {"q": "Quin és el contrari de «net»?", "o": ["brut", "fosc", "buit"], "e": "Net ↔ brut."},
      {"q": "Quin és el contrari de «ple»?", "o": ["buit", "brut", "dur"], "e": "Ple ↔ buit."},
      {"q": "Quin és el contrari de «fàcil»?", "o": ["difícil", "ràpid", "lent"], "e": "Fàcil ↔ difícil."},
      {"q": "Quin és el contrari de «ràpid»?", "o": ["lent", "curt", "difícil"], "e": "Ràpid ↔ lent."},
      {"q": "Quin és el contrari de «clar»?", "o": ["fosc", "brut", "ple"], "e": "Clar ↔ fosc."},
      {"q": "Quin és el contrari de «mullat»?", "o": ["sec", "fred", "net"], "e": "Mullat ↔ sec."},
      {"q": "Com és el sucre?", "o": ["dolç", "salat", "àcid"], "e": "Dolç."},
      {"q": "Com és la llima?", "o": ["àcida", "dolça", "salada"], "e": "Àcida."},
      {"q": "Com és l'aigua de la mar?", "o": ["salada", "dolça", "amarga"], "e": "Salada."},
      {"q": "Una cosa que costa molts diners és...", "o": ["cara", "barata", "gratuïta"], "e": "Cara."},
      {"q": "Una cosa que no costa diners és...", "o": ["gratuïta", "cara", "barata"], "e": "Gratuïta."},
      {"q": "Un carrer on hi ha molt de soroll és...", "o": ["sorollós", "silenciós", "tranquil"], "e": "Sorollós ↔ silenciós."},
      {"q": "Una pel·lícula que no t'interessa gens i et fa dormir és...", "o": ["avorrida", "divertida", "interessant"], "e": "Avorrida."},
      {"q": "Una pel·lícula que et fa riure és...", "o": ["divertida", "avorrida", "trista"], "e": "Divertida."},
      {"q": "Un paisatge molt bonic és...", "o": ["preciós", "lleig", "brut"], "e": "Preciós."},
      {"q": "Quin és el femení de «trist»?", "o": ["trista", "tristesa", "triste"], "e": "Trist → trista."},
      {"q": "Quin és el femení de «simpàtic»?", "o": ["simpàtica", "simpàtiqua", "simpàtic"], "e": "Simpàtic → simpàtica."},
      {"q": "Quin és el femení de «amable»?", "o": ["amable", "amabla", "amablessa"], "e": "Amable és invariable."},
      {"q": "Escriu el contrari de «gran».", "a": ["xicotet", "menut", "petit"], "e": "Xicotet (o menut, petit)."},
      {"q": "Escriu el contrari de «bo».", "a": ["dolent"], "e": "Bo ↔ dolent."},
      {"q": "Escriu el contrari de «obert».", "a": ["tancat"], "e": "Obert ↔ tancat."},
      {"q": "Escriu el contrari de «alegre».", "a": ["trist"], "e": "Alegre ↔ trist."}
    ]
  }
]$data$::jsonb) AS t(
  id uuid, type text, sort_order smallint, title text, name text,
  content text, icon text, color text, exercises jsonb
);

INSERT INTO public.resources (id, name, type, category, content, difficulty, xp_earned, sort_order, metadata)
SELECT id, name, type, 'lexic_semantica', content, 'principiant', 10, sort_order,
       jsonb_build_object('icon', icon, 'color', color, 'section_name', title)
FROM practice_catalog
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  category = EXCLUDED.category,
  content = EXCLUDED.content,
  sort_order = EXCLUDED.sort_order,
  metadata = EXCLUDED.metadata;

-- Formació de paraules i Sinònims, antònims i cortesia, darrere del vocabulari.
UPDATE public.resources SET sort_order = 9 WHERE id = '2d99f341-c91b-4c70-9d21-75a239956f97';
UPDATE public.resources SET sort_order = 10 WHERE id = 'e1165f90-cd1d-4006-84f3-75bda93d947e';

DELETE FROM public.practice_exercises e
USING practice_catalog c
WHERE e.resource_id = c.id AND e.level = 'A2';

INSERT INTO public.practice_exercises (resource_id, level, position, kind, prompt, options, answers, explanation)
SELECT c.id, 'A2', x.ord,
       CASE WHEN x.e ? 'a' THEN 'fill' ELSE 'choice' END,
       x.e->>'q',
       CASE WHEN x.e ? 'o' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'o')) END,
       CASE WHEN x.e ? 'a' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'a')) ELSE ARRAY[x.e->'o'->>0] END,
       x.e->>'e'
FROM practice_catalog c
CROSS JOIN LATERAL jsonb_array_elements(c.exercises) WITH ORDINALITY AS x(e, ord);

DROP TABLE practice_catalog;
