-- Vocabulari usual del B1 (Quadern B1 de la JQCV): els àmbits que els
-- continguts de 20261001100000 (un per bloc de 3.1) no cobrien o cobrien poc.
-- S'hi afigen huit continguts de Lèxic i semàntica de nivell intermedi (el camp
-- i la ciutat, els vehicles i el trànsit, els jocs i els esports, l'actualitat,
-- la música, el cinema i el teatre, els diners i els negocis, la tecnologia i
-- els estats d'ànim i la descripció d'objectes), i més exercicis B1 per a la
-- família, l'habitatge, el treball i la naturalesa i l'oratge, darrere dels que
-- ja hi ha (a partir de la posició `offset`). Tornar a aplicar el fitxer no
-- duplica res.

CREATE TEMP TABLE practice_catalog AS
SELECT * FROM jsonb_to_recordset($data$[
  {
    "id": "2dbbc6f8-5f76-455f-acc3-af804cf153e2", "type": "b1_vocab_camp_ciutat", "sort_order": 13,
    "title": "El camp i la ciutat", "name": "Agricultura, ramaderia, vida rural i vida urbana",
    "content": "Els treballs del camp, les ferramentes, els cultius, els animals de granja i la comparació entre la vida al camp i a la ciutat (Vocabulari usual).", "icon": "🚜", "color": "#E6EE9C",
    "exercises": [
      {"q": "La persona que treballa la terra és...", "o": ["el llaurador (o agricultor)", "el ramader", "el pescador"], "e": "El llaurador o l'agricultor conrea la terra. El ramader cria bestiar."},
      {"q": "Posar les llavors a la terra perquè naixquen plantes és...", "o": ["sembrar", "collir", "podar"], "e": "Sembrar. Plantar és posar a terra una planta ja nascuda."},
      {"q": "Arreplegar els fruits quan estan madurs és...", "o": ["collir", "sembrar", "regar"], "e": "Collir: la collita. Collir taronges, olives, ametles..."},
      {"q": "La collita del raïm per a fer vi és...", "o": ["la verema", "la sega", "la batuda"], "e": "La verema (veremar). La sega és la collita del blat o de l'arròs."},
      {"q": "Tallar les branques dels arbres perquè creixquen millor és...", "o": ["podar", "empeltar", "sembrar"], "e": "Podar. Empeltar és unir una branca d'un arbre a un altre."},
      {"q": "Cultivar la terra, en general, és...", "o": ["conrear", "colgar", "llaurar el mar"], "e": "Conrear (o cultivar). Els conreus: els cultius."},
      {"q": "La ferramenta amb un mànec i una fulla de ferro per a cavar la terra és...", "o": ["l'aixada", "la falç", "el rasclet"], "e": "L'aixada. La falç té la fulla corba i servix per a segar."},
      {"q": "El vehicle de motor que s'usa per a llaurar i portar remolcs al camp és...", "o": ["el tractor", "la grua", "la furgoneta"], "e": "El tractor."},
      {"q": "El vehicle d'una roda que s'empeny per a portar terra o pedres és...", "o": ["el carretó", "el tractor", "el remolc"], "e": "El carretó (de mà)."},
      {"q": "Una construcció de plàstic o vidre per a cultivar plantes protegides del fred és...", "o": ["un hivernacle", "un magatzem", "un galliner"], "e": "Un hivernacle."},
      {"q": "El producte químic que s'usa per a matar els insectes que fan malbé els cultius és...", "o": ["un insecticida (o plaguicida)", "un adob", "un fertilitzant natural"], "e": "Insecticida o plaguicida. L'adob (o fems) alimenta la terra."},
      {"q": "Els excrements dels animals que s'usen per a adobar la terra són...", "o": ["els fems", "les llavors", "les arrels"], "e": "Els fems: adob natural."},
      {"q": "Un camp ple de tarongers és...", "o": ["un hort de tarongers (o taronjar)", "una vinya", "un arrossar"], "e": "Un hort de tarongers o un taronjar."},
      {"q": "Un camp de vinyes és...", "o": ["una vinya", "un oliverar", "un ametlerar"], "e": "La vinya. Oliverar: camp d'oliveres. Ametlerar: d'ametlers."},
      {"q": "Un camp inundat on es cultiva arròs és...", "o": ["un arrossar", "un secà", "un bancal d'ametlers"], "e": "Un arrossar (com els de l'Albufera)."},
      {"q": "Quina fruita és típica de la tardor i sol ser taronja i molt dolça?", "o": ["el caqui", "la bresquilla", "la cirera"], "e": "El caqui (de la Ribera). La bresquilla i la cirera són d'estiu i de primavera."},
      {"q": "Quina fruita roja, plena de grans, es menja a la tardor?", "o": ["la magrana", "la nespra", "l'albercoc"], "e": "La magrana."},
      {"q": "Quina verdura té fulles dures i es menja el cor, molt típica de Benicarló?", "o": ["la carxofa", "la carabasseta", "l'albergínia"], "e": "La carxofa de Benicarló."},
      {"q": "Un conjunt d'animals de granja (vaques, ovelles, cabres, porcs) és...", "o": ["el bestiar", "el ramat de gats", "la fauna salvatge"], "e": "El bestiar. Un grup d'ovelles o cabres que guarda un pastor és un ramat."},
      {"q": "La persona que guarda i porta a pasturar les ovelles és...", "o": ["el pastor", "el llaurador", "el carnisser"], "e": "El pastor. Pasturar: menjar herba al camp."},
      {"q": "La cria de l'ovella és...", "o": ["el corder", "el vedell", "el poltre"], "e": "El corder (o anyell). El vedell és fill de la vaca i el poltre, del cavall."},
      {"q": "La femella del cavall és...", "o": ["l'egua", "la mula", "la burra"], "e": "L'egua (o euga)."},
      {"q": "On dormen les gallines?", "o": ["al galliner", "a la quadra", "a la cort"], "e": "Al galliner. Els cavalls, a la quadra; els porcs, a la cort (o porquera)."},
      {"q": "Traure la llet a una vaca o a una cabra és...", "o": ["munyir", "esquilar", "pasturar"], "e": "Munyir. Esquilar és tallar la llana a les ovelles."},
      {"q": "Quin animal de granja diu «quiquiriquic» de matí?", "o": ["el gall", "l'ànec", "el porc"], "e": "El gall. La gallina pon ous i els pollets són les cries."},
      {"q": "Una casa de camp gran, amb terres al voltant, típica de l'interior, és...", "o": ["un mas (o una masia)", "un àtic", "un pis"], "e": "Un mas o una masia. A l'horta: l'alqueria."},
      {"q": "Els productes que es cultiven a prop del lloc on es venen són productes...", "o": ["de proximitat (o de quilòmetre zero)", "d'importació", "congelats"], "e": "De proximitat o de quilòmetre zero."},
      {"q": "Els aliments cultivats sense productes químics són...", "o": ["ecològics", "transgènics", "industrials"], "e": "Ecològics (o biològics)."},
      {"q": "L'abandó dels pobles perquè la gent se'n va a viure a la ciutat és...", "o": ["el despoblament rural", "l'eixample", "l'urbanisme"], "e": "El despoblament (o l'èxode rural)."},
      {"q": "Un avantatge de viure al camp és...", "o": ["la tranquil·litat i l'aire net", "el trànsit intens", "la contaminació"], "e": "Avantatges del camp: tranquil·litat, natura, aire net. Inconvenients: menys servicis i transport."},
      {"q": "Un inconvenient de viure en una gran ciutat és...", "o": ["el soroll i la contaminació", "la falta de botigues", "que no hi ha transport"], "e": "Inconvenients de la ciutat: soroll, contaminació, embussos, pisos cars."},
      {"q": "Un edifici molt alt, de moltes plantes, és...", "o": ["un gratacel", "una masia", "una barraca"], "e": "Un gratacel (com els de Benidorm)."},
      {"q": "Un conjunt de cases noves fora del nucli urbà, sovint amb piscina i jardí, és...", "o": ["una urbanització", "un polígon industrial", "una alqueria"], "e": "Una urbanització."},
      {"q": "Quan hi ha massa gent en un lloc, diem que hi ha...", "o": ["aglomeracions", "despoblament", "silenci"], "e": "Aglomeracions (de gent): lloc massificat."},
      {"q": "«En el meu poble tots ens coneixem i ens ajudem.» Quin valor destaca?", "o": ["la vida de veïnat", "la contaminació", "l'anonimat"], "e": "Al poble hi ha més relació entre veïns; a la ciutat, més anonimat."},
      {"q": "Un camí estret per on passen els animals i les persones pel camp és...", "o": ["una senda (o un camí rural)", "una autovia", "una avinguda"], "e": "Una senda, un sender o un camí rural."},
      {"q": "Un carrer molt ample, sovint amb arbres, d'una ciutat és...", "o": ["una avinguda (o un bulevard)", "una senda", "un atzucac"], "e": "Una avinguda. Un atzucac és un carrer sense eixida."},
      {"q": "Un carrer sense eixida és...", "o": ["un atzucac (o carreró sense eixida)", "una avinguda", "una rambla"], "e": "Un atzucac."},
      {"q": "Escriu el verb: tallar les branques d'un arbre perquè cresca millor.", "a": ["podar"], "e": "Podar."},
      {"q": "Escriu el nom de la collita del raïm.", "a": ["verema", "la verema"], "e": "La verema."},
      {"q": "Escriu la cria de la vaca.", "a": ["vedell", "el vedell", "vedella", "la vedella"], "e": "El vedell (o la vedella)."},
      {"q": "Escriu la paraula: lloc on dormen les gallines.", "a": ["galliner", "el galliner"], "e": "El galliner."}
    ]
  },
  {
    "id": "3c7dfeff-bd32-430c-a7dc-ba19c67ba89c", "type": "b1_vocab_transit", "sort_order": 14,
    "title": "Els vehicles i el trànsit", "name": "El cotxe, la conducció, les normes i les incidències",
    "content": "Els vehicles i les seues parts, la conducció, els senyals i les normes de trànsit, les multes, les avaries i els accidents (Vocabulari usual).", "icon": "🚗", "color": "#B0BEC5",
    "exercises": [
      {"q": "La peça rodona amb què es dirigix el cotxe és...", "o": ["el volant", "el fre", "el maleter"], "e": "El volant. Conduir: portar el volant."},
      {"q": "El pedal que servix per a parar el cotxe és...", "o": ["el fre", "l'accelerador", "l'embragatge"], "e": "El fre (frenar). L'accelerador fa anar més de pressa."},
      {"q": "On es posen les maletes en un cotxe?", "o": ["al maleter", "al capó", "al parabrisa"], "e": "Al maleter. El capó cobrix el motor."},
      {"q": "L'espill que permet veure què hi ha darrere del cotxe és...", "o": ["el retrovisor", "l'intermitent", "el para-xocs"], "e": "El retrovisor (interior i laterals)."},
      {"q": "Els llums que avisen que el cotxe girarà són...", "o": ["els intermitents", "els fars antiboira", "els llums de fre"], "e": "Els intermitents: posar l'intermitent abans de girar."},
      {"q": "El vidre de davant del cotxe és...", "o": ["el parabrisa", "el retrovisor", "el capó"], "e": "El parabrisa. Els eixugaparabrises el netegen quan plou."},
      {"q": "La peça de goma plena d'aire que cobrix la roda és...", "o": ["el pneumàtic", "el volant", "el depòsit"], "e": "El pneumàtic. Si es punxa, tens una punxada."},
      {"q": "Quan el pneumàtic perd aire perquè ha xafat un clau, tens...", "o": ["una punxada", "un embús", "una multa"], "e": "Una punxada: cal posar la roda de recanvi."},
      {"q": "La placa amb números i lletres que identifica el cotxe és...", "o": ["la matrícula", "el permís de circulació", "la ITV"], "e": "La matrícula."},
      {"q": "El que has de portar posat per seguretat en el cotxe, encara que el trajecte siga curt, és...", "o": ["el cinturó de seguretat", "el casc", "l'armilla salvavides"], "e": "El cinturó de seguretat és obligatori per a tots els ocupants."},
      {"q": "El document que et permet conduir és...", "o": ["el carnet (o permís) de conduir", "el passaport", "la targeta SIP"], "e": "El carnet de conduir. S'obté a l'autoescola."},
      {"q": "On aprens a conduir?", "o": ["a l'autoescola", "a la gasolinera", "al taller"], "e": "A l'autoescola: examen teòric i examen pràctic."},
      {"q": "La revisió obligatòria que es fa als cotxes per a comprovar que estan en bon estat és...", "o": ["la ITV (inspecció tècnica de vehicles)", "la ITC", "el peatge"], "e": "La ITV."},
      {"q": "On porten el cotxe quan té una avaria?", "o": ["al taller (mecànic)", "a l'autoescola", "a la ITV"], "e": "Al taller. El mecànic repara el cotxe."},
      {"q": "Quan el cotxe s'espatla i no pot continuar, ha tingut...", "o": ["una avaria", "una multa", "un avançament"], "e": "Una avaria. Telefonar a la grua o a l'assegurança."},
      {"q": "El vehicle que s'emporta els cotxes mal aparcats o avariats és...", "o": ["la grua", "l'ambulància", "el camió del fem"], "e": "La grua."},
      {"q": "Una assegurança que cobrix tots els danys del teu cotxe és una assegurança...", "o": ["a tot risc", "a tercers", "de vida"], "e": "A tot risc. A tercers només cobrix els danys als altres."},
      {"q": "Un vehicle de dues rodes amb motor xicotet, que es pot conduir als quinze anys, és...", "o": ["un ciclomotor", "un camió", "un patinet"], "e": "Un ciclomotor (o «moto de 50»)."},
      {"q": "Un vehicle per a transportar mercaderies, més xicotet que un camió, és...", "o": ["una furgoneta", "un autocar", "un tramvia"], "e": "Una furgoneta."},
      {"q": "Un autobús per a viatges llargs per carretera és...", "o": ["un autocar", "un tramvia", "un taxi"], "e": "Un autocar."},
      {"q": "Quan hi ha tants cotxes que no es poden moure, hi ha...", "o": ["un embús (o una retenció)", "un avançament", "una punxada"], "e": "Un embús, una retenció o una caravana de cotxes."},
      {"q": "El moment del dia amb més trànsit és l'hora...", "o": ["punta", "baixa", "lliure"], "e": "L'hora punta."},
      {"q": "Quan el semàfor està en groc (o ambre), has de...", "o": ["parar si pots fer-ho amb seguretat", "accelerar", "pitar"], "e": "Groc o ambre: precaució, el semàfor està a punt de posar-se en roig."},
      {"q": "El senyal octogonal roig que obliga a parar del tot és...", "o": ["el senyal d'estop (STOP)", "el cediu el pas", "el sentit obligatori"], "e": "STOP: cal parar del tot. El senyal de cediu el pas és triangular."},
      {"q": "Passar al cotxe que va davant de tu, pel carril de l'esquerra, és...", "o": ["avançar", "recular", "aparcar"], "e": "Avançar (fer un avançament)."},
      {"q": "Anar cap arrere amb el cotxe és fer...", "o": ["marxa arrere", "un avançament", "un revolt"], "e": "Fer marxa arrere (o recular)."},
      {"q": "Una corba en la carretera és...", "o": ["un revolt", "un voral", "un encreuament"], "e": "Un revolt (o una corba). Revolts perillosos."},
      {"q": "La franja al costat de la carretera, fora dels carrils, on pots parar en cas d'avaria, és...", "o": ["el voral", "la vorera", "la mitjana"], "e": "El voral (de la carretera). La vorera és a la ciutat."},
      {"q": "Deixar el cotxe parat al costat d'un altre cotxe aparcat, en el carril, és aparcar en...", "o": ["doble fila", "zona blava", "bateria"], "e": "Aparcar en doble fila: prohibit i sancionat."},
      {"q": "La zona on cal pagar per a aparcar durant un temps limitat és la zona...", "o": ["blava", "verda de vianants", "de càrrega i descàrrega"], "e": "La zona blava (amb parquímetre o aplicació)."},
      {"q": "La sanció en diners per no complir les normes de trànsit és...", "o": ["una multa", "un peatge", "una propina"], "e": "Una multa. Posar una multa; multar."},
      {"q": "L'aparell que controla la velocitat dels cotxes a la carretera és...", "o": ["el radar", "el parquímetre", "el semàfor"], "e": "El radar. Si vas massa de pressa: excés de velocitat."},
      {"q": "La prova per a saber si un conductor ha begut alcohol és...", "o": ["el control d'alcoholèmia", "la ITV", "l'examen pràctic"], "e": "Control d'alcoholèmia: bufar en l'etilòmetre."},
      {"q": "Quan dos cotxes es peguen un colp, diem que...", "o": ["han xocat (o han topat)", "han avançat", "han aparcat"], "e": "Xocar o topar: un xoc, un accident."},
      {"q": "Quan un vehicle colpeja un vianant, diem que l'ha...", "o": ["atropellat", "avançat", "multat"], "e": "Atropellar: un atropellament."},
      {"q": "On es carrega un cotxe elèctric?", "o": ["en un punt de recàrrega", "en un parquímetre", "en un radar"], "e": "En un punt (o estació) de recàrrega."},
      {"q": "«Hi ha obres en la carretera i ens han fet anar per un altre camí»: hem pres una...", "o": ["desviació", "dreta", "rotonda"], "e": "Una desviació."},
      {"q": "Conduir amb precaució, respectant les normes, és conduir de manera...", "o": ["responsable", "temerària", "distreta"], "e": "Responsable. Una conducció temerària és perillosa."},
      {"q": "Escriu el verb: deixar el cotxe parat en un lloc.", "a": ["aparcar", "estacionar"], "e": "Aparcar o estacionar."},
      {"q": "Escriu la paraula: lloc del cotxe on es posen les maletes.", "a": ["maleter", "el maleter"], "e": "El maleter."},
      {"q": "Escriu el nom del vehicle que s'emporta els cotxes mal aparcats.", "a": ["grua", "la grua"], "e": "La grua."},
      {"q": "Escriu la paraula: quan una roda perd l'aire, tens una ___.", "a": ["punxada"], "e": "Una punxada."}
    ]
  },
  {
    "id": "42fca25a-cf27-40c1-9dee-c1464a42d683", "type": "b1_vocab_esports", "sort_order": 15,
    "title": "Els jocs i els esports", "name": "Esports, competicions, jocs de taula i de cartes",
    "content": "El lèxic dels esports més habituals, de les competicions, dels jocs de taula i de cartes (Vocabulari usual).", "icon": "⚽", "color": "#B2DFDB",
    "exercises": [
      {"q": "En futbol, el jugador que para els xuts i pot tocar la pilota amb les mans és...", "o": ["el porter", "el davanter", "el defensa"], "e": "El porter guarda la porteria. El davanter ataca i el defensa defén."},
      {"q": "Pegar a la pilota amb el peu amb força és...", "o": ["xutar", "encistellar", "rematar amb la mà"], "e": "Xutar: fer un xut."},
      {"q": "El càstig quan es fa una falta dins de l'àrea és...", "o": ["un penal", "un córner", "un fora de joc"], "e": "Un penal (o penalti)."},
      {"q": "Quan l'àrbitre trau una targeta roja, el jugador...", "o": ["és expulsat", "marca un gol", "és canviat per un suplent sense càstig"], "e": "Targeta roja: expulsió. La groga és una amonestació."},
      {"q": "El jugador que espera a la banqueta per a entrar al partit és...", "o": ["el suplent", "el titular", "el capità"], "e": "El suplent. Els titulars comencen jugant."},
      {"q": "Si un partit d'eliminatòria acaba en empat, de vegades es juga...", "o": ["una pròrroga", "un descans", "un entrenament"], "e": "La pròrroga i, si cal, la tanda de penals."},
      {"q": "En bàsquet, ficar la pilota dins de la cistella és...", "o": ["encistellar", "xutar", "servir"], "e": "Encistellar: fer una cistella. Un triple val tres punts."},
      {"q": "En tennis, l'objecte amb què es pega a la pilota és...", "o": ["la raqueta", "el bat", "el pal"], "e": "La raqueta. La pilota ha de passar per damunt de la xarxa."},
      {"q": "En tennis, el primer colp de cada punt és...", "o": ["el servei", "el remat", "el rebot"], "e": "El servei (servir). Un partit es dividix en sets."},
      {"q": "Quin estil de natació es fa panxa amunt?", "o": ["l'esquena", "la braça", "el crol"], "e": "Esquena. Altres estils: crol, braça i papallona."},
      {"q": "Una cursa a peu de 42 quilòmetres és...", "o": ["una marató", "un esprint", "una mitja marató"], "e": "La marató (42,195 km). La mitja marató té 21 km."},
      {"q": "El lloc on acaba una cursa és...", "o": ["la meta", "l'eixida", "el podi"], "e": "La meta. La cursa comença a l'eixida."},
      {"q": "Una cursa en què els corredors d'un equip es passen el testimoni és...", "o": ["una cursa de relleus", "una marató", "una contrarellotge"], "e": "Relleus: cada atleta corre un tram."},
      {"q": "En una volta ciclista, cada una de les curses d'un dia és...", "o": ["una etapa", "una pròrroga", "un set"], "e": "Una etapa. El líder porta el mallot groc (o el de líder)."},
      {"q": "La plataforma on pugen els tres primers classificats és...", "o": ["el podi", "la graderia", "la banqueta"], "e": "El podi: medalla d'or, de plata i de bronze."},
      {"q": "La millor marca de tots els temps en una prova és...", "o": ["el rècord", "l'empat", "el resultat"], "e": "Batre (o superar) un rècord."},
      {"q": "El partit que decidix qui guanya el campionat és...", "o": ["la final", "la semifinal", "els quarts de final"], "e": "La final. Abans: quarts de final i semifinals."},
      {"q": "L'equip que acaba segon en un campionat és...", "o": ["el subcampió", "el campió", "el descendit"], "e": "Subcampió. Baixar de categoria és descendir."},
      {"q": "Quan un club contracta un jugador nou, diem que l'ha...", "o": ["fitxat", "expulsat", "eliminat"], "e": "Fitxar: un fitxatge."},
      {"q": "L'organització que regula un esport en un territori és...", "o": ["la federació", "l'afició", "la penya"], "e": "La federació (de pilota, de futbol...). Una penya és un grup d'aficionats."},
      {"q": "Quan un equip perd un partit i ja no pot continuar en la competició, queda...", "o": ["eliminat", "classificat", "empatat"], "e": "Eliminat. Classificar-se és passar a la ronda següent."},
      {"q": "Un esport que es practica amb un company contra una altra parella, amb pales, en una pista tancada amb vidres, és...", "o": ["el pàdel", "el frontó", "el bàdminton"], "e": "El pàdel."},
      {"q": "Fer exercici per a preparar-se per a una competició és...", "o": ["entrenar-se", "escalfar la cadira", "retirar-se"], "e": "Entrenar(-se): l'entrenament, l'entrenador."},
      {"q": "Un joc d'estratègia en un tauler de 64 caselles, amb rei, reina, torres, alfils, cavalls i peons, és...", "o": ["els escacs", "les dames", "el parxís"], "e": "Els escacs. L'objectiu és fer escac i mat al rei."},
      {"q": "Un joc de taula amb un dau i fitxes de quatre colors és...", "o": ["el parxís", "els escacs", "el dòmino"], "e": "El parxís: tirar el dau i menjar fitxes."},
      {"q": "Un joc amb fitxes rectangulars marcades amb punts és...", "o": ["el dòmino", "el parxís", "les dames"], "e": "El dòmino."},
      {"q": "Quins són els quatre pals de la baralla espanyola?", "o": ["oros, copes, espases i bastos", "cors, piques, diamants i trèvols", "reis, cavalls, sotes i asos"], "e": "Oros, copes, espases i bastos. La baralla francesa té cors, piques, diamants i trèvols."},
      {"q": "Repartir les cartes entre els jugadors és...", "o": ["donar (o repartir) les cartes", "barallar les cartes", "tallar"], "e": "Repartir o donar. Barallar (o remenar) les cartes és mesclar-les."},
      {"q": "Un joc en què has de muntar una imatge amb moltes peces xicotetes és...", "o": ["un trencaclosques", "una endevinalla", "un embarbussament"], "e": "Un trencaclosques (o puzle)."},
      {"q": "Una pregunta enginyosa que has d'endevinar és...", "o": ["una endevinalla", "un trencaclosques", "un refrany"], "e": "Una endevinalla."},
      {"q": "Un joc electrònic que es juga en una consola o en l'ordinador és...", "o": ["un videojoc", "un joc de taula", "un trencaclosques"], "e": "Un videojoc. Jugar en línia amb altres persones."},
      {"q": "«Fer trampes» en un joc vol dir...", "o": ["no respectar les regles per a guanyar", "perdre a propòsit", "jugar molt bé"], "e": "Fer trampes: qui en fa és un trampós."},
      {"q": "Una persona que sap perdre sense enfadar-se té...", "o": ["esportivitat (o joc net)", "mal perdre", "molt de morro"], "e": "Esportivitat, joc net. Qui s'enfada quan perd té mal perdre."},
      {"q": "Les substàncies prohibides que alguns esportistes prenen per a rendir més són...", "o": ["el dopatge", "les vitamines", "l'entrenament"], "e": "El dopatge: els controls antidopatge."},
      {"q": "Quina d'estes paraules NO és un esport de raqueta?", "o": ["l'handbol", "el tennis", "el bàdminton"], "e": "L'handbol es juga amb les mans i una pilota."},
      {"q": "Quina d'estes paraules NO és un esport d'aigua?", "o": ["l'esgrima", "el waterpolo", "el piragüisme"], "e": "L'esgrima és un esport de combat amb espasa."},
      {"q": "Escriu el verb: ficar la pilota a la cistella.", "a": ["encistellar"], "e": "Encistellar."},
      {"q": "Escriu la paraula: lloc on acaba una cursa.", "a": ["meta", "la meta"], "e": "La meta."},
      {"q": "Escriu el joc de taula amb rei, reina, torres i peons.", "a": ["escacs", "els escacs"], "e": "Els escacs."},
      {"q": "Escriu la paraula: jugador que para els xuts a la porteria.", "a": ["porter", "el porter", "portera", "la portera"], "e": "El porter o la portera."}
    ]
  },
  {
    "id": "5ca81c57-fb9e-4e6b-b74a-2b62312e705d", "type": "b1_vocab_actualitat", "sort_order": 16,
    "title": "Els esdeveniments actuals", "name": "Mitjans de comunicació, política, societat i successos",
    "content": "El lèxic per a entendre i comentar les notícies: els mitjans, la política, la societat, el medi ambient i els successos (Vocabulari usual).", "icon": "📰", "color": "#E1BEE7",
    "exercises": [
      {"q": "El títol d'una notícia, escrit amb lletra gran, és...", "o": ["el titular", "el peu de foto", "l'editorial"], "e": "El titular. La portada és la primera pàgina del diari."},
      {"q": "Un article on el diari expressa la seua opinió oficial és...", "o": ["l'editorial", "la notícia", "la cartellera"], "e": "L'editorial. Els articles d'opinió els signen col·laboradors."},
      {"q": "Un text periodístic llarg, amb entrevistes i fotos, sobre un tema concret és...", "o": ["un reportatge", "un titular", "una esquela"], "e": "Un reportatge."},
      {"q": "El periodista que viu en un altre país i n'envia les notícies és...", "o": ["el corresponsal", "el locutor", "el redactor en cap"], "e": "El corresponsal."},
      {"q": "Una reunió en què una persona important informa els periodistes és...", "o": ["una roda de premsa", "una tertúlia", "una manifestació"], "e": "Una roda de premsa (o conferència de premsa)."},
      {"q": "El programa de televisió o de ràdio que dona les notícies del dia és...", "o": ["el noticiari (o les notícies)", "el concurs", "la sèrie"], "e": "El noticiari (o informatiu)."},
      {"q": "Un programa on diverses persones debaten sobre l'actualitat és...", "o": ["una tertúlia (o un debat)", "un documental", "un anunci"], "e": "Una tertúlia o un debat."},
      {"q": "Una informació falsa que es difon com si fora certa és...", "o": ["una notícia falsa", "una exclusiva", "un rumor confirmat"], "e": "Una notícia falsa. Cal contrastar la font."},
      {"q": "Dir públicament que una informació no és certa és...", "o": ["desmentir-la", "confirmar-la", "publicar-la"], "e": "Desmentir. El desmentiment."},
      {"q": "Quan un contingut es compartix moltíssim en les xarxes en poc de temps, diem que s'ha fet...", "o": ["viral", "privat", "obsolet"], "e": "Viral."},
      {"q": "La persona o el document d'on trau la informació un periodista és...", "o": ["la font", "el titular", "la portada"], "e": "La font (fiable o poc fiable)."},
      {"q": "El dia que els ciutadans trien els seus representants hi ha...", "o": ["eleccions", "vaga", "una roda de premsa"], "e": "Eleccions: votar, el vot, l'urna, la papereta."},
      {"q": "El període en què els partits demanen el vot és...", "o": ["la campanya electoral", "la legislatura", "la jornada de reflexió"], "e": "La campanya electoral. El dia abans de votar és la jornada de reflexió."},
      {"q": "Els partits que no governen formen...", "o": ["l'oposició", "el govern", "la majoria absoluta"], "e": "L'oposició."},
      {"q": "El parlament de la Comunitat Valenciana són...", "o": ["les Corts Valencianes", "el Congrés", "el Senat"], "e": "Les Corts Valencianes. El govern és el Consell, presidit pel president de la Generalitat."},
      {"q": "Quan el parlament vota a favor d'una llei, l'...", "o": ["aprova", "deroga", "desmentix"], "e": "Aprovar una llei. Derogar és anul·lar-la."},
      {"q": "Un grup de gent que camina pel carrer per a protestar és...", "o": ["una manifestació", "una vaga", "un míting"], "e": "Una manifestació (manifestants). La vaga és deixar de treballar per protesta."},
      {"q": "L'augment general dels preus és...", "o": ["la inflació", "la deflació", "la rebaixa"], "e": "La inflació (o la pujada dels preus)."},
      {"q": "Una situació econòmica greu, amb molt d'atur i poca activitat, és...", "o": ["una crisi", "una bonança", "un superàvit"], "e": "Una crisi (econòmica)."},
      {"q": "Una persona que fuig del seu país per una guerra o una persecució és...", "o": ["un refugiat", "un turista", "un emigrant per vacances"], "e": "Un refugiat (demanar asil)."},
      {"q": "L'augment de la temperatura del planeta per culpa de l'activitat humana és...", "o": ["el canvi climàtic (o escalfament global)", "la gota freda", "la tardor"], "e": "El canvi climàtic."},
      {"q": "Un foc molt gran en una muntanya o un bosc és...", "o": ["un incendi forestal", "una foguera", "una barbacoa"], "e": "Un incendi forestal. Els bombers forestals l'apaguen."},
      {"q": "Un moviment fort i sobtat de la terra és...", "o": ["un terratrémol", "una riuada", "un tsunami"], "e": "Un terratrémol."},
      {"q": "Les energies que no s'esgoten, com la solar i l'eòlica, són...", "o": ["renovables", "fòssils", "nuclears"], "e": "Energies renovables: plaques solars, molins de vent (aerogeneradors)."},
      {"q": "La secció del diari amb robatoris, accidents i crims és...", "o": ["successos", "cultura", "economia"], "e": "La secció de successos."},
      {"q": "Prendre una cosa d'amagat, sense violència, és...", "o": ["furtar (un furt)", "atracar", "segrestar"], "e": "Furtar: un furt. Robar amb violència o forçant: un robatori. Atracar: amb amenaces."},
      {"q": "Quan la policia agafa una persona sospitosa, la...", "o": ["detén", "absol", "jutja"], "e": "Detindre: el detingut, la detenció."},
      {"q": "La persona que ha vist un fet i ho conta davant del jutge és...", "o": ["el testimoni", "l'acusat", "l'advocat"], "e": "El testimoni (declarar com a testimoni)."},
      {"q": "La decisió final d'un jutge en un judici és...", "o": ["la sentència", "la denúncia", "l'acusació"], "e": "La sentència: condemnar o absoldre."},
      {"q": "Quan el jutge decidix que l'acusat no és culpable, l'...", "o": ["absol", "condemna", "detén"], "e": "Absoldre: l'acusat queda absolt."},
      {"q": "«Segons fonts del Govern, l'acord es firmarà demà.» La frase...", "o": ["atribuïx la informació a una font", "és una opinió del periodista", "és un anunci publicitari"], "e": "Segons..., d'acord amb..., fonts de...: atribuir la informació."},
      {"q": "Quina d'estes expressions s'usa per a donar l'opinió sobre una notícia?", "o": ["Al meu parer, és una mesura encertada.", "Segons el diari, hi ha hagut tres ferits.", "Ahir va ploure a Castelló."], "e": "Al meu parer, des del meu punt de vista, crec que... per a opinar."},
      {"q": "Una informació important que un mitjà publica abans que cap altre és...", "o": ["una exclusiva", "un desmentiment", "una esquela"], "e": "Una exclusiva."},
      {"q": "L'avís breu d'una notícia molt important que acaba de passar és...", "o": ["l'última hora", "el titular de dilluns", "l'editorial"], "e": "Notícia d'última hora."},
      {"q": "El periodista que presenta el programa de notícies és...", "o": ["el presentador", "el corresponsal", "el fotògraf"], "e": "El presentador o la presentadora."},
      {"q": "La persona que governa la Comunitat Valenciana és...", "o": ["el president de la Generalitat", "l'alcalde de València", "el president de la Diputació"], "e": "El president (o presidenta) de la Generalitat."},
      {"q": "Les persones que governen una conselleria de la Generalitat són...", "o": ["els consellers", "els regidors", "els diputats provincials"], "e": "Els consellers o conselleres (d'Educació, de Sanitat...)."},
      {"q": "Quan un partit té més de la meitat dels diputats, té...", "o": ["la majoria absoluta", "la minoria", "l'oposició"], "e": "La majoria absoluta. Si no la té, ha de pactar."},
      {"q": "Arribar a un acord entre diversos partits és...", "o": ["pactar", "dimitir", "votar en blanc"], "e": "Pactar: un pacte, una coalició."},
      {"q": "La prova per a saber què votarà la gent abans de les eleccions és...", "o": ["l'enquesta", "l'escrutini", "el míting"], "e": "L'enquesta (o sondeig). L'escrutini és el recompte dels vots."},
      {"q": "Una persona que ajuda sense cobrar en una catàstrofe és...", "o": ["un voluntari", "un funcionari", "un detingut"], "e": "Un voluntari (el voluntariat)."},
      {"q": "Escriu la paraula: títol d'una notícia.", "a": ["titular", "el titular"], "e": "El titular."},
      {"q": "Escriu el verb: dir que una notícia és falsa.", "a": ["desmentir"], "e": "Desmentir."},
      {"q": "Escriu la paraula: dia en què els ciutadans voten.", "a": ["eleccions", "les eleccions", "jornada electoral"], "e": "Les eleccions (la jornada electoral)."},
      {"q": "Escriu la paraula: moviment sobtat de la terra.", "a": ["terratrémol", "un terratrémol", "sisme"], "e": "El terratrémol (o sisme)."}
    ]
  },
  {
    "id": "7ae5ee2e-54b6-4541-b002-47670d46983a", "type": "b1_vocab_arts", "sort_order": 17,
    "title": "La música, el cinema i el teatre", "name": "Música, cinema, teatre, literatura i art",
    "content": "El lèxic dels temes culturals: la música i els instruments, el cinema, el teatre, la literatura i les arts plàstiques (Vocabulari usual).", "icon": "🎬", "color": "#F48FB1",
    "exercises": [
      {"q": "Una persona que escriu i canta les seues pròpies cançons és...", "o": ["un cantautor", "un director d'orquestra", "un apuntador"], "e": "Un cantautor o una cantautora."},
      {"q": "Les paraules d'una cançó són...", "o": ["la lletra", "la melodia", "el ritme"], "e": "La lletra. La melodia és la música i el ritme, el compàs."},
      {"q": "La sèrie de concerts que fa un grup en diferents ciutats és...", "o": ["una gira", "un assaig", "un festival"], "e": "Una gira (anar de gira)."},
      {"q": "Practicar una obra o una cançó abans de l'actuació és fer...", "o": ["un assaig", "una estrena", "una gira"], "e": "Un assaig (assajar)."},
      {"q": "Quan el públic demana que el grup toque una cançó més al final, el grup fa...", "o": ["un bis", "un entreacte", "un assaig"], "e": "Fer un bis."},
      {"q": "Un grup gran de músics que toquen instruments de corda, vent i percussió és...", "o": ["una orquestra", "un trio", "un cor"], "e": "Una orquestra, dirigida pel director amb la batuta. Un cor és un grup de cantants."},
      {"q": "El músic que toca tot sol o que destaca en una obra és...", "o": ["el solista", "el corista", "el tècnic de so"], "e": "El solista."},
      {"q": "Quin d'estos instruments és de corda?", "o": ["el violí", "la trompeta", "el tabal"], "e": "Corda: violí, guitarra, violoncel, contrabaix. Vent: trompeta, flauta, clarinet. Percussió: tabal, bateria."},
      {"q": "Quin d'estos instruments és de vent?", "o": ["el clarinet", "la bateria", "el piano"], "e": "El clarinet, la flauta, el saxòfon, la trompeta, la tuba, la dolçaina..."},
      {"q": "Quin d'estos instruments és de percussió?", "o": ["la bateria", "el violoncel", "el saxòfon"], "e": "La bateria, el tabal, el bombo, els plats, el xilòfon."},
      {"q": "Un concert en què la música sona en el moment, no gravada, és un concert...", "o": ["en directe", "en diferit", "en playback"], "e": "En directe."},
      {"q": "La música d'una pel·lícula és...", "o": ["la banda sonora", "el guió", "el doblatge"], "e": "La banda sonora."},
      {"q": "El text amb els diàlegs i les escenes d'una pel·lícula és...", "o": ["el guió", "la sinopsi", "el tràiler"], "e": "El guió, escrit pel guionista."},
      {"q": "Un resum breu de l'argument d'una pel·lícula és...", "o": ["la sinopsi", "el guió", "la crítica"], "e": "La sinopsi."},
      {"q": "Un vídeo curt amb escenes d'una pel·lícula per a anunciar-la és...", "o": ["el tràiler (o avançament)", "el càsting", "el rodatge"], "e": "El tràiler."},
      {"q": "Filmar les escenes d'una pel·lícula és...", "o": ["rodar", "estrenar", "doblar"], "e": "Rodar: el rodatge."},
      {"q": "El conjunt d'actors i actrius d'una pel·lícula és...", "o": ["el repartiment", "el públic", "l'equip tècnic"], "e": "El repartiment. L'actor principal és el protagonista."},
      {"q": "Una pel·lícula curta, de menys de mitja hora, és...", "o": ["un curtmetratge", "un llargmetratge", "una sèrie"], "e": "Un curtmetratge. Una pel·lícula llarga: un llargmetratge."},
      {"q": "Una pel·lícula que mostra fets reals, sense actors, és...", "o": ["un documental", "una comèdia", "un musical"], "e": "Un documental."},
      {"q": "Una pel·lícula que té molt d'èxit i guanya molts diners és...", "o": ["un èxit de taquilla", "un fracàs", "una estrena privada"], "e": "Un èxit de taquilla."},
      {"q": "Posar les veus en una altra llengua a una pel·lícula és...", "o": ["doblar-la", "subtitular-la", "rodar-la"], "e": "Doblar: el doblatge."},
      {"q": "La cortina gran que tapa l'escenari d'un teatre és...", "o": ["el teló", "el decorat", "la platea"], "e": "El teló: s'alça el teló i comença l'obra."},
      {"q": "Els objectes i els panells que creen l'ambient de l'escena són...", "o": ["el decorat (o l'escenografia)", "el vestuari", "el repartiment"], "e": "El decorat. El vestuari és la roba dels actors."},
      {"q": "La persona que escriu obres de teatre és...", "o": ["un dramaturg", "un apuntador", "un tramoista"], "e": "Un dramaturg (o autor teatral)."},
      {"q": "Una obra de teatre on parla un sol actor és...", "o": ["un monòleg", "un diàleg", "un musical"], "e": "Un monòleg."},
      {"q": "Una obra de teatre amb un final trist, en què el protagonista patix, és...", "o": ["una tragèdia", "una comèdia", "una farsa"], "e": "Una tragèdia. La comèdia fa riure."},
      {"q": "Uns ninots que es mouen amb fils o amb la mà en un espectacle infantil són...", "o": ["els titelles", "els ninots de falla", "els figurants"], "e": "Els titelles (o putxinel·lis)."},
      {"q": "Quan el públic aplaudix molt fort i dret al final, li fa...", "o": ["una ovació", "un xiulet", "un bis"], "e": "Una ovació (posar-se dret per a aplaudir)."},
      {"q": "Una obra literària llarga, en prosa, que conta una història és...", "o": ["una novel·la", "un poema", "una obra de teatre"], "e": "Una novel·la. Un conte és més curt."},
      {"q": "Cada una de les línies d'un poema és...", "o": ["un vers", "un capítol", "un paràgraf"], "e": "Un vers. Un conjunt de versos és una estrofa."},
      {"q": "Cada una de les parts en què es dividix una novel·la és...", "o": ["un capítol", "un vers", "un acte"], "e": "Un capítol. Les obres de teatre es dividixen en actes."},
      {"q": "L'empresa que publica llibres és...", "o": ["una editorial", "una llibreria", "una biblioteca"], "e": "Una editorial. La llibreria els ven i la biblioteca els presta."},
      {"q": "El conjunt de fets que passen en una novel·la o pel·lícula és...", "o": ["la trama (o l'argument)", "el pròleg", "l'índex"], "e": "La trama o l'argument."},
      {"q": "Un quadre que representa una persona és...", "o": ["un retrat", "un paisatge", "una natura morta"], "e": "Un retrat. Un autoretrat: el pintor es pinta a si mateix."},
      {"q": "Un quadre que representa fruites, flors o objectes és...", "o": ["una natura morta (o bodegó)", "un retrat", "un mural"], "e": "Una natura morta o un bodegó."},
      {"q": "L'art de fer figures en pedra, fusta o metall és...", "o": ["l'escultura", "la pintura", "la fotografia"], "e": "L'escultura (l'escultor)."},
      {"q": "Quin pintor valencià és famós per les seues escenes de platja plenes de llum?", "o": ["Joaquín Sorolla", "Pablo Picasso", "Salvador Dalí"], "e": "Joaquim (Joaquín) Sorolla, de València."},
      {"q": "«És una pel·lícula que t'enganxa des del principi fins al final.» Com la valora?", "o": ["Molt positivament", "Negativament", "No la valora"], "e": "Enganxar: interessar molt. Altres: és trepidant, emocionant, commovedora."},
      {"q": "«L'obra se'm va fer llarguíssima: no passava res.» Com la valora?", "o": ["Negativament", "Positivament", "No la valora"], "e": "Fer-se llarg, ser avorrit, pesat, lent."},
      {"q": "Escriu la paraula: text amb els diàlegs d'una pel·lícula.", "a": ["guió", "el guió"], "e": "El guió."},
      {"q": "Escriu la paraula: cortina gran del teatre.", "a": ["teló", "el teló"], "e": "El teló."},
      {"q": "Escriu la paraula: música d'una pel·lícula, la banda ___.", "a": ["sonora"], "e": "La banda sonora."},
      {"q": "Escriu la paraula: cada línia d'un poema.", "a": ["vers", "el vers"], "e": "El vers."}
    ]
  },
  {
    "id": "743422cf-9743-4f27-934a-948991958ae7", "type": "b1_vocab_diners", "sort_order": 18,
    "title": "Els diners i els negocis", "name": "El banc, l'estalvi, els impostos i l'empresa",
    "content": "El lèxic dels diners, el banc, les despeses i l'estalvi, els impostos i el món de l'empresa i els negocis (Vocabulari usual).", "icon": "💶", "color": "#C5E1A5",
    "exercises": [
      {"q": "La màquina del carrer per a traure diners amb la targeta és...", "o": ["el caixer automàtic", "el parquímetre", "la caixa registradora"], "e": "El caixer automàtic: traure diners."},
      {"q": "Posar diners en el teu compte bancari és...", "o": ["ingressar", "traure", "deure"], "e": "Ingressar (fer un ingrés). Traure: retirar diners."},
      {"q": "Enviar diners des del teu compte al d'una altra persona és fer...", "o": ["una transferència", "una devolució", "un ingrés en efectiu"], "e": "Una transferència (bancària)."},
      {"q": "El número secret de la targeta és...", "o": ["el PIN", "l'IBAN", "el NIF"], "e": "El PIN (número d'identificació personal)."},
      {"q": "La quantitat que cobra el banc per alguns servicis és...", "o": ["la comissió", "la nòmina", "la propina"], "e": "La comissió (bancària)."},
      {"q": "Els diners que et deixa el banc i que has de tornar amb interessos són...", "o": ["un préstec", "un estalvi", "un regal"], "e": "Un préstec. L'interés és el percentatge que pagues de més."},
      {"q": "Els diners que deus a algú són...", "o": ["un deute", "un estalvi", "un ingrés"], "e": "Un deute (deure diners). Tornar els diners: pagar el deute."},
      {"q": "Guardar diners per al futur és...", "o": ["estalviar", "malgastar", "invertir en borsa sempre"], "e": "Estalviar: els estalvis."},
      {"q": "Gastar diners en coses innecessàries és...", "o": ["malgastar", "estalviar", "ingressar"], "e": "Malgastar (o balafiar)."},
      {"q": "La previsió de quant gastaràs i quant ingressaràs en un temps és...", "o": ["el pressupost", "el rebut", "el balanç final"], "e": "El pressupost (familiar, d'una empresa...)."},
      {"q": "«Este cotxe m'ha costat un ull de la cara.» Vol dir que...", "o": ["ha sigut caríssim", "ha sigut molt barat", "l'ha comprat de segona mà"], "e": "Costar un ull de la cara: ser molt car."},
      {"q": "«A final de mes sempre estic escurat.» Vol dir que...", "o": ["no li queden diners", "té molts estalvis", "treballa molt"], "e": "Estar escurat: no tindre diners. També: anar just de diners."},
      {"q": "L'impost que es paga en comprar quasi qualsevol producte és...", "o": ["l'IVA", "l'IRPF", "l'IBI"], "e": "L'IVA (impost sobre el valor afegit). L'IBI es paga pels immobles."},
      {"q": "El document anual que fas per a declarar els teus ingressos a Hisenda és...", "o": ["la declaració de la renda", "la nòmina", "el contracte"], "e": "La declaració de la renda (l'IRPF)."},
      {"q": "Les monedes xicotetes que et tornen quan pagues amb un bitllet gran són...", "o": ["el canvi (o la solta)", "la propina", "la comissió"], "e": "El canvi o la solta (monedes soltes)."},
      {"q": "Els diners que deixes de més a un cambrer per a agrair el servici són...", "o": ["la propina", "la comissió", "l'IVA"], "e": "La propina."},
      {"q": "Una persona que funda i dirigix la seua pròpia empresa és...", "o": ["un emprenedor (o empresari)", "un assalariat", "un aturat"], "e": "Un emprenedor o un empresari."},
      {"q": "La persona o empresa que ven productes a una altra empresa és...", "o": ["el proveïdor", "el client", "el soci"], "e": "El proveïdor. El client compra."},
      {"q": "La persona que compartix la propietat d'una empresa amb tu és...", "o": ["el soci", "el client", "el proveïdor"], "e": "El soci o la sòcia."},
      {"q": "Els diners que guanya una empresa després de pagar totes les despeses són...", "o": ["els beneficis", "les pèrdues", "els deutes"], "e": "Els beneficis (o guanys). El contrari: les pèrdues."},
      {"q": "Posar diners en un negoci per a guanyar-ne més és...", "o": ["invertir", "estalviar en un calaix", "malgastar"], "e": "Invertir: la inversió, l'inversor."},
      {"q": "Quan una empresa no pot pagar els deutes i ha de tancar, fa...", "o": ["fallida", "beneficis", "rebaixes"], "e": "Fer fallida (o anar a la bancarrota)."},
      {"q": "Una botiga que usa la marca i el model de negoci d'una gran empresa és...", "o": ["una franquícia", "una sucursal bancària", "una cooperativa"], "e": "Una franquícia."},
      {"q": "Una empresa propietat dels seus treballadors o socis, com moltes del camp valencià, és...", "o": ["una cooperativa", "una franquícia", "una multinacional"], "e": "Una cooperativa (agrícola, de consum...)."},
      {"q": "Les empreses que oferixen els mateixos productes que la teua són...", "o": ["la competència", "els proveïdors", "els socis"], "e": "La competència (competir)."},
      {"q": "Vendre productes a altres països és...", "o": ["exportar", "importar", "fabricar"], "e": "Exportar. Comprar-ne d'altres països: importar."},
      {"q": "Els anuncis per a donar a conéixer un producte són...", "o": ["la publicitat", "la factura", "la fallida"], "e": "La publicitat (una campanya publicitària)."},
      {"q": "El lloc on es compren i es venen accions d'empreses és...", "o": ["la borsa", "el mercat municipal", "la llotja de peix"], "e": "La borsa (de valors)."},
      {"q": "Pagar amb el mòbil a un amic de manera instantània és fer...", "o": ["un pagament per mòbil", "un xec", "una hipoteca"], "e": "Pagar amb el mòbil o amb una aplicació bancària."},
      {"q": "Un producte que ja ha sigut usat per una altra persona és de...", "o": ["segona mà", "primera mà", "fàbrica"], "e": "De segona mà."},
      {"q": "Una targeta que et permet pagar ara i tornar els diners més avant és una targeta de...", "o": ["crèdit", "dèbit", "fidelització"], "e": "De crèdit. La de dèbit cobra directament del compte."},
      {"q": "El compte del banc on tens els diners per als pagaments habituals és el compte...", "o": ["corrent", "d'estalvi a termini", "de crèdit"], "e": "El compte corrent. El document amb els moviments és l'extracte."},
      {"q": "Canviar euros per dòlars abans d'un viatge és canviar...", "o": ["moneda (o divises)", "de banc", "el PIN"], "e": "Canviar moneda o divises: el tipus de canvi."},
      {"q": "Pagar a algú per un treball fet o un servici és...", "o": ["remunerar", "estafar", "recaptar"], "e": "Remunerar: la remuneració."},
      {"q": "Enganyar algú per a quedar-se els seus diners és...", "o": ["estafar", "invertir", "estalviar"], "e": "Estafar: una estafa, un estafador."},
      {"q": "«Hem de fer números abans de comprar el cotxe.» Vol dir que...", "o": ["cal calcular si ens ho podem permetre", "cal aprendre matemàtiques", "cal jugar a la loteria"], "e": "Fer números: calcular les despeses i els ingressos."},
      {"q": "«Llançar la casa per la finestra» vol dir...", "o": ["gastar molts diners en una celebració", "fer obres a casa", "vendre la casa"], "e": "Tirar (o llançar) la casa per la finestra: no estalviar en una celebració."},
      {"q": "Comprar productes a l'engròs vol dir comprar-los...", "o": ["en grans quantitats", "d'un en un", "de segona mà"], "e": "A l'engròs (majorista). Al detall: en quantitats xicotetes."},
      {"q": "El document on una empresa detalla el que has comprat i el que has de pagar, amb l'IVA, és...", "o": ["la factura", "el pressupost", "la nòmina"], "e": "La factura (facturar)."},
      {"q": "Escriu el verb: guardar diners per al futur.", "a": ["estalviar"], "e": "Estalviar."},
      {"q": "Escriu la paraula: diners que deus a algú.", "a": ["deute", "un deute", "el deute"], "e": "Un deute."},
      {"q": "Escriu el contrari de «benefici».", "a": ["pèrdua", "pèrdues", "les pèrdues", "la pèrdua"], "e": "La pèrdua (les pèrdues)."},
      {"q": "Escriu el contrari d'«exportar».", "a": ["importar"], "e": "Importar."}
    ]
  },
  {
    "id": "cbe6905c-aba9-4c29-bda5-c29fbf1e241e", "type": "b1_vocab_tecnologia", "sort_order": 19,
    "title": "La tecnologia", "name": "Aparells, internet, xarxes socials i informàtica",
    "content": "Els aparells electrònics i les seues parts, les accions en l'ordinador i el mòbil, internet, el correu electrònic, les xarxes socials i la seguretat digital (Vocabulari usual).", "icon": "💻", "color": "#90CAF9",
    "exercises": [
      {"q": "Un ordinador xicotet que es pot plegar i portar amb tu és...", "o": ["un portàtil", "un ordinador de taula", "un servidor"], "e": "Un (ordinador) portàtil."},
      {"q": "Un dispositiu pla amb pantalla tàctil, més gran que un mòbil, és...", "o": ["una tauleta", "un teclat", "un altaveu"], "e": "Una tauleta (tàctil)."},
      {"q": "La peça amb tecles per a escriure en l'ordinador és...", "o": ["el teclat", "el ratolí", "el monitor"], "e": "El teclat. El ratolí mou el cursor per la pantalla."},
      {"q": "L'aparell que servix per a passar al paper un document de l'ordinador és...", "o": ["la impressora", "l'escàner", "l'altaveu"], "e": "La impressora (imprimir). L'escàner fa el contrari: digitalitza un paper."},
      {"q": "El cable o l'aparell per a carregar la bateria del mòbil és...", "o": ["el carregador", "l'endoll", "l'auricular"], "e": "El carregador. L'endoll és on es connecta a la paret."},
      {"q": "Quan el mòbil es queda sense energia, s'ha quedat sense...", "o": ["bateria", "cobertura", "memòria"], "e": "Sense bateria. Sense cobertura: sense senyal de xarxa."},
      {"q": "Una aplicació xicoteta del mòbil és...", "o": ["una app (o aplicació)", "un cable", "un fitxer"], "e": "Una aplicació (app)."},
      {"q": "Passar un fitxer d'internet al teu dispositiu és...", "o": ["descarregar-lo (o baixar-lo)", "penjar-lo", "esborrar-lo"], "e": "Descarregar o baixar. El contrari: penjar (o pujar) un fitxer a internet."},
      {"q": "Posar un programa en l'ordinador perquè funcione és...", "o": ["instal·lar-lo", "desinstal·lar-lo", "imprimir-lo"], "e": "Instal·lar. Llevar-lo: desinstal·lar."},
      {"q": "Posar al dia un programa o el sistema del mòbil amb la versió nova és...", "o": ["actualitzar-lo", "reiniciar-lo", "formatar-lo"], "e": "Actualitzar: una actualització."},
      {"q": "Guardar un document en l'ordinador és...", "o": ["desar-lo", "esborrar-lo", "retallar-lo"], "e": "Desar (o guardar)."},
      {"q": "Copiar un text i posar-lo en un altre lloc és «copiar i ___».", "o": ["apegar (o enganxar)", "esborrar", "desar"], "e": "Copiar i apegar (o enganxar). Retallar: llevar-lo del lloc original."},
      {"q": "Quan l'ordinador es bloqueja i no respon, diem que s'ha...", "o": ["penjat", "carregat", "descarregat"], "e": "Penjar-se: l'ordinador s'ha penjat. Cal reiniciar-lo."},
      {"q": "Apagar i tornar a encendre un aparell és...", "o": ["reiniciar-lo", "actualitzar-lo", "instal·lar-lo"], "e": "Reiniciar."},
      {"q": "Un conjunt de documents agrupats en un lloc de l'ordinador és...", "o": ["una carpeta", "un enllaç", "un navegador"], "e": "Una carpeta. Cada document és un fitxer (o arxiu)."},
      {"q": "El programa que s'usa per a navegar per internet és...", "o": ["el navegador", "el cercador", "el teclat"], "e": "El navegador. El cercador és la pàgina per a buscar informació."},
      {"q": "El text o el botó en què fas clic per a anar a una altra pàgina web és...", "o": ["un enllaç", "un adjunt", "un perfil"], "e": "Un enllaç."},
      {"q": "El document que envies amb un correu electrònic és...", "o": ["un fitxer adjunt", "una contrasenya", "una signatura"], "e": "Un fitxer adjunt (adjuntar un document)."},
      {"q": "Els correus de publicitat que no has demanat són...", "o": ["el correu brossa", "els adjunts", "els esborranys"], "e": "Correu brossa (o correu no desitjat)."},
      {"q": "Un correu que has començat a escriure però encara no has enviat és...", "o": ["un esborrany", "una resposta", "un reenviament"], "e": "Un esborrany."},
      {"q": "La paraula secreta per a entrar en un compte és...", "o": ["la contrasenya", "el nom d'usuari", "l'adreça"], "e": "La contrasenya. Ha de ser segura i no compartir-la."},
      {"q": "Entrar en el teu compte amb el nom d'usuari i la contrasenya és...", "o": ["iniciar la sessió", "tancar la sessió", "donar-se de baixa"], "e": "Iniciar la sessió. En acabar, tancar la sessió."},
      {"q": "La connexió a internet sense fils és...", "o": ["el wifi", "el cable de xarxa", "el bluetooth"], "e": "El wifi (la xarxa sense fils)."},
      {"q": "Guardar els fitxers en servidors d'internet per a accedir-hi des de qualsevol lloc és guardar-los...", "o": ["al núvol", "al calaix", "a la paperera"], "e": "Al núvol."},
      {"q": "Una còpia dels teus fitxers per si es perden és...", "o": ["una còpia de seguretat", "un esborrany", "una captura de pantalla"], "e": "Una còpia de seguretat."},
      {"q": "Una imatge del que es veu en la pantalla en un moment és...", "o": ["una captura de pantalla", "un fons de pantalla", "un perfil"], "e": "Una captura de pantalla."},
      {"q": "Un programa que fa malbé l'ordinador o roba dades és...", "o": ["un virus (o programari maliciós)", "un antivirus", "un navegador"], "e": "Un virus. L'antivirus el detecta i l'elimina."},
      {"q": "Una persona que entra sense permís en sistemes informàtics és...", "o": ["un pirata informàtic", "un programador", "un influenciador"], "e": "Un pirata informàtic."},
      {"q": "Les persones que veuen les publicacions d'un perfil en les xarxes socials són...", "o": ["els seguidors", "els proveïdors", "els usuaris de la biblioteca"], "e": "Els seguidors (seguir un perfil)."},
      {"q": "Posar una foto o un comentari en una xarxa social és...", "o": ["publicar-lo (o penjar-lo)", "esborrar-lo", "descarregar-lo"], "e": "Publicar o penjar."},
      {"q": "Una trucada en què es veu la cara de l'altra persona és...", "o": ["una videotrucada", "un missatge de veu", "un correu"], "e": "Una videotrucada."},
      {"q": "Un programa d'ordinador que imita la manera de pensar humana, per exemple per a respondre preguntes, és...", "o": ["la intel·ligència artificial", "el processador de textos", "el full de càlcul"], "e": "La intel·ligència artificial (IA)."},
      {"q": "El programa per a fer càlculs i taules amb files i columnes és...", "o": ["el full de càlcul", "el processador de textos", "el navegador"], "e": "El full de càlcul. El processador de textos servix per a escriure documents."},
      {"q": "«Abans de tirar el mòbil vell, porta'l a un punt de reciclatge.» És...", "o": ["un consell sobre l'ús responsable de la tecnologia", "una instrucció d'instal·lació", "una queixa"], "e": "Els aparells electrònics vells van al punt net (o deixalleria)."},
      {"q": "La part del dispositiu que guarda els fitxers és...", "o": ["la memòria (o disc dur)", "la pantalla", "el teclat"], "e": "La memòria o el disc dur. Una memòria USB és portàtil."},
      {"q": "L'aparell xicotet que es posa a les orelles per a escoltar música és...", "o": ["els auriculars", "els altaveus", "el micròfon"], "e": "Els auriculars (amb fil o sense fils)."},
      {"q": "Trobar la manera d'eixir d'un problema informàtic és...", "o": ["solucionar-lo", "formatar el ratolí", "penjar-lo"], "e": "Solucionar o resoldre un problema."},
      {"q": "Escriu el verb: posar un programa en l'ordinador.", "a": ["instal·lar"], "e": "Instal·lar."},
      {"q": "Escriu la paraula: paraula secreta per a entrar en un compte.", "a": ["contrasenya", "la contrasenya"], "e": "La contrasenya."},
      {"q": "Escriu el contrari de «descarregar» un fitxer.", "a": ["penjar", "pujar", "carregar"], "e": "Penjar o pujar (un fitxer a internet)."},
      {"q": "Escriu el nom de la peça que mou el cursor de l'ordinador.", "a": ["ratolí", "el ratolí"], "e": "El ratolí."}
    ]
  },
  {
    "id": "37563e69-ff08-4822-a5c1-3de1a9c57c37", "type": "b1_vocab_estats_objectes", "sort_order": 20,
    "title": "Estats d'ànim i descripcions", "name": "Sentiments, emocions i com són els objectes",
    "content": "Lèxic per a descriure estats d'ànim i sentiments, expressions fetes relacionades i adjectius per a descriure objectes: forma, mida, pes, textura, material i estat (Vocabulari usual).", "icon": "😊", "color": "#FFF59D",
    "exercises": [
      {"q": "Una persona que ha perdut les ganes de fer coses i està trista des de fa temps està...", "o": ["desanimada", "eufòrica", "il·lusionada"], "e": "Desanimat (o deprimit, si és greu). El contrari: animat."},
      {"q": "Quan esperes amb alegria que passe una cosa, estàs...", "o": ["il·lusionat", "decebut", "avorrit"], "e": "Il·lusionat: tindre il·lusió per alguna cosa."},
      {"q": "Quan una cosa no ha sigut tan bona com esperaves, estàs...", "o": ["decebut", "il·lusionat", "orgullós"], "e": "Decebut: una decepció."},
      {"q": "Quan tens molta faena i poc temps, i et sents pressionat, estàs...", "o": ["estressat", "relaxat", "avorrit"], "e": "Estressat: l'estrés."},
      {"q": "Quan tens una por i una inquietud molt fortes, estàs...", "o": ["angoixat", "content", "orgullós"], "e": "Angoixat: l'angoixa."},
      {"q": "Quan sents vergonya, estàs...", "o": ["avergonyit", "agraït", "sorprés"], "e": "Avergonyit (tindre vergonya). Posar-se roig de vergonya."},
      {"q": "Quan algú t'ha ajudat i li vols donar les gràcies, estàs...", "o": ["agraït", "gelós", "furiós"], "e": "Agraït: l'agraïment."},
      {"q": "Quan estàs satisfet del que has fet tu o algú pròxim, estàs...", "o": ["orgullós", "avergonyit", "decebut"], "e": "Orgullós: sentir orgull."},
      {"q": "Quan trobes a faltar una persona o un lloc, la...", "o": ["enyores", "oblides", "odies"], "e": "Enyorar: l'enyorança. Trobar a faltar."},
      {"q": "Quan algú fa una cosa que no esperaves gens, et quedes...", "o": ["sorprés", "indiferent", "relaxat"], "e": "Sorprés (o sorpresa): la sorpresa."},
      {"q": "Quan estàs moltíssim enfadat, estàs...", "o": ["furiós", "tranquil", "tímid"], "e": "Furiós: estar fet una fúria."},
      {"q": "Quan no t'importa gens una cosa, et deixa...", "o": ["indiferent", "il·lusionat", "angoixat"], "e": "Indiferent: la indiferència."},
      {"q": "«Estic fet pols»: com està?", "o": ["Molt cansat", "Molt content", "Molt brut"], "e": "Estar fet pols: estar esgotat."},
      {"q": "«Està com un gínjol»: com està?", "o": ["Molt content i ple d'energia", "Malalt", "Enfadat"], "e": "Estar com un gínjol: estar molt bé, alegre i animat."},
      {"q": "«Hui està de mala lluna»: com està?", "o": ["De mal humor", "Molt alegre", "Molt cansat"], "e": "Estar de mala lluna (o de mal humor)."},
      {"q": "«Té els nervis a flor de pell»: com està?", "o": ["Molt nerviós", "Molt tranquil", "Molt trist"], "e": "Tindre els nervis a flor de pell: estar molt nerviós."},
      {"q": "«Va perdre els estreps i va començar a cridar»: què li va passar?", "o": ["Va perdre el control i s'enfadà molt", "Va caure del cavall", "Es va adormir"], "e": "Perdre els estreps (o els nervis): enfadar-se molt."},
      {"q": "«Sempre està en els núvols»: com és?", "o": ["Distret", "Molt atent", "Molt alt"], "e": "Estar en els núvols: estar distret."},
      {"q": "«Botava d'alegria quan li van donar la notícia»: com estava?", "o": ["Molt content", "Molt trist", "Molt cansat"], "e": "Botar d'alegria: estar molt content."},
      {"q": "«Té el cor en un puny»: com està?", "o": ["Molt preocupat i angoixat", "Molt enamorat", "Molt tranquil"], "e": "Tindre el cor en un puny: estar angoixat."},
      {"q": "Un objecte en forma de cercle és...", "o": ["rodó", "quadrat", "triangular"], "e": "Rodó. Altres formes: quadrat, rectangular, triangular, ovalat."},
      {"q": "Un objecte amb la punta fina, que pot fer mal, és...", "o": ["punxegut", "rom", "pla"], "e": "Punxegut. Rom: sense punta o sense tall."},
      {"q": "Un objecte que pesa molt és...", "o": ["pesat", "lleuger", "buit"], "e": "Pesat. El contrari: lleuger."},
      {"q": "Una superfície que fa mal al tacte perquè no és llisa és...", "o": ["aspra (o rugosa)", "suau", "llisa"], "e": "Aspre o rugós. El contrari: suau, llis."},
      {"q": "Un objecte que es trenca amb facilitat és...", "o": ["fràgil", "resistent", "elàstic"], "e": "Fràgil (com el vidre). Resistent: que no es trenca fàcilment."},
      {"q": "Un objecte que es pot doblegar sense trencar-se és...", "o": ["flexible", "rígid", "fràgil"], "e": "Flexible. El contrari: rígid."},
      {"q": "Un coixí o un matalàs que s'afona quan el prems és...", "o": ["tou", "dur", "rígid"], "e": "Tou. El contrari: dur."},
      {"q": "Un objecte de ferro que s'ha posat de color marró amb la humitat està...", "o": ["rovellat", "esquerdat", "abonyegat"], "e": "Rovellat: el rovell. Esquerdat: amb una esquerda. Abonyegat: amb bonys."},
      {"q": "Un got de vidre que té una línia trencada però no s'ha partit està...", "o": ["esquerdat", "rovellat", "descolorit"], "e": "Esquerdat: té una esquerda."},
      {"q": "Un objecte molt usat, que ja no està com nou, està...", "o": ["gastat", "a estrenar", "intacte"], "e": "Gastat (o desgastat)."},
      {"q": "Un material que no deixa passar l'aigua és...", "o": ["impermeable", "transparent", "absorbent"], "e": "Impermeable (com un xubasquer o una jaqueta de pluja)."},
      {"q": "Un material que deixa veure el que hi ha a l'altra banda és...", "o": ["transparent", "opac", "mat"], "e": "Transparent. Opac: no deixa passar la llum."},
      {"q": "Una cosa molt xicoteta és...", "o": ["diminuta", "enorme", "gegant"], "e": "Diminut (o menut, minúscul). El contrari: enorme, gegant."},
      {"q": "Un objecte de terra cuita, com els plats tradicionals de Manises, és de...", "o": ["ceràmica", "acer", "plàstic"], "e": "De ceràmica (o de fang). Manises i l'Alcora són famoses per la ceràmica."},
      {"q": "Per a descriure la finalitat d'un objecte diem...", "o": ["«Servix per a obrir llaunes.»", "«És de color blau.»", "«Pesa dos quilos.»"], "e": "Servix per a..., s'usa per a...: indica la funció."},
      {"q": "Escriu el contrari de «pesat».", "a": ["lleuger"], "e": "Lleuger."},
      {"q": "Escriu el contrari de «dur» (un matalàs).", "a": ["tou"], "e": "Tou."},
      {"q": "Escriu el verb: trobar a faltar una persona o un lloc.", "a": ["enyorar"], "e": "Enyorar."},
      {"q": "Escriu l'adjectiu: que es trenca amb facilitat.", "a": ["fràgil"], "e": "Fràgil."}
    ]
  }
]$data$::jsonb) AS t(
  id uuid, type text, sort_order smallint, title text, name text,
  content text, icon text, color text, exercises jsonb
);

INSERT INTO public.resources (id, name, type, category, content, difficulty, xp_earned, sort_order, metadata)
SELECT id, name, type, 'lexic_semantica', content, 'intermedi', 15, sort_order,
       jsonb_build_object('icon', icon, 'color', color, 'section_name', title)
FROM practice_catalog
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  category = EXCLUDED.category,
  content = EXCLUDED.content,
  difficulty = EXCLUDED.difficulty,
  xp_earned = EXCLUDED.xp_earned,
  sort_order = EXCLUDED.sort_order,
  metadata = EXCLUDED.metadata;

DELETE FROM public.practice_exercises e
USING practice_catalog c
WHERE e.resource_id = c.id AND e.level = 'B1';

INSERT INTO public.practice_exercises (resource_id, level, position, kind, prompt, options, answers, explanation)
SELECT c.id, 'B1', x.ord,
       CASE WHEN x.e ? 'a' THEN 'fill' ELSE 'choice' END,
       x.e->>'q',
       CASE WHEN x.e ? 'o' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'o')) END,
       CASE WHEN x.e ? 'a' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'a')) ELSE ARRAY[x.e->'o'->>0] END,
       x.e->>'e'
FROM practice_catalog c
CROSS JOIN LATERAL jsonb_array_elements(c.exercises) WITH ORDINALITY AS x(e, ord);

DROP TABLE practice_catalog;

CREATE TEMP TABLE practice_more AS
SELECT * FROM jsonb_to_recordset($data$[
  {
    "id": "3c2cdca6-70e4-4a53-99af-2db26e50aaea", "offset": 50,
    "exercises": [
      {"q": "Els familiers de la teua parella (sogres, cunyats...) són la família...", "o": ["política", "nombrosa", "monoparental"], "e": "La família política: els parents per matrimoni."},
      {"q": "Els pares dels teus fills casats entre ells (el sogre de ton fill) són els teus...", "o": ["consogres", "cunyats", "padrins"], "e": "Consogre i consogra: els pares de l'altre membre de la parella del teu fill."},
      {"q": "Les persones de la família que van viure fa molts anys, abans que tu, són els...", "o": ["avantpassats", "descendents", "hereus"], "e": "Els avantpassats. Els fills, néts i besnéts són els descendents."},
      {"q": "Una persona que ha perdut el pare i la mare és...", "o": ["orfe", "vidu", "solter"], "e": "Orfe (o òrfena). Vidu: qui ha perdut la parella."},
      {"q": "Fer legalment fill teu un xiquet que no és biològic és...", "o": ["adoptar-lo", "apadrinar-lo", "heretar-lo"], "e": "Adoptar: el fill adoptiu, l'adopció."},
      {"q": "Els béns i els diners que deixa una persona quan es mor són...", "o": ["l'herència", "la hipoteca", "el lloguer"], "e": "L'herència. Qui la rep és l'hereu o l'hereva. El testament diu com es repartix."},
      {"q": "Quan dos pares separats es repartixen el temps amb els fills, tenen la custòdia...", "o": ["compartida", "única", "provisional"], "e": "La custòdia compartida."},
      {"q": "En valencià, tindre una relació amorosa amb algú és...", "o": ["festejar", "conviure", "divorciar-se"], "e": "Festejar: el xicot i la xicota."},
      {"q": "Quan una parella decidix casar-se, diem que s'ha...", "o": ["promés (o compromés)", "separat", "divorciat"], "e": "Prometre's: el promés i la promesa."},
      {"q": "Quan dos persones que s'havien barallat tornen a ser amigues, es...", "o": ["reconcilien", "separen", "barallen"], "e": "Reconciliar-se: fer les paus."},
      {"q": "Una persona amb qui tens molta confiança i que t'entén és...", "o": ["un amic íntim", "un conegut", "un desconegut"], "e": "Un amic íntim (o de l'ànima). Un conegut és algú que coneixes poc."},
      {"q": "«Ens portem molt bé.» Vol dir que...", "o": ["tenim una bona relació", "vivim lluny", "ens veiem poc"], "e": "Portar-se bé (o mal) amb algú: tindre una bona (o mala) relació."}
    ]
  },
  {
    "id": "bb9d81a8-ec10-438f-bdca-ce5933d487eb", "offset": 46,
    "exercises": [
      {"q": "La part de fora d'un edifici, la que dona al carrer, és...", "o": ["la façana", "el replà", "el pati de llums"], "e": "La façana."},
      {"q": "La coberta d'un edifici, sovint plana, on es pot estendre la roba, és...", "o": ["el terrat", "la teulada", "el balcó"], "e": "El terrat (pla). La teulada té teules i és inclinada."},
      {"q": "L'espai de l'escala davant de les portes dels pisos és...", "o": ["el replà", "el rebedor", "el traster"], "e": "El replà."},
      {"q": "L'aparell per a obrir la porta del carrer des de dins de casa és...", "o": ["el porter automàtic (o intèrfon)", "el timbre de la bicicleta", "el pany"], "e": "El porter automàtic o l'intèrfon."},
      {"q": "On deixa el carter les cartes?", "o": ["a la bústia", "al replà", "a la finestra"], "e": "A la bústia."},
      {"q": "Les làmines que es baixen per a no deixar entrar la llum per la finestra són...", "o": ["les persianes", "les cortines de dutxa", "les rajoles"], "e": "Les persianes. Abaixar o alçar la persiana."},
      {"q": "Les peces de ceràmica que cobrixen el terra o les parets de la cuina i del bany són...", "o": ["les rajoles", "les teules", "les bigues"], "e": "Les rajoles (de València, de Manises...)."},
      {"q": "On ix l'aigua a la cuina i al bany?", "o": ["per l'aixeta", "per l'endoll", "per l'interruptor"], "e": "L'aixeta. Obrir o tancar l'aixeta."},
      {"q": "On es connecten els aparells elèctrics a la paret?", "o": ["a l'endoll", "a l'interruptor", "a l'aixeta"], "e": "A l'endoll. L'interruptor encén i apaga el llum."},
      {"q": "L'aparell que escalfa l'aigua de la dutxa és...", "o": ["el termo (o escalfador)", "el congelador", "el microones"], "e": "El termo o l'escalfador (d'aigua)."},
      {"q": "L'aparell que hi ha damunt dels fogons per a traure el fum de la cuina és...", "o": ["la campana extractora", "el forn", "la vitroceràmica"], "e": "La campana extractora."},
      {"q": "El moble amb calaixos per a guardar la roba és...", "o": ["la calaixera", "la prestatgeria", "la tauleta de nit"], "e": "La calaixera. La prestatgeria té prestatges per als llibres."},
      {"q": "El professional que arregla les canonades i les aixetes és...", "o": ["el lampista (o fontaner)", "l'electricista", "el fuster"], "e": "El lampista o fontaner. L'electricista, la llum; el fuster, la fusta."},
      {"q": "El professional que fa obres de construcció, posa rajoles i alça parets és...", "o": ["el paleta (o obrer de la construcció)", "el lampista", "el pintor"], "e": "El paleta."},
      {"q": "Fer obres en un pis per a millorar-lo és...", "o": ["reformar-lo", "llogar-lo", "hipotecar-lo"], "e": "Reformar: una reforma. Un pis reformat."},
      {"q": "Canviar-se de casa és...", "o": ["mudar-se (o fer la mudança)", "empadronar-se", "reformar"], "e": "Mudar-se: la mudança."},
      {"q": "Escriu la paraula: lloc on el carter deixa les cartes.", "a": ["bústia", "la bústia"], "e": "La bústia."},
      {"q": "Escriu la paraula: part de fora d'un edifici.", "a": ["façana", "la façana"], "e": "La façana."}
    ]
  },
  {
    "id": "d2eb464d-1df4-4fcd-9d67-26a8eb56d9f2", "offset": 43,
    "exercises": [
      {"q": "Les proves per a aconseguir una plaça fixa en l'Administració són...", "o": ["les oposicions", "les rebaixes", "les eleccions"], "e": "Les oposicions (opositar). Qui les aprova és funcionari."},
      {"q": "Una persona que treballa per a l'Administració amb una plaça fixa és...", "o": ["funcionària", "autònoma", "becària"], "e": "Funcionari o funcionària."},
      {"q": "Passar a un lloc de treball de més responsabilitat és tindre...", "o": ["un ascens", "un acomiadament", "una baixa"], "e": "Un ascens (ascendir, promocionar)."},
      {"q": "Fer compatible el treball amb la vida familiar és...", "o": ["conciliar", "cotitzar", "dimitir"], "e": "Conciliar la vida laboral i familiar: la conciliació."},
      {"q": "Els dies que pots faltar al treball quan naix un fill són el permís de...", "o": ["maternitat o paternitat (per naixement)", "vacances", "assumptes propis"], "e": "El permís per naixement i cura de menor (maternitat o paternitat)."},
      {"q": "Els diners que paga el treballador i l'empresa a la Seguretat Social per a la futura pensió són les...", "o": ["cotitzacions", "propines", "comissions"], "e": "Cotitzar: les cotitzacions a la Seguretat Social."},
      {"q": "Les pagues de més que alguns treballadors reben a l'estiu i per Nadal són les pagues...", "o": ["extra (o extraordinàries)", "mínimes", "de fiança"], "e": "Les pagues extra."},
      {"q": "Una persona molt treballadora diem que «treballa com...»", "o": ["una formiga", "un gat", "un peix"], "e": "Treballar com una formiga: ser molt feiner."}
    ]
  },
  {
    "id": "45f412d2-e3b7-406e-9e34-1d8dd18f2ddc", "offset": 50,
    "exercises": [
      {"q": "La part de la planta que està davall de terra i n'absorbix l'aigua és...", "o": ["l'arrel", "el tronc", "la fulla"], "e": "L'arrel. El tronc, les branques, les fulles, les flors i els fruits."},
      {"q": "La part de la planta d'on naix una planta nova és...", "o": ["la llavor", "la branca", "l'escorça"], "e": "La llavor. L'escorça és la pell del tronc."},
      {"q": "Un arbre que perd les fulles a la tardor és de fulla...", "o": ["caduca", "perenne", "punxeguda"], "e": "De fulla caduca. El pi i l'alzina són de fulla perenne."},
      {"q": "Quin animal marí intel·ligent, que salta fora de l'aigua, es pot veure davant de la costa valenciana?", "o": ["el dofí", "el tauró blanc", "la balena blava"], "e": "El dofí."},
      {"q": "Quin animal marí té huit braços amb ventoses?", "o": ["el pop", "el calamar", "la sépia"], "e": "El pop té huit potes; el calamar i la sépia, deu."},
      {"q": "Quin animal gelatinós del mar pot picar els banyistes?", "o": ["la medusa", "el cranc", "l'eriçó de mar"], "e": "La medusa. L'eriçó de mar té punxes."},
      {"q": "Quin crustaci camina de costat i té pinces?", "o": ["el cranc", "la gamba", "el musclo"], "e": "El cranc. La gamba i la llagosta també són crustacis."},
      {"q": "Quin mosquit ratllat negre i blanc, que pica de dia, s'ha estés per la costa?", "o": ["el mosquit tigre", "la mosca", "la vespa"], "e": "El mosquit tigre."},
      {"q": "Quin insecte groc i negre pica i no fa mel?", "o": ["la vespa", "l'abella", "la papallona"], "e": "La vespa. L'abella fa mel i viu en un rusc."},
      {"q": "Quin animal xicotet fa teles per a caçar insectes?", "o": ["l'aranya", "la formiga", "l'escarabat"], "e": "L'aranya: la teranyina."},
      {"q": "Un animal que només viu en un lloc del món, com el samaruc, és...", "o": ["endèmic", "invasor", "domèstic"], "e": "Endèmic. Una espècie invasora ve de fora i fa mal a les autòctones."},
      {"q": "Una espècie que pot desaparéixer del tot està en perill d'...", "o": ["extinció", "expansió", "hibernació"], "e": "En perill d'extinció. Una espècie protegida."},
      {"q": "«Fa un sol de justícia.» Vol dir que...", "o": ["fa un sol molt fort i molta calor", "està núvol", "plou poc"], "e": "Un sol de justícia: un sol molt fort."},
      {"q": "«Fa un fred que pela.» Vol dir que...", "o": ["fa moltíssim fred", "fa calor", "fa vent suau"], "e": "Fer un fred que pela: fer molt de fred."},
      {"q": "Quan el cel no té cap núvol, està...", "o": ["serè", "ennuvolat", "tapat"], "e": "Serè (o clar). Ennuvolat: amb núvols."},
      {"q": "Quan hi ha núvols però de tant en tant ix el sol, hi ha...", "o": ["clarianes", "calamarsa", "rosada"], "e": "Clarianes: espais sense núvols."},
      {"q": "Les temperatures més baixes que zero graus són temperatures...", "o": ["sota zero (o sota zero graus)", "màximes", "suaus"], "e": "Sota zero. Fer cinc graus sota zero."},
      {"q": "L'arc de colors que apareix al cel quan plou i fa sol és...", "o": ["l'arc de Sant Martí", "el llampec", "l'aurora"], "e": "L'arc de Sant Martí."},
      {"q": "La informació sobre el temps que farà els pròxims dies és...", "o": ["la previsió meteorològica", "la cartellera", "l'esquela"], "e": "La previsió (meteorològica) o l'oratge."},
      {"q": "Quan el mar està molt mogut, amb ones grans, diem que hi ha mar...", "o": ["brava (o forta marejada)", "en calma", "plana"], "e": "Mar brava (o mar grossa, marejada). Mar en calma: bonança."},
      {"q": "Escriu la paraula: part de la planta que està davall de terra.", "a": ["arrel", "l'arrel"], "e": "L'arrel."},
      {"q": "Escriu el contrari de «ennuvolat».", "a": ["serè", "clar", "assolellat"], "e": "Serè o clar."}
    ]
  }
]$data$::jsonb) AS t(id uuid, "offset" smallint, exercises jsonb);

DELETE FROM public.practice_exercises e
USING practice_more m
WHERE e.resource_id = m.id AND e.level = 'B1' AND e.position > m."offset";

INSERT INTO public.practice_exercises (resource_id, level, position, kind, prompt, options, answers, explanation)
SELECT c.id, 'B1', c."offset" + x.ord,
       CASE WHEN x.e ? 'a' THEN 'fill' ELSE 'choice' END,
       x.e->>'q',
       CASE WHEN x.e ? 'o' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'o')) END,
       CASE WHEN x.e ? 'a' THEN ARRAY(SELECT jsonb_array_elements_text(x.e->'a')) ELSE ARRAY[x.e->'o'->>0] END,
       x.e->>'e'
FROM practice_more c
CROSS JOIN LATERAL jsonb_array_elements(c.exercises) WITH ORDINALITY AS x(e, ord);

DROP TABLE practice_more;
